### ISSUE TITLE
[windows] Implement a Win32/UWP version of the embedder

### ISSUE THREAD

**Issue by stuartmorgan** [google/flutter-desktop-embedding#101]
The current implementation on Windows is a temporary solution using GLFW; the goal is to implement a more flexible, view-based solution that could be used in an existing application, similar to what currently exists on macOS.

See previous discussion in issue #6.

**Comment by clarkezone** [comment]
I have been making good progress on a Win32/UWP implementation based on Angle.  There are currently two engine changes blocking my fork:  the first is a null reference exception in Dart.  I have filed an issue on the Dart repo here https://github.com/dart-lang/sdk/issues/33826 and developed a fix here: https://github.com/clarkezone/sdk/commit/42f67a7628ef98915989b7f46cf5a8722aa04bf1.

The second is a change to Skia to make it delay load Angle.  I need to clean up the code and will then prepare that next.

**Comment by weitzhandler** [comment]
WOW, this is great news.
The only reason I stand aside from Flutter is its lack of Windows support. I hope WASM support is also on the radar.

**Comment by stuartmorgan** [comment]
Moved to https://github.com/flutter/flutter/issues/30726
