### ISSUE TITLE
[windows] Add plugin support

### ISSUE THREAD

**Issue by stuartmorgan** [google/flutter-desktop-embedding#103]
The current implementation has no plugin support. I expect that we'll be able to share most or all of the Linux code for the plugin infrastructure (although if Windows provides a built-in JSON parser, we'll presumably want to use that instead of jsoncpp).

If we can't use the same code, then the Windows version should *not* follow the macOS/Linux example, since I plan to rewrite both per #102. Instead it should be written directly to the end-state of the macOS/Linux refactoring (which would mean something very much like the Flutter Android implementation).

**Comment by stuartmorgan** [comment]
@clarkezone I know you've expressed interest in tackling this after the core implementation is complete.

**Comment by clarkezone** [comment]
yes i can look at those.  Whats the ETA on the refactoring of the linux / mac versions

**Comment by stuartmorgan** [comment]
The second phase (adding MethodCodec) I'm working on now and will probably finish on Monday. I'm not sure when I'll get to the third and final phase (adding MethodChannel, and potentially eliminating the plugin class entirely).

**Comment by clarkezone** [comment]
OK.  I can probably get to text input over the weekend

**Comment by clarkezone** [comment]
Windows has a Windows.Data.Json API that should do the trick.  But i’ll wait for your part to come in.

**Comment by clarkezone** [comment]
Got a chance to look at this today and notice that text input depends on the plugin infra which I didn't previously realize.  For that reason I think i'll await your refactor for that as well as the more general plugin support.  Also, for text input I think it would be better to use the binary format rather than json for perf reasons, do you agree?

**Comment by stuartmorgan** [comment]
> Also, for text input I think it would be better to use the binary format rather than json

You have to use JSON; both sides have to match:
https://github.com/flutter/flutter/blob/fa6f9a03416ecf5e0e1813861538116b813dce66/packages/flutter/lib/src/services/system_channels.dart#L146

That's why JSON, not Standard, is the one codec currently implemented for desktop so far

**Comment by listepo-alterpost** [comment]
@stuartmorgan @clarkezone any news?

**Comment by stuartmorgan** [comment]
There's no concrete ETA on the remaining refactor step I referred to above. However, my hope is that the Windows implementation of the plugin infrastructure can share a lot of code with the Linux version (with just the JSON-specific implementations being different), so implementing it before the last of the refactor shouldn't be an issue.

The blocker at this point is someone having time to implement it.

**Comment by clarkezone** [comment]
FWIW I’ve been making some progress on this now actively debugging a windows implementation

**Comment by stuartmorgan** [comment]
Happy New Year for Windows, thanks to James :)

**Comment by brettclutch** [comment]
Happy new years everyone! Thx for all your hard work and awesome news on Windows!

**Comment by Tokenyet** [comment]
Is text input supported? I cannot key anything or copy-paste to TextField, or If there is a plugin supported this feature?

OS: Win 1903 18362.239

**Comment by stuartmorgan** [comment]
Copy/paste support is https://github.com/flutter/flutter/issues/30708, and non-ASCII input is https://github.com/flutter/flutter/issues/30661. Both are unrelated to this issue.
