### ISSUE TITLE
[windows] Add text input support

### ISSUE THREAD

**Issue by stuartmorgan** [google/flutter-desktop-embedding#104]
As on the other platforms, the initial implementation should handle basic text input, not try to do a complete implementation that supports IME and such (which is a longer-term project for all platforms).

Blocked on #103 since text input is currently done via an internal plugin (unless #47 is addressed before this)

**Comment by jcteng** [comment]
Linux code also works for windows . Try my branch 
https://github.com/jcteng/flutter-desktop-embedding
The plugin only support raw keyevent, IME feature not included.
