### ISSUE TITLE
WASM support

### ISSUE THREAD

**Issue by weitzhandler** [google/flutter-desktop-embedding#112]
Please have flutter work in the web-browser too, via Web Assebbly (WASM/WebAsm).

**Comment by Gaubee** [comment]
There will be a lot of work, because the browser is more like a security sandbox than an operating system platform.

**Comment by darmie** [comment]
To do this. Converting the Flutter desktop target to WASM is going to be an overkill, instead we can create a WebGL/JavaScript backend for the Flutter UI renderer... And then we compile our Dart code to WASM target that utilizes this backend.

**Comment by charafau** [comment]
I think that might help you https://github.com/Zubnix/skia-wasm-port ;)

**Comment by gedw99** [comment]
Raised there as an issue.

https://github.com/Zubnix/skia-wasm-port/issues/5

Google team seem to be open to helping:

https://github.com/Zubnix/skia-wasm-port/issues/1

**Comment by gedw99** [comment]
Hey @darmie

But there is no compiler to compile dart to wasm is there ?

**Comment by darmie** [comment]
@gedw99 non that I know of. It was only a suggestion.

**Comment by gedw99** [comment]
Ok thanks.
I presumed Google would eventually do it.

But flutter for web does not actually need it.
Skia wasm only does.

That's my opinion at least.

**Comment by stuartmorgan** [comment]
Web is out of scope for this project; we're focused specifically on native desktop embedding. If people are interested in trying to build an embedder using Wasm, you could always spin up a new project for it.

**Comment by Chaz6** [comment]
Google have announced Hummingbird which brings Flutter to the web. When the code is ready for public consumption, there should be a new github project page to request this. https://medium.com/flutter-io/hummingbird-building-flutter-for-the-web-e687c2a023a8

**Comment by utkutkutku** [comment]
What does it mean by flutter web. Will be like jupyter notebook?

**Comment by weitzhandler** [comment]
It's using html canvas, not WASM.
Are we ever gonna see flutter rendering using WASM?

**Comment by stuartmorgan** [comment]
If you have questions about Flutter for Web, or trying your own WASM-based custom embedder, please ask in a more general Flutter forum (see https://flutter.dev/community). The flutter-desktop-embedding project has no relationship with web, as a I said above.
