### ISSUE TITLE
[windows]: update_flutter_engine.bat is failing on latest flutter master channel

### ISSUE THREAD

**Issue by clarkezone** [google/flutter-desktop-embedding#115]
I'm on flutter master branch and have upgraded flutter to the latest version.  When update_flutter_engine.bat is run either directly from cmd or as part of the windows desktop embedder library build, there are a bunch of errors eg:

file:///C:/Users/james/Source/github.com/clarkezone/flutter-desktop-embedding/third_party/dart_packages/crypto/lib/src/hash_sink.dart(20,9): error G7D2AEF3C: Type 'Endianness' not found.
1>  final Endianness _endian;

**Comment by jason-simmons** [comment]
The version of the crypto package in https://github.com/google/flutter-desktop-embedding/tree/master/third_party/dart_packages/crypto needs to be updated to a newer release that uses the new Dart 2 Endian API.

@stuartmorgan 

For now, you might be able to work around this by editing the `tools/dart_tools/.packages` file locally to point the `crypto` package at the latest version of https://github.com/dart-lang/crypto

**Comment by stuartmorgan** [comment]
Thanks all for the investigation and fix!

**Comment by clarkezone** [comment]
+1 all good now thx to all

Sent from my iPad

On Aug 4, 2018, at 12:24 PM, stuartmorgan <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #115<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgoogle%2Fflutter-desktop-embedding%2Fissues%2F115&data=02%7C01%7C%7C75d8a875a1b44c78c30008d5fa3fec12%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636690074801954903&sdata=wihEAeibbOmfUvkr0mlrzw%2FvSTkls6IKgam%2Bk38Bi6s%3D&reserved=0>.
