### ISSUE TITLE
MissingPluginException : the plugin works but an exception is throwed

### ISSUE THREAD

**Issue by rxlabz** [google/flutter-desktop-embedding#13]
Hi, 
first : thanks for sharing this project ! it's really exciting :)
I started to play and tried to use plugins, but even if the call works, I get a MissingPluginException.

```dart
Future _colorPick() async {
  final channel = new MethodChannel('flutter/colorpanel', const JSONMethodCodec());
  final res = await channel.invokeMethod('ColorPanel.Show');
}
```

For instance when I use this method to open the colorPicker, the picker is opened, but I see an exception log.

```
[ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
MissingPluginException(No implementation found for method ColorPanel.Show on channel flutter/colorpanel)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:153)
<asynchronous suspension>
#1      _MyHomePageState._colorPick (file:///Users/rxlabz/dev/labz/flutter/desktop/flutter_desktop2/example_flutter/lib/main.dart:81)
<asynchronous suspension>
```

Did I missed something ?

**Comment by rxlabz** [comment]
the exception seems to be caused by the return of `nil` from the plugins methods... 🤔

**Comment by stuartmorgan** [comment]
Issue #9 covers adding an example plugin, including the Dart side, to the example, to avoid people having to try to figure out the Dart side.

In this case, I think it's a plugin bug. The existing Dart code for interacting with this is using OptionalMethodChannel which means this never came up.

**Comment by stuartmorgan** [comment]
Update on this: doing a quick fix for this is pretty easy, but in looking into it I filed issue #45 which ideally I'll do first.

It is definitely a plugin bug, which the current API makes much more likely than it should be.

**Comment by stuartmorgan** [comment]
The plugins now return correct response objects, using the new API.
