### ISSUE TITLE
Build  FetchFlutterEngine of project FlutterEmbedderMac failed in Xcode 10

### ISSUE THREAD

**Issue by chenyuantao** [google/flutter-desktop-embedding#131]
Build target FetchFlutterEngine of project FlutterEmbedderMac with configuration Debug

Unhandled exception:
SocketException: OS Error: Operation timed out, errno = 60, address = storage.googleapis.com, port = 57595
#0      downloadEngine (file:///Users/Tao/development/flutter-desktop-embedding/tools/dart_tools/bin/update_flutter_engine.dart:186:7)
<asynchronous suspension>
#1      main (file:///Users/Tao/development/flutter-desktop-embedding/tools/dart_tools/bin/update_flutter_engine.dart:101:13)
<asynchronous suspension>
#2      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#3      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by chenyuantao** [comment]
Is this because I am in China?

**Comment by chenyuantao** [comment]
I fixed it with using terminal and running `xcodebuild -target 'Example Embedder'`.
Because I can access storage.googleapis.com in my ss proxy terminal instead of Xcode.
Thanks to GFW.

**Comment by stuartmorgan** [comment]
The download step only runs when your Flutter checkout is updated, so going forward you should be able to build from within Xcode, and only switch to xcodebuild when you update Flutter.
