### ISSUE TITLE
Building for Centos 7 - abi:cxx11

### ISSUE THREAD

**Issue by 11xdev** [google/flutter-desktop-embedding#142]
Hi All,

I'm attempting to build the example application on centos. I've worked my way through installing the relevant dependencies; however I'm hitting some issues at the build stage.

I've added -D_GLIBCXX_USE_CXX11_ABI=0 to the CXXFLAGS in the Makefile as suggested in a few places online but no luck!

I've installed JSON cpp via:-

`RUN rpm -i http://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/j/jsoncpp-0.10.5-2.el7.x86_64.rpm
RUN rpm -i http://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/j/jsoncpp-devel-0.10.5-2.el7.x86_64.rpm`

I'm using GCC 7.3.0 (built from source) the error is below

`g++ -std=c++14 -Wall -Werror -D_GLIBCXX_USE_CXX11_ABI=0 -I/usr/include/jsoncpp   -I/root/flutter-desktop-embedding/example/linux/../../library/linux/include -I/root/flutter-desktop-embedding/example/linux/../../plugins/color_panel/linux/include -I/root/flutter-desktop-embedding/example/linux/../../plugins/file_chooser/linux/include -I/root/flutter-desktop-embedding/example/linux/../../plugins/menubar/linux/include flutter_embedder_example.cc -L/root/flutter-desktop-embedding/example/linux/out/lib -lglfw -ljsoncpp   -lflutter_embedder -lflutter_engine -lflutter_embedder_color_panel -lflutter_embedder_file_chooser -lflutter_embedder_menubar -Wl,-rpath=\$ORIGIN/lib -o /root/flutter-desktop-embedding/example/linux/out/flutter_embedder_example
/tmp/ccelbj1X.o: In function `main':
**flutter_embedder_example.cc:(.text+0x331): undefined reference to `flutter_desktop_embedding::CreateFlutterWindowInSnapshotMode(unsigned long, unsigned long, std::string const&, std::string const&, std::vector<std::string, std::allocator<std::string> > const&)'
/root/flutter-desktop-embedding/example/linux/out/lib/libflutter_embedder.so: undefined reference to `Json::writeString[abi:cxx11](Json::StreamWriter::Factory const&, Json::Value const&)'
/root/flutter-desktop-embedding/example/linux/out/lib/libflutter_embedder.so: undefined reference to `Json::Value::asString[abi:cxx11]() const'
/root/flutter-desktop-embedding/example/linux/out/lib/libflutter_embedder.so: undefined reference to `Json::Value::Value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'**
collect2: error: ld returned 1 exit status
make: *** [/root/flutter-desktop-embedding/example/linux/out/flutter_embedder_example] Error 1
make: Leaving directory `/root/flutter-desktop-embedding/example/linux'
The command '/bin/sh -c make -C ~/flutter-desktop-embedding/example/linux' returned a non-zero code: 2`

**Comment by stuartmorgan** [comment]
> I've added -D_GLIBCXX_USE_CXX11_ABI=0 to the CXXFLAGS in the Makefile

Did you add it to all of them? The example, the embedder library, and each plugin all have separate Makefiles.

**Comment by 11xdev** [comment]
I'd tried that without any luck. I took a different approach and used one of the pre-built Centos & docker images with devtoolset-7 included and it worked. Something must have gone wrong with the environment I was using previously.
