### ISSUE TITLE
engine_ is null when trying to InvokeMethod

### ISSUE THREAD

**Issue by pauldemarco** [google/flutter-desktop-embedding#146]
https://github.com/google/flutter-desktop-embedding/blob/58d0e92c1b5f2e86a32d33861affe255174b8f17/library/linux/src/plugin.cc#L26

I'm seeing this when creating a plugin much like the ColorPlugin, with callbacks from a g_signal_connect.

It works when InvokeMethod is called from the plugin's main method handler, but not from the g_signal_connect callback function.

Any ideas?

**Comment by krisgiesing** [comment]
That seems like a lifecycle question. The embedder hasn't had a chance to initialize the plugin with the configured engine's pointer yet. Is the g_signal_connect callback happening too early in the startup sequence?

**Comment by krisgiesing** [comment]
Or, possibly, the plugin hasn't been properly registered and so the embedder isn't initializing the engine at all?

**Comment by pauldemarco** [comment]
This was an implementation error on my part. Thanks.
