### ISSUE TITLE
Resource Contexts Must be Provided For Async Texture Uploads.

### ISSUE THREAD

**Issue by chinmaygarde** [google/flutter-desktop-embedding#17]
In an upcoming engine change, the engine will log a warning if an embedder does not provide a resource context. Resource contexts are used for asynchronous texture uploads in Flutter and are highly recommended as they eliminate jank when attempting to decode and upload large images for rendering. The callback can be [provided here](https://github.com/flutter/engine/blob/bdd3a0b34996d1d9f0fafdbc2427ed1796e57230/shell/platform/embedder/embedder.h#L44) and is similar to the `make_current` callback. The callback will be made on an internal thread separate from the GPU thread and the context used must be in the same sharegroup as the main context.

This is optional and the warning will only show up in un-optimized builds. But it is highly recommended.

**Comment by chinmaygarde** [comment]
Happy to implement this on Mac. So if there are no takers for this issue, feel free to assign to me.

**Comment by krisgiesing** [comment]
For the `make_current` callback we just forward to the `makeCurrentContext` method of the NSOpenGLView that hosts the rendering. Where is this new callback expected to go? The same method? A method on a different NSOpenGLView? Somewhere else?

**Comment by chinmaygarde** [comment]
You need to create a separate `NSOpenGLContext`. In the [`init`](https://developer.apple.com/documentation/appkit/nsopenglcontext/1436178-init) call, making sure the `share:` parameter is the same context obtained from the context of the `NSOpenGLView` should do the trick. Then, in the resource `make_current` callback, call `makeCurrentContext` on the second context you just created.

**Comment by stuartmorgan** [comment]
This was still on my radar from when we talked about this, I just haven't gotten to it yet. I can fix it shortly.
