### ISSUE TITLE
[macos] Rendering issue or crash on resize

### ISSUE THREAD

**Issue by jimmycoyne** [google/flutter-desktop-embedding#171]
If you quickly resize the sample app, it exhibits a graphical glitch by rendering a red frame. 
 
<img width="353" alt="screen shot 2018-12-11 at 06 35 58" src="https://user-images.githubusercontent.com/130512/49782677-198fee80-fd0f-11e8-8804-b83ca5731f31.png">

I took a screen recording but github does not support the file type.

commit 06989e11a492642cfdcdb12ccc0a5be1b14d8248 (HEAD -> master, origin/master, origin/HEAD)

Tested on 10.13 only.
Xcode 10

**Comment by stuartmorgan** [comment]
Yes, this is a known issue. It's closely related to https://github.com/flutter/flutter/issues/19225

**Comment by stuartmorgan** [comment]
Closing since this is tracked by https://github.com/flutter/flutter/issues/30671
