### ISSUE TITLE
Support 32bit Windows

### ISSUE THREAD

**Issue by loongliu** [google/flutter-desktop-embedding#175]
Accounting [this](https://github.com/flutter/flutter/issues/14925), Flutter only has 64bit SDK.

Is there any solution to build Application can run at 32bit windows, since considerable amount user are using 32bit windows.

**Comment by stuartmorgan** [comment]
This project assumes the presence of a Flutter SDK for the relevant platform, which according to the issue you linked isn't available for 32-bit Windows.

If you or someone else gets that working and there's still other work at the level of the code in this project that's necessary for supporting 32-bit then we can certainly consider that, but I'm not aware of anything that currently requires 64-bit in our Windows embedding code.

We can leave this open as a placeholder, but at this point it's not clear to me that there's any work in this project to track.

**Comment by stuartmorgan** [comment]
With the Windows shell now living in the engine repository, this is now covered by the existing bug linked above, since a 32-bit engine build would automatically include the shell as well. Given that, closing.
