### ISSUE TITLE
Duplication dart class in Mac OS product app

### ISSUE THREAD

**Issue by mutexliu** [google/flutter-desktop-embedding#176]
setup the engine development environment according [this](https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment)

I changed some code both `embedder.c` and `flutter/lib/ui/*.dart` in flutter engine, add some instance variable to dart class.

build and copy the `FlutterEmbedder.framework` to desired location: `flutter_engine_framework/macos/FlutterEmbedder.framework` (in the original build pipeline, `FlutterEmbedder.framework` is downloaded from network)

Then change some code in flutter/flutter, this code depends on the dart code change in engine.

Build the macos example project with Debug configuration. Run the result `Example Embedder.app`.

I found both my dart code changes in engine and flutter/flutter works (two logs both printed). But the code in flutter/flutter does not find the instance variable previously added to `flutter/lib/ui/*.dart`.
And Application crashed.

After some debug, I found `flutter/lib/ui/*.dart` class is duplicated in product app.

There are two files in app folder (Right click `Example Embedder.app` and click `Show Package Contents`): 
1. Contents/Resources/flutter_assets/vm_snapshot_data
2. Contents/Frameworks/FlutterEmbedderMac.framework/Versions/A/Frameworks/FlutterEmbedder.framework/Versions/Current/FlutterEmbedder.

file 1: app build result by `flutter build bundle`
file 2: engine build result by `ninja -C` 

Check the file contents by Mac command line `strings /path/to/file1or2 > output1or2.txt`

Search for `flutter/lib/ui/` in these generated output.txt, you can find `flutter/lib/ui/*.dart` class in both files.

Is anything wrong with my build settings?

**Comment by stuartmorgan** [comment]
Did you follow the instructions [here](https://github.com/google/flutter-desktop-embedding/blob/master/tools/build_flutter_assets#L26)?

(Issue #160 is about making what you are trying to do easier to set up.)

**Comment by mutexliu** [comment]
Thanks for the reply. 
Struggle with the problem for about ten hours, does not find the reason.

 I have done following changes:

![image](https://user-images.githubusercontent.com/15890184/50163722-0935d000-031c-11e9-95bf-8c7d93aace71.png)
![image](https://user-images.githubusercontent.com/15890184/50163860-4d28d500-031c-11e9-8f8d-0d328bb159fc.png)
![image](https://user-images.githubusercontent.com/15890184/50163901-60d43b80-031c-11e9-82a2-d0c1d306c963.png)

**Comment by stuartmorgan** [comment]
I'm a little confused as to why you've inlined `build_flutter_assets` into Xcode rather than modifying the script in place, but I'm not seeing any obvious issues with what you've posted. Other than deleting `.../flutter_engine_framework/macos/FlutterEmbedder.framework` and `.../flutter_app/build` just to make sure nothing is stale, I don't have any immediate suggestions. And maybe delete `flutter/bin/cache` as I think I saw a case where the previously-downloaded cache of sky_engine was being used instead of the new engine version (but I can't find where I encountered that, so may be misremembering).

If you provide the hashes for your Flutter tree and Flutter engine tree I can test a local engine override with the same versions to see if I can reproduce your issue with that version.

**Comment by stuartmorgan** [comment]
The script in the first screenshot is (a slightly modified version of) the script I linked to above that passes that flag, showing the relevant lines uncommented.

**Comment by krisgiesing** [comment]
You're right, apologies for missing that.

**Comment by mutexliu** [comment]
> I'm a little confused as to why you've inlined `build_flutter_assets` into Xcode rather than modifying the script in place.
> If you provide the hashes for your Flutter tree and Flutter engine tree I can test a local engine override with the same versions to see if I can reproduce your issue with that version.

Inline script is easier to modify in Xcode environment, since I don't need Linux built product.

flutter commit SHA-1 : `0f10d3f992410a712af77a1d82ebe32aeeb4ef1c`
engine commit SHA-1: `0e9ad4341695b8825ba90c60ce980f363ceb6c53`

**Comment by mutexliu** [comment]
After remove `flutter/bin/cache`, compile error fixed and app works fine.

So no block for my work. Close this issue for this moment.

When more time is available, I will do more check about whether dart class is duplicated.
