### ISSUE TITLE
Copy/paste isn't supported

### ISSUE THREAD

**Issue by icode** [google/flutter-desktop-embedding#180]
Ubuntu 18.04 `ctrl c` `ctrl v` etc not support，and keyboard menu key not support

paste button not support
![2018-12-26 12-10-56](https://user-images.githubusercontent.com/972959/50431651-64148c00-0907-11e9-9df3-bacfd21573a3.png)

**Comment by the4thfloor** [comment]
same on macOS

**Comment by kerocate** [comment]
same on windows

**Comment by stuartmorgan** [comment]
Moved to https://github.com/flutter/flutter/issues/30708 and https://github.com/flutter/flutter/issues/30709

(The larger issue of more general clipboard access is covered by https://github.com/flutter/flutter/issues/23603)
