### ISSUE TITLE
How to draw text with ParagraphBuilder?

### ISSUE THREAD

**Issue by ykmnkmi** [google/flutter-desktop-embedding#186]
Flutter desktop example app, code work in android.
[Flutter raw layers text example](https://github.com/flutter/flutter/blob/master/examples/layers/raw/text.dart)
![example](https://user-images.githubusercontent.com/18323977/50510695-e1313400-0ab4-11e9-8e18-38f5bb0d88a6.png)

**Comment by stuartmorgan** [comment]
What is the issue you are reporting? You've shown a screenshot of some code, but you haven't described a problem.

**Comment by stuartmorgan** [comment]
Closing due to lack of response. If you can provide information about the issue you are seeing, I can re-open.
