### ISSUE TITLE
[linux] Force re-render when window is moved

### ISSUE THREAD

**Issue by GeertJohan** [google/flutter-desktop-embedding#188]
On a multi-workspace desktop environment, in my case xmonad, the window can be moved out of view by switching workspace. When the window is moved back into view, it doesn't re-render to de GPU which means that either what was previous on screen is displayed, or some random graphics that - I assume - were left in GPU memory. Either way, a redraw is required to display whatever is going on in the flutter application. This redraw is fairly quick when there is something happening in the flutter application (state updated from external source, blinking cursor in text input, etc.). But when the application doesn't change, it takes a window resize to "snap it back to life". 

The same thing happens when the window is partially moved out of the display. See the screenshot below of the things that happen when view was moved outside of the monitor and then dragged back onto the monitor.. Flutter doesn't re-render so some strange stuff is left in the window until a resize is done or flutter re-renders because of click or state change.

![selection_004](https://user-images.githubusercontent.com/564501/50518766-b1cff680-0ab7-11e9-9305-bd63cf57fd98.png)

I suggest we force Flutter to re-render whenever the window is moved.

**Comment by stuartmorgan** [comment]
This seems to be the same issue as #111; closing as a duplicate.

**Comment by GeertJohan** [comment]
Whoops, my mistake.
