### ISSUE TITLE
[linux] Link fail flutter_embedder_example (undefined reference to...)

### ISSUE THREAD

**Issue by jonboj** [google/flutter-desktop-embedding#19]
Building on Ubuntu 17.10.
 g++ version :  gcc version 7.2.0 (Ubuntu 7.2.0-8ubuntu3.2)

Build with https://github.com/google/flutter-desktop-embedding/blob/master/linux/example/Makefile fails due to order of link libs ` -lGL -lglfw -lflutter_embedder`. Moving them to end of build command gives a successful build of bin `flutter_embedder_example`

**Comment by stuartmorgan** [comment]
@awdavies

**Comment by code-mc** [comment]
I made a PR that implements the proposed fix but I can't be bothered dealing with the CLA so if someone else wants to get in an easy contribution feel free to do so.

**Comment by awdavies** [comment]
For future reference, which version of g++ are you using?

**Comment by jonboj** [comment]
Updated issue with g++ version.

**Comment by awdavies** [comment]
Thanks!  I didn't have this issue originally on my machine, so if you can, could you make sure the pull request linked above works for you?

**Comment by jonboj** [comment]
Great, have tested on the pull request #26, in this the link works. So fine.
