### ISSUE TITLE
[Question] How to use database in `flutter-desktop-embedding`?

### ISSUE THREAD

**Issue by hyochan** [google/flutter-desktop-embedding#190]
I'd like to use `flutter-desktop embedding` for my diary app, and I have a question on how to save my `data` in `database`. Are there any supports in `flutter-desktop-embedding`?

**Comment by stuartmorgan** [comment]
In the future, please use the mailing list for questions, as noted in the README.

The answer to how you would use a database depends on what database you want to use, but at high level you have two options: use a database written entirely in Dart, or use an existing desktop database library and bridge to it by [writing a plugin](https://github.com/google/flutter-desktop-embedding/blob/master/plugins/README.md#writing-your-own-plugins).

**Comment by hyochan** [comment]
@stuartmorgan I might have to look for dart database. Sorry that I've missed the readme. I will do that in the future. Thanks.

**Comment by AppleEducate** [comment]
use moor! https://github.com/AppleEducate/moor_shared

**Comment by stuartmorgan** [comment]
@AppleEducate That link is to a project that is an application, not a database package, and which seems to be completely undocumented. It's not at all clear to me how it's related to this issue.

**Comment by Nipodemos** [comment]
one package that i think it will be interesting to you is [Hive](https://pub.dev/packages/hive), it is good to store key value pairs, as well as almost any object you project may have. And it is well documented and it works in web desktop and mobile.

**Comment by AppleEducate** [comment]
I was linking to an example, here is the package: https://github.com/simolus3/moor

**Comment by AppleEducate** [comment]
Hive works good for anything other that large lists and relational datasets
