### ISSUE TITLE
[Windows] Remove VS Configurations

### ISSUE THREAD

**Issue by CallumIddon** [google/flutter-desktop-embedding#192]
`jsoncpp` wasn't added to the static library builds in VS and now they are both broken.

As Linux only supports outputting shared libraries I think should be reciprocate this on Windows with only dynamic libraries as the extra configurations just complicate things.

**Comment by stuartmorgan** [comment]
Reducing the number of configurations sounds good to me, especially at this stage where there's still a significant amount of churn.

**Comment by CallumIddon** [comment]
Also, would it be a good idea to have debug or release not both as we will have to add 2 more configurations when we add the GN builds to the example. And this would simplify the `jsoncpp` build process until we need both configurations.
The Linux implementations looks like it only supports one mode (I don't know which one) so until we start releasing prebuilt binaries I think we should just stick with one configuration.

**Comment by stuartmorgan** [comment]
Reopening since the broken static library build options still need to be removed.

**Comment by stuartmorgan** [comment]
I'm not really tracking status live on the Kanban board; I'll generally be updating it once or twice a week. So things like this where the time between someone starting work and the patch landing is very short will jump straight to Done, which is fine.
