### ISSUE TITLE
Windows MethodChannel 

### ISSUE THREAD

**Issue by 1AlexFix1** [google/flutter-desktop-embedding#207]
Hi, I found information that in Linux and MacOS we can already use MethodChannel, which means that we can access the system (files, sound, etc.), But I cannot find the same information for the platform Windows, it would be great to apply immediately under 5 platforms

**Comment by stuartmorgan** [comment]
Windows plugin support landed recently (#103). (If you're still seeing docs we missed updating saying that Windows doesn't have plugin support, please provide links and I can update them.)
