### ISSUE TITLE
[Linux] Debug Text Missing

### ISSUE THREAD

**Issue by CallumIddon** [google/flutter-desktop-embedding#212]
The debug banner on Linux is missing the debug text that is present on Windows (and macOS?? @stuartmorgan). I'm assuming it is the same problem that #82 solved and a similar solution can be taken here.

**Comment by stuartmorgan** [comment]
It works for me; likely a difference in system-level fonts. Do you have any logging that indicates what font isn't loading?

**Comment by CallumIddon** [comment]
Completely silent, what distro are you using I'm on Ubuntu 18.04.1. I am installing a new virtual machine now to see if my main Linux VM is broken.

**Comment by stuartmorgan** [comment]
Debian, but it's not a perfectly clean install.

It's odd though; given (this)[https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/banner.dart#L23] and the lack of explicit font I would have expected it to be the bundled Roboto-Black. Perhaps something higher up in the hierarchy is changing the text style.

**Comment by CallumIddon** [comment]
What is `_kTextStyle.fontFamily` and `_kTextStyle.fontFamilyFallback` equal on your system? I get `null` for both which I am guessing is wrong.

**Comment by stuartmorgan** [comment]
They are `null` for me as well. I don't see any obvious place where the `MaterialApp`'s default theme (including font) is being passed through, so probably the banner is falling back onto default platform font resolution.

Long term the solution would be to have better platform-level font fallback for desktop platforms in Flutter. In the short term, it might be that fixing the banner as in 82 would require turning the default banner off, and then manually adding in a Banner with a style that includes a font. I don't think there's much value in doing that in the example though.

**Comment by RBogie** [comment]
When running the engine with verbose logging, you'll get the message that it can't find a font family for font ''. The easiest fix I could find was to add this to the pubspec.yaml for now ;)

```fonts:
  - family: ""
    fonts:
    - asset: fonts/Roboto/Roboto-Regular.ttf
      weight: 400```

**Comment by stuartmorgan** [comment]
Filed https://github.com/flutter/flutter/issues/30700 for the long-term fix.
