### ISSUE TITLE
Set up CI for Windows

### ISSUE THREAD

**Issue by stuartmorgan** [google/flutter-desktop-embedding#223]
There's now CI build coverage for Linux and macOS via Travis, but it doesn't support Windows. At some point Flutter was using Travis (Linux/macOS)+AppVeyor, and I believe I've seen that combination in other projects, so hopefully that would work.

From a quick glance at their docs it looks like they have preconfigured images with VS, which could make it pretty straightforward.

@CallumIddon

**Comment by clarkezone** [comment]
It might relate to this:

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(1399,5): warning MSB8012: TargetName(lib_json) does not match the Library's OutputFile property value (json_vc71_libmtd). This may cause your project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specified in %(Lib.OutputFile). [C:\projects\flutter-desktop-embedding\library\windows\third_party\jsoncpp\makefiles\msvc2017\lib_json.vcxproj] [C:\projects\flutter-desktop-embedding\library\windows\GLFW Library.vcxproj]

wondering if it could relate to the above warning?  Although I’m by no means an expert in cppbuild

Sent from my iPad

On Jan 10, 2019, at 5:26 PM, Callum Iddon <notifications@github.com<mailto:notifications@github.com>> wrote:


I have gotten started but I am running into a weird issue where the jsoncpp build won't output the library even when the build is successful. @clarkezone<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fclarkezone&data=02%7C01%7C%7C8a300d22f861422c5f6008d67763ca26%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636827667802782018&sdata=Q5RAuOTaRY1naAMX3jnXt%2FadERmfCBcQldCY0XxHi%2BQ%3D&reserved=0> do you know why this could be? The tree is here<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCallumIddon%2Fflutter-desktop-embedding%2Ftree%2Fappveyor&data=02%7C01%7C%7C8a300d22f861422c5f6008d67763ca26%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636827667802938269&sdata=0DCz8tijmr1jev%2FtCCX76kG9qBVVoAERCyGFOioGsXA%3D&reserved=0> and builds are here<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fci.appveyor.com%2Fproject%2FCallumIddon%2Fflutter-desktop-embedding&data=02%7C01%7C%7C8a300d22f861422c5f6008d67763ca26%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636827667802938269&sdata=VEk9PKB0jqq%2FM7m3mTC781a1HgItix7HsvJ0hVpnUMM%3D&reserved=0>.

**Comment by stuartmorgan** [comment]
Confirmed working—and it turned out to be very timely, because as soon as it was turned on it found the breakage that led to PR #233. Thanks for doing the research and legwork on this!
