### ISSUE TITLE
[MacOS] Contents shake when resize

### ISSUE THREAD

**Issue by loongliu** [google/flutter-desktop-embedding#226]
Resize the MacOS example application, the contents shake.
Resizing is a common operation on desktop application, and the shake action is not accepted for released product.
After speeding some time digging into the problem, I found the reason:
When resizing, NSOpenGLView calls `glViewport` with new size for serval times on the main thread, also Native code call `FlutterEngineSendWindowMetricsEvent` sending resize event to flutter embedder. flutter engine's platform task runner (which is the native main thread) receives the resize event and posted to the ui task runner (which is a native background thread). Ui task runner handled the event and flush OpenGL contents for new size.

So, the key point is `NSOpenGLView` calls `glViewport`, which make the contents scale for new size. After some delay for cross thread communication, the content refresh for new size (return to the normal size).  Take an image for example, the image size will firstly scale and return to normal size, then scale and return to normal size, behave as shaking.

**Comment by stuartmorgan** [comment]
Yes, there are several known issues with resize. There are discussions in progress about embedder API changes that would allow for better resize behavior.

**Comment by loongliu** [comment]
Glad to know about this discussions and look forward for the changes.

Any possible solutions to handle this problem?

**Comment by stuartmorgan** [comment]
The solution is for Flutter to do some kind of synchronous draw during resize; there are various options for how to go about that.

Most likely, at least for the medium term, it will re-blit at the old size with white fill as necessary, to avoid a sync re-layout. That would make resize feel similar to Chromium's.

**Comment by stuartmorgan** [comment]
Moved to https://github.com/flutter/flutter/issues/30671
