### ISSUE TITLE
Invalid bundle identifier io.flutter.flutter_embedder

### ISSUE THREAD

**Issue by jbg** [google/flutter-desktop-embedding#234]
I've ported an existing Flutter app over to MacOS using flutter-desktop-embedding, and when doing a test upload to the Mac App Store to verify the release process for when things eventually get stable enough to do a release, the upload is rejected due to the underscore in the bundle identifier of `FlutterEmbedder.framework`.

Removing the underscore from the bundle identifier in the `Info.plist` of `FlutterEmbedder.framework` and in `FLEViewController.m` allows a successful upload.

**Comment by stuartmorgan** [comment]
Good thought; always helpful to find things like that well in advance.

Per the Note section [here](https://github.com/google/flutter-desktop-embedding/tree/master/library#using-the-framework), that framework comes from Flutter itself, not flutter-desktop-embedding, so you'll want to file this in [Flutter's issue tracker](https://github.com/flutter/flutter/issues). I'll leave this open though, and you can link to that bug from here, so this stays on our radar.

**Comment by jbg** [comment]
Reported. When https://github.com/flutter/engine/pull/7503 gets merged (or whenever a version containing that change starts getting used by this project, not sure exactly how that works) I suppose this line will need to change in `FLEViewController.m`:

```objc
static NSString *const kICUBundleID = @"io.flutter.flutter_embedder"
```

**Comment by jbg** [comment]
I did see that, but I found it a bit confusing, because the `update_flutter_engine` script under `tools/` (which is run by a build target in the embedder framework Xcode project) seems to download some kind of snapshot of the Flutter engine from storage.googleapis.com, suggesting that the version used is fixed, whereas the text you linked to seems to suggest that I'm in control of which version of Flutter is used.

**Comment by jbg** [comment]
Ah, sorry, disregard that! I dug into it a bit more and think I understand how it works now (downloads a snapshot based on the version of your local Flutter tree).

**Comment by stuartmorgan** [comment]
> downloads a snapshot based on the version of your local Flutter tree

Exactly; that specific macOS artifact isn't part of the Flutter tree, but needs to match the engine version expected by Flutter.
