### ISSUE TITLE
macOS example no longer runs correctly

### ISSUE THREAD

**Issue by shrike69** [google/flutter-desktop-embedding#245]
I downloaded the FDE this morning and tried running the example. After building in Xcode and running the window appears but it has a gray background. There's a message in the console about Search tree file's format version number (0) is not supported from MessageTracker, but I don't know that it's related (though I can't recall seeing that message before today). This was with f26ec2e. 3c276ec landed shortly after but had the same problem. macOS 10.13.6, Xcode 9.2.

**Comment by stuartmorgan** [comment]
This is very likely the macOS version of #240. What's your Flutter tree hash? If you sync again (to pick up the error logging change I landed very recently) do you see logging about `error 2` from running the Flutter engine?

**Comment by inevity** [comment]
what location is Flutter tree hash?

**Comment by stuartmorgan** [comment]
It's the git hash of HEAD in your Flutter checkout. You can run any git command that lets you look at recent commits (`git rev-parse HEAD` will provide just the hash) in your Flutter tree, or run `flutter doctor -v` and look for the "Framework revision".

**Comment by inevity** [comment]
ok
    • Framework revision c20db6689c (11 days ago), 2019-01-16 03:43:48 -0500
    • Engine revision 09e149e897
    • Flutter-desktop-embedding Latest commit 5881f2

ok 
    • Flutter version 1.1.10-pre.196 
    • Framework revision 45b0942437 (9 hours ago), 2019-01-26 15:32:39 -0500
    • Engine revision 9b6d5031a3
    • Dart version 2.1.1 (build 2.1.1-dev.3.2 a5030ed92f)
    • Flutter-desktop-embedding Latest commit 5881f2


Now only these errors, but looks like those are not relate flutter. Have sign and sanbox the example,so no other error.
```
2019-01-27 13:38:06.261777+0800 Example Embedder[13482:2667465] [default] Unable to load Info.plist exceptions (eGPUOverrides)
2019-01-27 13:38:06.449980+0800 Example Embedder[13482:2667520] MessageTracer: load_domain_whitelist_search_tree:73: Search tree file's format version number (0) is not supported
2019-01-27 13:38:06.452821+0800 Example Embedder[13482:2667520] MessageTracer: Falling back to default whitelist
```

**Comment by stuartmorgan** [comment]
@inevity I'm confused by your last comment. Are you saying you have this bug (blank grey window on macOS) with the hashes you've listed?

**Comment by inevity** [comment]
No this bug.  All ok.

**Comment by stuartmorgan** [comment]
Were you experiencing the bug previously? I'm not clear on why you're posting version information and log messages here if you aren't seeing this bug.

**Comment by inevity** [comment]
No, I just post some info to aid the troobleshooting.

**Comment by shrike69** [comment]
I updated flutter and the problem went away.

**Comment by stuartmorgan** [comment]
That matches my expectation that this was #240; closing.
