### ISSUE TITLE
Add file-picker plugin support to Linux

### ISSUE THREAD

**Issue by stuartmorgan** [google/flutter-desktop-embedding#25]
We have a macOS implementation of the native side of the file picker plugin; we need a Linux version as well. Implementation will depend on the toolkit we end up using for the base Linux embedder.

**Comment by mrmcq2u** [comment]
you can call the native file picker using dbus?

**Comment by awdavies** [comment]
I haven't found any indication that there exists such a thing.  The closest I've found is the DBus interface for `FileManager1`, which only gets us unidirectional communication.

**Comment by mrmcq2u** [comment]
its an xdg-desktop-portal, you get the kde file picker on kde, the gtk one gnome etc. There is also a printer portal which use the native backend based on the environment the user is running. You interact with the portals over dbus.

**Comment by stuartmorgan** [comment]
> its an xdg-desktop-portal

I assume you are referring to this: https://github.com/flatpak/xdg-desktop-portal ? Whose readme says that the documentation for the available interfaces is this 404 page:
https://flatpak.org/xdg-desktop-portal/portal-docs.html ?

If you have working example code that would provide the functionality needed to implement this plugin on Linux (ideally something which could be easily deployed without adding extra layers of dependencies), please provide pointers to it. We'd also be happy to have contributions to the Linux embedder via pull requests.
