### ISSUE TITLE
Add support for text navigation key combinations

### ISSUE THREAD

**Issue by franciscojma86** [google/flutter-desktop-embedding#276]
On macOS, typing cmd+right invokes moveToRightEndOfLine: These methods are already received by doCommandBySelector: so we we just need to implement the logic. 

On glfw we could use modifier flags https://www.glfw.org/docs/latest/group__mods.html#ga14994d3196c290aaa347248e51740274

**Comment by stuartmorgan** [comment]
Moved to https://github.com/flutter/flutter/issues/30725
