### ISSUE TITLE
ninja: fatal: CreateProcess: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by ruizhang81** [google/flutter-desktop-embedding#279]
virtul studio in win7 64 

build error:
1>Run the embedder library's GN build
1>Done. Made 14 targets from 12 files in 1549ms
1>ninja: Entering directory `D:\flutter-desktop-embedding\example\windows_fde\scripts\..\..\..\out'
1>ninja: fatal: CreateProcess: %1 is not a valid Win32 application.

**Comment by stuartmorgan** [comment]
Please run `ninja -v -C out` from the root of the repository and provide the command that is printed before that error.

**Comment by ruizhang81** [comment]
D:\flutter\flutter-desktop-embedding>ninja -v -C out
ninja: Entering directory `out'
ninja: fatal: CreateProcess: %1 is not a valid Win32 application.

i'm in Win7 64-bit system

**Comment by ruizhang81** [comment]
Visual Studio 2017

**Comment by stuartmorgan** [comment]
Hm, I was expecting verbose mode to print something before the error. It must be quite early then.

Since it's run as part of most of the build commands: does running `vcvars64.bat` directly work for you? I'm not sure it's actually getting that far--there may well be a step that's earlier than the toolchain failing--but it would be good to eliminate that as a possibility.

**Comment by ruizhang81** [comment]
i find vcvars64.bat in C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64
run it,i get nothing
~~~
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64>vcvars64
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64>
~~~

after add C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64  to  environment path
run ninja -C out flutter_embedder

~~~
D:\flutter\flutter-desktop-embedding>ninja -C out flutter_embedder
ninja: Entering directory `out'
ninja: fatal: CreateProcess: %1 is not a valid Win32 application.olchain:msvc)
~~~

what is ".olchain:msvc)"? @.@

**Comment by stuartmorgan** [comment]
> after add C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64 to environment path

vcvars64.bat should already have been in your path per the setup instructions:
https://github.com/google/flutter-desktop-embedding/blob/master/library/README.md#windows
That path doesn't look right; 14.0 is VS 2015, and amd64 isn't the right target. Please follow the linked instructions and make sure the right tools are in your path, then try building again.

> what is ".olchain:msvc)"?

The '.' is part of the error message; see your previous output above. "olchain:msvc" is the end of "toolchain:msvc", which is what the toolchain is named in GN. It looks like your terminal is stomping a previous output line.

**Comment by stuartmorgan** [comment]
If you still see issues, please update and then run the new:
```
tools\run_dart_tool doctor
```
to see if there are any obvious missing dependencies.

**Comment by ruizhang81** [comment]
thank you very much.
i use FlutterSDK<https://storage.googleapis.com/flutter_infra/releases/stable/windows/flutter_windows_v1.0.0-stable.zip> replace flutter source.
run the demo in windows  success.

**Comment by stuartmorgan** [comment]
Unless you switched to the 'master' channel after you downloaded that version, I don't see how that's possible; Flutter 1.0 is too old to be compatible with this project. But I'm glad you were able to build successfully.
