### ISSUE TITLE
GN build instructions should mention flutter_tree_path

### ISSUE THREAD

**Issue by lukef** [google/flutter-desktop-embedding#289]
In `build/flutter.gni` the flutter path is defined as:

```
flutter_tree_path = rebase_path("../../flutter")
```

On Linux, this will fail if you've configured a custom flutter installation location.

**Comment by stuartmorgan** [comment]
It's not hard coded, it's an argument that can be set with `gn_dart args`. This is intentional (per the comment above that line).

That's currently missing from the build documention though, which is a bug.

**Comment by lukef** [comment]
Thanks

**Comment by stuartmorgan** [comment]
Fixed in the README
