### ISSUE TITLE
How to build the macOS version

### ISSUE THREAD

**Issue by gedw99** [google/flutter-desktop-embedding#29]
Can someone put in a make file , like the Linux one has ?

**Comment by stuartmorgan** [comment]
There's an Xcode project; you open it and build (or use xcodebuild if you want to do it from the command line). A makefile that just invokes xcodebuild would be trivial, so I don't see much value in having it in the repo.

(Longer term, we may revisit the current approach of having platform-style build systems, and instead more closely parallel the `flutter build`/`flutter run` type commands. But that wouldn't be a makefile either.)
