### ISSUE TITLE
[menubar] Linux menu is in a detached window

### ISSUE THREAD

**Issue by lukef** [google/flutter-desktop-embedding#290]
When running via the Linux (beta) on Chrome OS (73 beta) the menu bar for the example engine will be detached. It is still functional.

Unclear if the issue is a Chrome OS one or a Flutter one.

I realize it is (probably) a low priority but figured I'd mention it.

![screenshot 2019-02-22 at 12 38 16 pm](https://user-images.githubusercontent.com/37941/53270419-87a64980-36a0-11e9-9fba-df7786040961.png)

**Comment by stuartmorgan** [comment]
This is true of the linux implementation in general, it's not specific to Chrome OS:
https://github.com/google/flutter-desktop-embedding/blob/master/plugins/menubar/linux/src/menubar_plugin.cc#L55

It's impossible to add an in-window native menu to a GLFW window, so this implementation is necessary until #23 is implemented.

**Comment by stuartmorgan** [comment]
Fixed by #762
