### ISSUE TITLE
Arabic language support

### ISSUE THREAD

**Issue by 0x4ym4n** [google/flutter-desktop-embedding#296]
Flutter 1.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8661d8aecd (2 weeks ago) • 2019-02-14 19:19:53 -0800
Engine • revision 3757390fa4
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

## Does the prebuilt and portable version works ?
 - Yes 
## Steps to Reproduce

1. Arabic language support - currently my Linux machine shows nothing for Arabic. 
Screenshot :
https://ibb.co/6nrDrZs
https://ibb.co/bLzvG4d (Modifying first row in Stock App with Arabic strings)
Mobile Screenshot :
https://ibb.co/tLjZMmd

**Comment by stuartmorgan** [comment]
Have you read https://github.com/google/flutter-desktop-embedding/blob/master/Flutter-Requirements.md#fonts? What font did you specify when you modified the applications you are running, and can that font display Arabic?

> ## Does the prebuilt and portable version works ?
> * Yes

I'm confused by what this means; what prebuilt version does this refer to? Where did this question come from?

**Comment by 0x4ym4n** [comment]
Yes I changed the roboto to Arabic font and it works perfectly
Thank you.
