### ISSUE TITLE
Idea / Question

### ISSUE THREAD

**Issue by kafein** [google/flutter-desktop-embedding#300]
Hi,

I want to create a visual layout builder for flutter. Do you think desktop-embedding project mature enough for this type application? What are the current limitations? 

Finally, what do you think about idea?

Thanks.

**Comment by stuartmorgan** [comment]
In the future please use the mailing list for general questions, [as requested in the README](https://github.com/google/flutter-desktop-embedding#feedback-and-discussion).

> Do you think desktop-embedding project mature enough for this type application?

I'm not sure I understand the question; the maturity of the project is largely orthogonal to the type of application you want to build. If you're asking if it has the specific functionality you want, I can't answer without knowing what specific functionality you want.

> What are the current limitations?

It's difficult to enumerate a complete set of limitations of a framework, especially one that's in relatively early stages of development. Again, without knowing what functionality you want, I don't know what limitations would be relevant to you.

If you just want a high-level understanding of the current state I would suggest reading the READMEs, skimming the titles of the open issues to see some of the known limitations that have been flagged, and trying out the example app. I'm happy to answer specific questions you may have beyond that on the mailing list.
