### ISSUE TITLE
Windows Build Failed

### ISSUE THREAD

**Issue by MrAlvaro** [google/flutter-desktop-embedding#301]
![image](https://user-images.githubusercontent.com/41203980/54010011-d8f81380-414b-11e9-9403-460d8d360b8d.png)
```
1>------ Build started: Project: GLFW Example, Configuration: Debug x64 ------
1>Run the embedder library's GN build
1>Done. Made 14 targets from 12 files in 10ms
1>ninja: Entering directory `W:\SDK\flutter-desktop-embedding\example\windows_fde\scripts\..\..\..\out'
1>[1/41] CXX obj/library/common/client_wrapper/src/client_wrapper.engine_method_result.obj
1>FAILED: obj/library/common/client_wrapper/src/client_wrapper.engine_method_result.obj
1>vcvars64.bat 1> nul && cl /nologo /showIncludes /MDd /FC -DUSE_FDE_TREE_PATHS -I../library/include -I.. -I../library/common/client_wrapper/include -I../third_party/jsoncpp/src/include /EHsc /W3 /Od  /c ../library/common/client_wrapper/src/engine_method_result.cc /Foobj/library/common/client_wrapper/src/client_wrapper.engine_method_result.obj /Fdobj/library/common/client_wrapper/client_wrapper_c.pdb
1>CreateProcess failed: The system cannot find the file specified.
1>ninja: fatal: ReadFile: The handle is invalid.
1>
1>
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(128,5): error MSB3073: The command "W:\SDK\flutter-desktop-embedding\example\windows_fde\scripts\run_gn_build
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(128,5): error MSB3073: :VCEnd" exited with code 1.
1>Done building project "GLFW Example.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by stuartmorgan** [comment]
Please provide the information [requested here](https://github.com/google/flutter-desktop-embedding#feedback-and-discussion).

**Comment by MrAlvaro** [comment]
_The error was due to the lack of Visual Studio CommandLine in path, thx_
### Doctor:
![image](https://user-images.githubusercontent.com/41203980/54043489-77679180-41ab-11e9-8fe1-17259edd94c7.png)
### New compilation issue:
![image](https://user-images.githubusercontent.com/41203980/54043731-13919880-41ac-11e9-8478-77471e63685f.png)

**Log:**
`1>ninja: Entering directory `W:\SDK\flutter-desktop-embedding\example\windows_fde\scripts\..\..\..\out'
1>[1/3] CXX obj/library/common/glfw/flutter_embedder.embedder.obj
1>FAILED: obj/library/common/glfw/flutter_embedder.embedder.obj
1>vcvars64.bat 1> nul && cl /nologo /showIncludes /MDd /FC -DFLUTTER_DESKTOP_EMBEDDING_IMPL -DUSE_FDE_TREE_PATHS -I.. -I../library/include -Igen/flutter_engine -I../library/common/client_wrapper/include -I../third_party/jsoncpp/src/include -Igen/glfw /EHsc /W3 /Od  /c ../library/common/glfw/embedder.cc /Foobj/library/common/glfw/flutter_embedder.embedder.obj /Fdobj/library/flutter_embedder_c.pdb
1>w:\sdk\flutter-desktop-embedding\library\common\glfw\embedder.cc(182): error C2838: 'kAdd': illegal qualified name in member declaration
1>w:\sdk\flutter-desktop-embedding\library\common\glfw\embedder.cc(182): error C2065: 'kAdd': undeclared identifier
1>w:\sdk\flutter-desktop-embedding\library\common\glfw\embedder.cc(183): error C2838: 'kAdd': illegal qualified name in member declaration
1>w:\sdk\flutter-desktop-embedding\library\common\glfw\embedder.cc(183): error C2065: 'kAdd': undeclared identifier
1>w:\sdk\flutter-desktop-embedding\library\common\glfw\embedder.cc(187): error C2838: 'kAdd': illegal qualified name in member declaration
1>w:\sdk\flutter-desktop-embedding\library\common\glfw\embedder.cc(187): error C2065: 'kAdd': undeclared identifier
1>w:\sdk\flutter-desktop-embedding\library\common\glfw\embedder.cc(202): error C2838: 'kAdd': illegal qualified name in member declaration
1>w:\sdk\flutter-desktop-embedding\library\common\glfw\embedder.cc(202): error C2065: 'kAdd': undeclared identifier
1>w:\sdk\flutter-desktop-embedding\library\common\glfw\embedder.cc(204): error C2838: 'kRemove': illegal qualified name in member declaration
1>w:\sdk\flutter-desktop-embedding\library\common\glfw\embedder.cc(204): error C2065: 'kRemove': undeclared identifier
1>w:\sdk\flutter-desktop-embedding\library\common\glfw\embedder.cc(214): error C2838: 'kAdd': illegal qualified name in member declaration
1>w:\sdk\flutter-desktop-embedding\library\common\glfw\embedder.cc(214): error C2065: 'kAdd': undeclared identifier
1>w:\sdk\flutter-desktop-embedding\library\common\glfw\embedder.cc(214): error C2838: 'kRemove': illegal qualified name in member declaration
1>w:\sdk\flutter-desktop-embedding\library\common\glfw\embedder.cc(214): error C2065: 'kRemove': undeclared identifier
1>w:\sdk\flutter-desktop-embedding\library\common\glfw\embedder.cc(223): error C2838: 'kHover': illegal qualified name in member declaration
1>w:\sdk\flutter-desktop-embedding\library\common\glfw\embedder.cc(223): error C2065: 'kHover': undeclared identifier
1>ninja: build stopped: subcommand failed.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(128,5): error MSB3073: The command "W:\SDK\flutter-desktop-embedding\example\windows_fde\scripts\run_gn_build
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(128,5): error MSB3073: :VCEnd" exited with code 1.
1>Done building project "GLFW Example.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
`

**Comment by stuartmorgan** [comment]
You need a newer version of Flutter; those constants were recently added to the embedding header. As the README says, this project generally expects you to be on a recent version of master.

(I forgot to advance the minimum version check when landing f8c81178, which is why there's not a specific error message about it being too old.)

**Comment by deekay42** [comment]
I'm getting the same error. I then pulled the latest flutter version from https://github.com/flutter/flutter.
Still the same error. Also same platform and flutter doctor output as @AlvaroVasconcelos 
After some searching it appears that these constants are defined in https://github.com/flutter/engine/blob/master/shell/platform/embedder/embedder.h, however that's not the repository I pulled from. Do I need to pull this repo as well?

**Comment by stuartmorgan** [comment]
> I'm getting the same error.

I assume you mean the second error? There are two completely unrelated errors in this issue.

> Do I need to pull this repo as well?

No; engine artifacts, including that header, are downloaded as part of the build.

Are you using master of the FDE repo? The min Flutter version has been rolled forward since my comment above, so you should have seen an error during the build step that fetches the engine.

**Comment by deekay42** [comment]
Yes, I meant the second error.
My versions must've gotten messed up; setting up from scratch by cloning both repos solved the problem for me though.
