### ISSUE TITLE
Please add "clang" to your README.MD

### ISSUE THREAD

**Issue by JhettHeliks** [google/flutter-desktop-embedding#307]
There seems to be a missing tool in your Tools heading in your README. It's is needed for gn tools.

Oh Its also just clang `sudo apt install clang` for linux.

**Comment by stuartmorgan** [comment]
There are prebuilt GN binaries looked from the GN page. If you choose to build GN from source instead then of course you'll need GN's build dependencies, but that doesn't make clang a requirement for this project.
