### ISSUE TITLE
Support unicode

### ISSUE THREAD

**Issue by hayhv** [google/flutter-desktop-embedding#309]
I think it should support typing unicode in TextInput controls

**Comment by stuartmorgan** [comment]
Yes, this is a known issue, but hadn't ever been actually logged. Currently we only really support ASCII input, and need a solution that allows for IME integration on each platform.

**Comment by hayhv** [comment]
I integrated support unicode on windows.

In the class TextInputModel
changed variables  std::string to std::wstring

  std::wstring text_;
  std::string input_type_;
  std::string input_action_;
  std::wstring::iterator selection_base_;
  std::wstring::iterator selection_extent_;


-  edit functions
void AddCharacter(unsigned int c);



bool TextInputModel::SetEditingState(size_t selection_base,
                                     size_t selection_extent,
                                     const std::string &text) {
  if (selection_base > selection_extent) {
    return false;
  }
  // Only checks extent since it is implicitly greater-than-or-equal-to base.
  if (selection_extent > text.size()) {
    return false;
  }
 
	wchar_t *wcText = nullptr; 
	size_t byte = 0;

#ifdef WINDOWS
	if(text.length() > 0)
	{
		byte = ::MultiByteToWideChar(CP_UTF8, 0, text.c_str(), text.length(), NULL, 0);
		wcText = new wchar_t[byte+sizeof(wchar_t)];
		::MultiByteToWideChar(CP_UTF8, 0, text.c_str(), text.length(), wcText, byte);
		wcText[byte] = L'\0';
 		text_ = std::wstring(wcText);
	}
	else
	{
		text_ = std::wstring(L"");
	}
#else
	byte = mbstowcs(NULL, text.c_str(), text.length());
	wcText = new wchar_t[byte+sizeof(wchar_t)];
	mbstowcs(wcText, text.c_str(), text.length());
	text_ = std::wstring(wcText);
#endif	
  //release wcText
  if(wcText) delete wcText;
  
  selection_base_ = text_.begin() + selection_base;
  selection_extent_ = text_.begin() + selection_extent;
  return true;
}



void TextInputModel::AddCharacter(unsigned int c) {
  if (selection_base_ != selection_extent_) {
    DeleteSelected();
  }
  selection_extent_ = text_.insert(selection_extent_, c);
  selection_extent_++;
  selection_base_ = selection_extent_;
}


Json::Value TextInputModel::GetState() const {
  // TODO(awdavies): Most of these are hard-coded for now.
  Json::Value editing_state;
  editing_state[kComposingBaseKey] = -1;
  editing_state[kComposingExtentKey] = -1;
  editing_state[kSelectionAffinityKey] = kAffinityDownstream;
  editing_state[kSelectionBaseKey] =
      static_cast<int>(selection_base_ - text_.begin());
  editing_state[kSelectionExtentKey] =
      static_cast<int>(selection_extent_ - text_.begin());
  editing_state[kSelectionIsDirectionalKey] = false;
  //editing_state[kTextKey] = text_;
  char *buf = nullptr;
  size_t byte = 0;
#ifdef WINDOWS 
  if (text_.length() > 0)
  {
    byte = ::WideCharToMultiByte(CP_UTF8, 0, text_.c_str(), text_.length(), NULL,0, 0, 0);
	buf = new char[byte+sizeof(char)];
	::WideCharToMultiByte(CP_UTF8, 0, text_.c_str(), text_.length(), buf, byte, 0, 0);						  
    buf[byte] = '\0';
    editing_state[kTextKey] = std::string(buf);
	
  } 
  else
  {
		editing_state[kTextKey] = std::string("");
  }
#else
	//
	  byte = wcsrtombs(NULL, text_.c_str(), text_.length());
	  buf = new char[byte + sizeof(char)];
	  wcsrtombs(buf, text_.c_str(), text_.length());
	  editing_state[kTextKey] = std::string(buf);
#endif	
	//release buf
	if (buf) delete buf;

  // TODO(stuartmorgan): Move client_id out up to the plugin so that this
  // function just returns the editing state.
  Json::Value args = Json::arrayValue;
  args.append(client_id_);
  args.append(editing_state);
  return args;
}

- In the class TextInputPlugin
void TextInputPlugin::CharHook(GLFWwindow *window, unsigned int code_point) {
  if (active_model_ == nullptr) {
    return;
  }
  // TODO(awdavies): Actually handle potential unicode characters. Probably
  // requires some ICU data or something.
  active_model_->AddCharacter(static_cast<unsigned int>(code_point));
  SendStateUpdate(*active_model_);
}

ex: https://github.com/hayhv/flutter-desktop-embedding

**Comment by stuartmorgan** [comment]
If you want to contribute code, you'll need to use a pull request; see CONTRIBUTING.md.

**Comment by stuartmorgan** [comment]
Moved to:
https://github.com/flutter/flutter/issues/30660
https://github.com/flutter/flutter/issues/30661
https://github.com/flutter/flutter/issues/30662
