### ISSUE TITLE
client_id away increase

### ISSUE THREAD

**Issue by hayhv** [google/flutter-desktop-embedding#310]
in the function 
void TextInputPlugin::HandleMethodCall

variable client_id away increase when click focus input textfield and other
and if client_id >  kInputModelLimit has error

**Comment by stuartmorgan** [comment]
This is already on our radar; we need to get a definitive answer on whether Flutter's current client ID behavior is something we can rely on, and then either eliminate the multiple-client tracking, or add wraparound, depending.

**Comment by stuartmorgan** [comment]
Per discussion about the documentation for this system channel, we should change the text plugin implementations to keep only one state, rather than a set of them.

**Comment by stuartmorgan** [comment]
Moved to https://github.com/flutter/flutter/issues/30659
