### ISSUE TITLE
PIP (Picture in Picture) Mode

### ISSUE THREAD

**Issue by meteorsnows** [google/flutter-desktop-embedding#319]
Request API from Flutter to have this mode?

I know Chromium have implement its own PIP feature, but I guess Windows 10 above can use following, it have size restriction but might be better support, however it only working from UWP project: 

Type 'Windows.UI.ViewManagement.ApplicationView' can only be used in UWP apps, not Desktop or Centennial (CompactOverlay)

**Comment by stuartmorgan** [comment]
This would require #101, and possibly #98 depending on the use case.

**Comment by stuartmorgan** [comment]
This is a sufficiently niche use case that it's not something that I expect to explore at the early stages of development that FDE is now scoped to, so I'm going to close this. If you'd like to see it longer term, you can file it as a Flutter feature request. (If you do, I would suggest providing more details about what exactly you want to be able to do.)
