### ISSUE TITLE
[linux][windows] The pixel ratio is hardcoded to 1 which causes ugly rendering on high DPI displays.

### ISSUE THREAD

**Issue by chinmaygarde** [google/flutter-desktop-embedding#32]
[This value](https://github.com/google/flutter-desktop-embedding/blob/88f1385481f0cd1ba8ce91bfd30bc5486248f2ca/macos/library/FLEViewController.m#L317) must be determined based on the pixel ratio of the display.

**Comment by stuartmorgan** [comment]
Thanks, I noticed this while in that part of the code again recently but hadn't filed a tracking bug.

**Comment by pulyaevskiy** [comment]
I suspect this would address https://github.com/flutter/flutter/issues/15283 ?

**Comment by krisgiesing** [comment]
It's possible there's more than one issue affecting flutter/flutter#15283, but yes, it's very likely related.

**Comment by awdavies** [comment]
This is gonna be a bit of a nuisance in Linux, but just to verify (and write for reference if it's correct) the pseudocode to get the pixel ratio would look something like this?

```dart
var dpi = getDisplayDpi();
var dpmm = dpi / 25.4;  // There are 25.4mm in an inch.
var pix_ratio = ((dpmm * getPhysicalDisplayWidthInMillimeters()) / getLogicalDisplayWidthInPixels()) *
                ((dpmm * getPhysicalDisplayHeightInMillimeters()) / getLogicalDisplayHeightInPixels());
```
This doesn't quite work for mobile, because plugging in the values for a Nexus 6 (`159.26 x 82.98` in mm) which has a DPI of 560, gets:
`dpi == 560`, `dpmm == 22.05`, and `pix_ratio == 1.75`, which is not what the phone reports (it's 3.5)

But AFAIK there's no direct way to get the pixel ratio on Linux (can't speak for Mac).

**Comment by chinmaygarde** [comment]
I believe [`-[NSView convertPointToBacking:]`](https://developer.apple.com/documentation/appkit/nsview/1483803-convertpointtobacking) gives you the ratio to use on AppKit. You could try something like the following to see if the values are reasonable.

```
NSPoint converted = [_renderSurface convertPointToBacking:NSMakePoint(1.0, 1.0)];
NSLog(@"%@", NSStringFromPoint(converted));
```

I don't know where to begin on Linux but the psuedocode looks about right.

**Comment by krisgiesing** [comment]
Then there's the question of what happens if the Flutter window is dragged to be half in one monitor and half in another...

**Comment by stuartmorgan** [comment]
For macOS I believe the normal behavior is that the window changes scale factor once the majority of the window is in the other monitor. I'll need to set up a test configuration and see how that interacts with NSOpenGLView's backing store.

For Linux we can probably punt on this for now. It looks like GTK provides this info at the view level (as macOS does) via gtk_widget_get_scale_factor, which avoids the problem of knowing which screen to check.

**Comment by stuartmorgan** [comment]
I did a bit of searching while reviewing the Windows GLFW PR, and it looks like we could do a simple implementation for the GLFW embedder using http://www.glfw.org/docs/latest/monitor_guide.html#monitor_size
