### ISSUE TITLE
SetIcon not working

### ISSUE THREAD

**Issue by canewsin** [google/flutter-desktop-embedding#324]
I was using this lib
https://github.com/nothings/stb
and another thing is i was using simple flutter png image with 400*400

```
File : flutter_embedder_example.cc

#include <stdint.h>

#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"

int main() {
    .
    .
    .
    std::string icon_path = assets_path + "/icon.png";
    int width, height, bpp; 
    uint8_t* rgb_image = stbi_load(icon_path.c_str(), &width, &height, &bpp, 3);
    printf("width + %d" " + height %d",width,height);
    flutter_controller.SetIcon(rgb_image,width,height);
    flutter_controller.SetTitle("Another Title");
}
```
I was not able to set icon in this case

**Comment by stuartmorgan** [comment]
The documentation for `SetIcon` clearly states: "The pixel format is 32-bit RGBA".

Based on the comment on `stbi_load`, passing `3` as the last argument gives you 24-bit RGB, which is the wrong format.
