### ISSUE TITLE
Attach to a running Flutter application is not working

### ISSUE THREAD

**Issue by Kleak** [google/flutter-desktop-embedding#341]
**Describe the bug**
*Please provide a clear and concise description of the bug, including steps to reproduce, and, if relevant, screenshots.*

I have put the observatory port to a specific number. 
Then i use the attach command in vscode but it never attach.

**Development Environment (please complete the following information):**
* OS: *linux*

**Doctor Output**

```
[✓] Flutter (Channel master, v1.5.4-pre.17, on Linux, locale en_US.UTF-8)
    • Flutter version 1.5.4-pre.17 at /home/kevin/Work/github.com/flutter/flutter
    • Framework revision 0545c63b9b (22 hours ago), 2019-04-19 20:41:32 -0400
    • Engine revision ca31a7c57b
    • Dart version 2.3.0 (build 2.3.0-dev.0.1 cf4444b803)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/kevin/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at:
      /home/kevin/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5452501/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /home/kevin/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5452501
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] VS Code (version 1.33.1)
    • VS Code at /usr/share/code
    • Flutter extension version 2.25.1

[✓] Connected device (1 available)
    • Linux • Linux • linux-x64 • Linux

• No issues found!
```

```
Checking dependencies:

--------------------
Verifying git...
Running git --version
git version 2.21.0

--------------------
Verifying GN...
Running gn --version
1559 (78db9de5)

--------------------
Verifying ninja...
Running ninja --version
1.8.2

--------------------
Verifying GCC...
Running g++ --version
g++ (Ubuntu 8.3.0-6ubuntu1) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


--------------------
Verifying libraries...
Running pkg-config --exists --print-errors gtk+-3.0 jsoncpp

====================
No issues found
```

**Comment by jonahwilliams** [comment]
What is the observatory port reported as when you run the executable directly?

**Comment by stuartmorgan** [comment]
I'm not able to get this working on macOS today either. Based on the URL, and the last few commits in my Flutter tree, it looks like observatory URI auth tokens just landed.

Looks like Dart Code needs to be updated to support it, which means at the moment I don't think there's anything we can do to make attach work: https://github.com/Dart-Code/Dart-Code/issues/1632

**Comment by jonahwilliams** [comment]
The required flag should be available on master with `--debug-uri`.

**Comment by stuartmorgan** [comment]
I was going to wait until the Track Widget Creation bug was fixed in our `build` support to document the new and improved VS Code debugging approach, but since attach is broken I've gone ahead and updated the debugging instructions now with the caveat about disabling that.

Leaving this open since I want to re-test attach once Dart Code supports it again with Flutter master, and document the new flow. (I'm hoping it will Just Work when using `flutter run`, but we may still need at attach config.)

**Comment by stuartmorgan** [comment]
Closing; I updated the attach instructions (and filed https://github.com/Dart-Code/Dart-Code/issues/1638 for a workflow improvement), but forgot to close this at the time.
