### ISSUE TITLE
IME(Input Method Editor) position error

### ISSUE THREAD

**Issue by vipyami** [google/flutter-desktop-embedding#345]
when run example in MacOS, the IME position is error:
1. OS locale is zh_cn,  Chinese language system
2. Flutter is master branch
3. latest flutter-desktop-embedding package
3. Xcode 10.2.1
the error image:

![image](https://user-images.githubusercontent.com/3376549/56482381-7938aa80-64f6-11e9-8890-71c295221c44.png)

The expected position is under the input cursor.

**Comment by stuartmorgan** [comment]
This is under the umbrella of work tracked by https://github.com/flutter/flutter/issues/30660.
