### ISSUE TITLE
Error Building Example on Windows

### ISSUE THREAD

**Issue by canewsin** [google/flutter-desktop-embedding#352]
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4019	The imported project "C:\flutter\flutter-desktop-embedding\example\windows\Generated.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.	Runner	C:\flutter\flutter-desktop-embedding\example\windows\Runner.vcxproj	44	

```

Also Specified cmd for windows only works in powershell as it is powershell syntax specify there there that user should use powershell

or add SET CMD to cmd users
https://github.com/google/flutter-desktop-embedding/blob/master/example/README.md#enable-desktop-support

and even windows cmd 
`$env:ENABLE_FLUTTER_DESKTOP="true"`

`flutter release` still shows no devices in console

**Comment by stuartmorgan** [comment]
That file is generated (per the name) by `flutter run`, and as the example README says:
> the first build must be done via flutter run in order to generate necessary files.
Did you build with the `flutter` tool, or did you try to build the project directly?

> `flutter release` still shows no devices in console

I'm not aware of `release` being a Flutter command. Do you mean `devices`?

What is your Flutter version?

**Comment by stuartmorgan** [comment]
> Also Specified cmd for windows only works in powershell

Good point; I've updated the README to include both variants.

**Comment by JustBrenkman** [comment]
If you are using flutter 1.2.1 they have changed the variable name to FLUTTER_DESKTOP_EMBEDDING

**Comment by stuartmorgan** [comment]
> If you are using flutter 1.2.1

If you are using Flutter 1.2.1, pretty much nothing in this repository will work because the current state relies on changes that landed in the last week, and 1.2.1 is several months old. This project generally requires the latest Flutter version (on master), as it says in the README.

> they have changed the variable name to FLUTTER_DESKTOP_EMBEDDING

No, the variable used to be `FLUTTER_DESKTOP_EMBEDDING`, and was changed.

**Comment by stuartmorgan** [comment]
> That file is generated (per the name) by flutter run, and as the example README says:
>
>>  the first build must be done via flutter run in order to generate necessary files.
>
> Did you build with the flutter tool, or did you try to build the project directly?

Absent a response, I'm going to assume this was the issue and close the bug, since that file is written unconditionally by the build script so I don't see how else it could have happened.

If you did `flutter run` and still did somehow see that error, please update with complete build logs and I can re-open for investigation.

**Comment by canewsin** [comment]
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4019	The imported project "C:\flutter\flutter-desktop-embedding\plugins\example_plugin\windows\flutter\Generated.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.	ExamplePlugin	C:\flutter\flutter-desktop-embedding\plugins\example_plugin\windows\ExamplePlugin.vcxproj	41	

```
Error while building plugin for windows

**Comment by stuartmorgan** [comment]
> C:\flutter\flutter-desktop-embedding\plugins\example_plugin\windows\flutter\Generated.props

That path looks like you opened the plugin project directly and tried to build it, which [is not how they are set up](https://github.com/google/flutter-desktop-embedding/tree/master/plugins#building-1)

**Comment by canewsin** [comment]
@stuartmorgan 
```
Building
The plugin projects are designed to be built from within the solution of the application using them. Add the .vcxproj files for the plugins you want to build to your application's Runner.sln.
```
I don't know how to do this
What i tried is Open runner.sln file and go to file>add> and added example_plugin.vcxproj file and 
billd>build runner but plugin not build to build dir outside

**Comment by canewsin** [comment]
Ok I right click the example plugin in solution explorer and build that it outputs to build dir in project folder and add this line to 
> #include "../build/windows/x64/Debug/Plugins/example_plugin.h"

Got this error
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1318	Unexpected PDB error; FORMAT (11) 'C:\flutter\flutter-desktop-embedding\example\build\windows\x64\Debug\Runner\Flutter Desktop Example.pdb'	Runner	C:\flutter\flutter-desktop-embedding\example\build\windows\x64\Debug\Runner\Flutter Desktop Example.pdb	1
```

**Comment by stuartmorgan** [comment]
Since this is not related to the initial issue you filed about building the stock example app, please file a new issue (and clearly describe what you are doing; it's very hard to troubleshoot an issue when I don't know what modifications you have made locally).
