### ISSUE TITLE
Example crash in macOS

### ISSUE THREAD

**Issue by piaojin** [google/flutter-desktop-embedding#358]
macOS:
`10.14.4`

Xcode:
`10.2.1`

Flutter:
```
Flutter 1.4.12 • channel dev • https://github.com/flutter/flutter.git
Framework • revision 294d7ea0cf (3 weeks ago) • 2019-04-08 12:37:43 -0700
Engine • revision ff1bcdc009
Tools • Dart 2.2.1 (build 2.2.1-dev.3.0 None)
```

**Describe Request**
Crash when run the example. The following are the crash logs.
[flutter_02.log](https://github.com/google/flutter-desktop-embedding/files/3125060/flutter_02.log)
[flutter_01.log](https://github.com/google/flutter-desktop-embedding/files/3125061/flutter_01.log)
[flutter_03.log](https://github.com/google/flutter-desktop-embedding/files/3125062/flutter_03.log)

**Comment by jonahwilliams** [comment]
It looks like you haven't configured flutter project according to https://github.com/flutter/flutter/wiki/Desktop-shells, because the logs indicate we're attempting to run an iOS build.

Furthermore, only the last week or so of flutter master supports desktop, your flutter version is too old.

**Comment by piaojin** [comment]
@jonahwilliams I will update flutter and try again. Thank you!
