### ISSUE TITLE
Hide observatory window

### ISSUE THREAD

**Issue by thebf** [google/flutter-desktop-embedding#359]
Is there a way to avoid/disable the spawning of the observatory window

**Comment by stuartmorgan** [comment]
I'm assuming you're on Windows; this is tracked by https://github.com/flutter/flutter/issues/31268

(But if you mean the observatory service, rather than the console window, you can add `--disable-observatory` in your runner code.)

**Comment by Tokenyet** [comment]
I saw It add in milestone! But If someone need a workaround, I found out a simple way to do it.

1. Open flutter_embedder_example.cpp
2. Add the following code at certain line (I added after the line of plugin loaded):
```
::ShowWindow(::GetConsoleWindow(), SW_HIDE);
```

This would popup up command in a second, but is going to be disappeared finally.
