### ISSUE TITLE
embedder crashes on linux with latest flutter

### ISSUE THREAD

**Issue by billy1380** [google/flutter-desktop-embedding#36]
I did an update of flutter and rebuilt libflutter_engine.so with --runtime-mode=debug but running the app with the embedder is causing a segmentation fault.
`5223 Segmentation fault      (core dumped) ./app/app.bin`
Is there any way to view a call stack or something to help with why this might be happening?

As usual all help appreciated.

Many thanks.

**Comment by awdavies** [comment]
What were the Flutter/Flutter Engine checkout hashes?  Recently Flutter and the engine switched from Dart 1 to Dart 2 which no longer supports snapshot mode, and there can be some weird behavior if the versions aren't in sync.

**Comment by billy1380** [comment]
@awdavies the last commit hash on flutter engine master is 04f3c6557c02879191a558320ed8ec81f8b2b619

How can I tell if things are not in sync? I definitely called `gclient sync` after getting the latest code and doing a build, or are you talking about something else?

**Comment by awdavies** [comment]
I've got a pull request for this in the works, but (hopefully) it's just a mismatch of what version of the engine Flutter is expecting.

Inside of `flutter/bin/internal/` there is a file called `engine.version` that has the hash that it expects the engine to be set to.

**Comment by awdavies** [comment]
The pull request is for updating the readme to specify the use of `engine.version`, specifically

**Comment by billy1380** [comment]
the hash in my `engine.version` file is identical to the one above :disappointed:

**Comment by awdavies** [comment]
I haven't updated in a while.  I'm checkin it out now 😄

**Comment by awdavies** [comment]
Good news...? I get the same error!

**Comment by billy1380** [comment]
very mixed emotions right now!

**Comment by billy1380** [comment]
does that mean that you can get it to run the second time around?

**Comment by stuartmorgan** [comment]
The roll to 04f3c6557c02879191a558320ed8ec81f8b2b619 didn't pick up the fix for #30 / #33 so that's the crash.

You'll need to do one of:
- Use the current head of the engine repo, which has the fix
- Run in source mode instead of snapshot mode
- Wait until Flutter rolls the engine again.

**Comment by stuartmorgan** [comment]
Duplicate of #33

**Comment by billy1380** [comment]
I will try the second option then the first one and see how I get on. Thank you.

**Comment by billy1380** [comment]
Three cheers for option number 1... works beautifully now... thanks for all the time and effort... much appreciated.
