### ISSUE TITLE
Plugin Build Error(Flutter library update aborted: Your Flutter tree is too old for use with this project.)

### ISSUE THREAD

**Issue by JAICHANGPARK** [google/flutter-desktop-embedding#366]
I'm windows user
>tools\gn_dart gen out && ninja -C out

>Done. Made 3 targets from 7 files in 6ms
ninja: Entering directory `out'
[1/7] ACTION //plugins/common:fetch_flutter_library(//build/win/toolchain:msvc)
FAILED: gen/flutter_library/flutter_windows.dll gen/flutter_library/flutter_windows.dll.lib gen/flutter_library/flutter_windows.dll.exp gen/flutter_library/flutter_windows.dll.pdb gen/flutter_library/flutter_export.h gen/flutter_library/flutter_messenger.h gen/flutter_library/flutter_plugin_registrar.h gen/flutter_library/flutter_glfw.h gen/flutter_library/cpp_client_wrapper/byte_stream_wrappers.h gen/flutter_library/cpp_client_wrapper/engine_method_result.cc gen/flutter_library/cpp_client_wrapper/json_message_codec.cc gen/flutter_library/cpp_client_wrapper/json_method_codec.cc gen/flutter_library/cpp_client_wrapper/plugin_registrar.cc gen/flutter_library/cpp_client_wrapper/standard_codec.cc gen/flutter_library/cpp_client_wrapper/standard_codec_serializer.h gen/flutter_library/cpp_client_wrapper/flutter_window_controller.cc gen/flutter_library/cpp_client_wrapper/include/flutter/basic_message_channel.h gen/flutter_library/cpp_client_wrapper/include/flutter/binary_messenger.h gen/flutter_library/cpp_client_wrapper/include/flutter/encodable_value.h gen/flutter_library/cpp_client_wrapper/include/flutter/engine_method_result.h gen/flutter_library/cpp_client_wrapper/include/flutter/json_message_codec.h gen/flutter_library/cpp_client_wrapper/include/flutter/json_method_codec.h gen/flutter_library/cpp_client_wrapper/include/flutter/json_type.h gen/flutter_library/cpp_client_wrapper/include/flutter/message_codec.h gen/flutter_library/cpp_client_wrapper/include/flutter/method_call.h gen/flutter_library/cpp_client_wrapper/include/flutter/method_channel.h gen/flutter_library/cpp_client_wrapper/include/flutter/method_codec.h gen/flutter_library/cpp_client_wrapper/include/flutter/method_result.h gen/flutter_library/cpp_client_wrapper/include/flutter/plugin_registrar.h gen/flutter_library/cpp_client_wrapper/include/flutter/standard_message_codec.h gen/flutter_library/cpp_client_wrapper/include/flutter/standard_method_codec.h gen/flutter_library/cpp_client_wrapper/include/flutter/flutter_window_controller.h
C:\Users\HOME613\Desktop\Research\flutter_desktop_ex\flutter\bin\cache\dart-sdk\bin\dart ../tools/dart_tools/bin/sync_flutter_library.dart --flutter_root=C:/Users/HOME613/Desktop/Research/flutter_desktop_ex/flutter gen/flutter_library
Running git merge-base --is-ancestor 829130ddfcf84aa683291744fb6d170f61f0287b HEAD
Flutter library update aborted: Your Flutter tree is too old for use with this project. Please update to a newer version of Flutter, then try again.

Note that this may require switching to Flutter master. See:
https://github.com/flutter/flutter/wiki/Flutter-build-release-channels
ninja: build stopped: subcommand failed.

**Comment by stuartmorgan** [comment]
The project README documents the requirement to use the latest Flutter master; getting this error if you aren't is expected behavior, not a bug.
