### ISSUE TITLE
How to build the example to run on windows xp?

### ISSUE THREAD

**Issue by boyen747** [google/flutter-desktop-embedding#372]
How to build the example to run on windows xp?

Best Regards!

**Comment by stuartmorgan** [comment]
As the README says, this project requires Visual Studio 2017 or 2019, so it's not possible to build it on XP.

**Comment by canewsin** [comment]
@boyen747 You may try prebuild bins from repo
https://github.com/canewsin/flutter_desktop_launcher
and sync your flutter code

**Comment by stuartmorgan** [comment]
Note that those builds are not associated with this project (or with Flutter itself), and there's no source published for them, so bear that in mind before deciding if you want to run them.

Also note that they will not work with the current version of Flutter on any channel.

**Comment by canewsin** [comment]
Yeah Those were Old Builds But Currently a workaround

**Comment by boyen747** [comment]
@stuartmorgan Now i got it run on win7, and use vs2015. Thanks!

**Comment by canewsin** [comment]
@boyen747 good to listen from you, happy coding
