### ISSUE TITLE
windows cpu too high

### ISSUE THREAD

**Issue by boyen747** [google/flutter-desktop-embedding#374]
whew i run the example on windows, the cpu usage is too high. What's the matter?
![image](https://user-images.githubusercontent.com/5665136/57571462-3efd6180-7441-11e9-9264-aa4390867bb0.png)

**Comment by boyen747** [comment]
Is it caused by OpenGL? Dose the windows example use OpenGL?

**Comment by stuartmorgan** [comment]
See https://github.com/flutter/flutter/issues/30730, which is the tracking bug for this issue.

> Is it caused by OpenGL?

No.

> Dose the windows example use OpenGL?

Yes.

**Comment by boyen747** [comment]
@stuartmorgan I have read the tracking bug, but I don't know if the problem was reloved? or if it can be resolved in future? When i update the code, the cpu usage is still high.

**Comment by stuartmorgan** [comment]
It can be fixed, but it hasn't been fixed yet (which is why that issue is still open).

**Comment by boyen747** [comment]
@stuartmorgan Thanks a lot. I look forward to it.
