### ISSUE TITLE
Support cursor changes

### ISSUE THREAD

**Issue by ethanblake4** [google/flutter-desktop-embedding#376]
Requesting here since it should probably be a plugin first, let me know if I should move it. There should be a way to change the displayed mouse cursor in an FDE app,

- imperatively, by calling a function akin to `setCursor(Cursors.pointer)`
- inline in the Widget tree, with something akin to 
   ```dart
   CursorWidget(
       cursor: Cursors.loading,
       child: MaterialButton(...)
   );
   ```

The first one is more important since we already have `Listener`.

**Comment by stuartmorgan** [comment]
See also https://github.com/flutter/flutter/issues/31952

I think the way to proceed would be to first implement that issue, and then see if there are common use cases that go beyond what's needed for the built-in cursor behavior that may be useful to prototype as a plugin.

**Comment by ethanblake4** [comment]
Ah, didn't see that - thanks! Feel free to close or leave open as needed.

**Comment by rodydavis** [comment]
Here is my PR for the plugin: https://github.com/google/flutter-desktop-embedding/pull/638

**Comment by stuartmorgan** [comment]
Since core cursor support has landed in the framework and can easily be implemented in the desktop embeddings (macOS is already done), closing this. The remaining work is custom cursors, but I don't see a need for that to be done here vs in Flutter itself at this stage.

**Comment by e200** [comment]
@stuartmorgan were can I find more about the implementation? I'm trying to set the cursor on macOS, but I can't see anything about how to achieve this.

**Comment by stuartmorgan** [comment]
There are links to various parts of the implementation in https://github.com/flutter/flutter/issues/31952.
