### ISSUE TITLE
How to modify flutter_glfw.cc

### ISSUE THREAD

**Issue by boyen747** [google/flutter-desktop-embedding#380]
I want to modify the code below just for my test on windows.  I have built the engine, But don't know what to do next?  
![image](https://user-images.githubusercontent.com/5665136/57696854-73149480-7684-11e9-8dbb-47c5d4f73cc3.png)

**Comment by boyen747** [comment]
![image](https://user-images.githubusercontent.com/5665136/57696916-97707100-7684-11e9-8f65-35a455161d97.png)

**Comment by stuartmorgan** [comment]
https://github.com/google/flutter-desktop-embedding/blob/master/LocalEngine.md

**Comment by boyen747** [comment]
Need i compile the engine first as this link said https://github.com/flutter/flutter/wiki/Compiling-the-engine, or I just create a folder named engine next to flutter dir, and put the engine code in it? @stuartmorgan

**Comment by stuartmorgan** [comment]
Compiling is how you build the engine, so yes; that's why the instructions start with that link.

You indicated that you had already built the engine.

**Comment by boyen747** [comment]
Could you tell me if my file tree is correct? The engine_override content is "C:\steven\engine\src\out\host_release", which contains the engine build output。
 @![image](https://user-images.githubusercontent.com/5665136/57711291-06f45980-76a1-11e9-88c6-b41971251229.png)  @stuartmorgan

**Comment by boyen747** [comment]
Then when i execute "flutter run" in example folder, it still use the old engine in "flutter\bin\cache\artifacts\engine", Which step am I wrong?

**Comment by stuartmorgan** [comment]
> Then when i execute "flutter run" in example folder

As it says in the Windows section of the instructions page that I linked to:

> Note that this only works for `testbed`, not `example`.

**Comment by boyen747** [comment]
My engine host_release dir only like this, there's no flutter_windows.dll. Did I miss something when compile it?
![image](https://user-images.githubusercontent.com/5665136/57734876-91ef4700-76d5-11e9-951b-7a11c1904e21.png)

some build info:
[   +2 ms] PreBuildEvent:
[        ]   Sync and build dependencies
[  +12 ms]   C:\steven\flutter-desktop-embedding\testbed\windows\scripts\prepare_dependencies
"C:\steven\flutter-desktop-embedding\testbed\windows\..\build\windows\intermediates\x64\Debug\Runner\"
[   +4 ms]   :VCEnd
[  +88 ms]   C:\steven\flutter-desktop-embedding\testbed\windows\scripts\..\..\..\tools\sync_flutter_library
C:\steven\flutter-desktop-embedding\testbed\windows\..\build\windows\intermediates\x64\Debug\Runner\flutter_library
[ +569 ms]   Running git merge-base --is-ancestor c27d10bf464500ef4e1792e9aa57128c1b281d2f HEAD
[ +269 ms]   Unhandled exception:
[  +12 ms]   FileSystemException: Cannot copy file to 'c:\steven\flutter-desktop-embedding\testbed\build\windows\intermediates\x64\debug\runner\flutter_library\flutter_windows.dll', path =
'C:\steven\engine\src\out\host_release\flutter_windows.dll' (OS Error: 绯荤粺鎵句笉鍒版寚瀹氱殑鏂囦欢銆?
[  +12 ms]   , errno = 2)

**Comment by stuartmorgan** [comment]
A screenshot of a subset of the files in your build output directory doesn't really help with debugging, but if you don't have `flutter_windows.dll` there then the desktop shell wasn't built.

You didn't say what commands you used for building the engine, but looking at the engine build page it looks like the instructions there are out of date for Windows. Assuming you did `ninja -C .\out\<dir created by previous step> gen_snapshot` as it said there, you need to re-run without the `gen_snapshot` argument. I'll update that page.

**Comment by boyen747** [comment]
I used the command "ninja -C .\out\host_release gem_snapshot" before. Last night, when go to bed, I think maybe i can try to build without gem_snapshot param today. I saw the doc has changed this morning. Hope it will works! But I encoutered many file encoding problem, and now I change it by vs2015 one by one. Do you have some smart method to resolve it? @stuartmorgan

**Comment by stuartmorgan** [comment]
I have no idea what you're referring to, so I don't have any suggestions. Also, this is increasingly off-topic for the flutter-desktop-embedding issue tracker at this point, as the Flutter engine is not a part of this project.

If you believe you there are issues with the engine repository, you should file a bug in the Flutter issue tracker (with specific details).
