### ISSUE TITLE
testbeb build error

### ISSUE THREAD

**Issue by boyen747** [google/flutter-desktop-embedding#382]
I have built a local engine on windows, then I cd to testbeb and execute "flutter run -v". I got the error below:

[ +271 ms] Launching lib/main.dart on Windows in debug mode...
[  +45 ms] Building Windows application...
[+2173 ms] **********************************************************************
[   +3 ms] ** Visual Studio 2017 Developer Command Prompt v15.9.11
[        ] ** Copyright (c) 2017 Microsoft Corporation
[        ] **********************************************************************
[ +446 ms] [vcvarsall.bat] Environment initialized for: 'x64'
[ +353 ms] 用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
[   +1 ms] 版权所有(C) Microsoft Corporation。保留所有权利。
[   +1 ms] 在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
[ +120 ms] 生成启动时间为 2019/5/15 20:31:35。
[ +113 ms] 节点 1 上的项目“C:\steven\flutter-desktop-embedding\testbed\windows\Runner.sln”(默认目标)。
[   +1 ms] ValidateSolutionConfiguration:
[   +1 ms]   正在生成解决方案配置“Debug|x64”。
[ +150 ms] 项目“C:\steven\flutter-desktop-embedding\testbed\windows\Runner.sln”(1)正在节点 1 上生成“C:\steven\flutter-desktop-embedding\testbed\windows\Runner.vcxproj”(2) (默认目标)。
[   +2 ms] InitializeBuildStatus:
[   +3 ms]   正在对“C:\steven\flutter-desktop-embedding\testbed\windows\..\build\windows\intermediates\x64\Debug\Runner\Runner.tlog\unsuccessfulbuild”执行 Touch 任务。
[   +1 ms] PreBuildEvent:
[   +3 ms]   Sync and build dependencies
[  +11 ms]   C:\steven\flutter-desktop-embedding\testbed\windows\scripts\prepare_dependencies "C:\steven\flutter-desktop-embedding\testbed\windows\..\build\windows\intermediates\x64\Debug\Runner\"
[   +2 ms]   :VCEnd
[ +159 ms]   C:\steven\flutter-desktop-embedding\testbed\windows\scripts\..\..\..\tools\sync_flutter_library
C:\steven\flutter-desktop-embedding\testbed\windows\..\build\windows\intermediates\x64\Debug\Runner\flutter_library
[ +579 ms]   Running git merge-base --is-ancestor c27d10bf464500ef4e1792e9aa57128c1b281d2f HEAD
[ +535 ms]   Copied artifacts from C:\steven\engine\src\out\host_debug.
[ +249 ms]   gn.py: Could not find checkout in any parent of the current path.
[   +1 ms]   This must be run inside a checkout.
[  +29 ms] C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(128,5): error MSB3073:
命令“C:\steven\flutter-desktop-embedding\testbed\windows\scripts\prepare_dependencies "C:\steven\flutter-desktop-embedding\testbed\windows\..\build\windows\intermediates\x64\Debug\Runner\"
[C:\steven\flutter-desktop-embedding\testbed\windows\Runner.vcxproj]
[   +6 ms] C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(128,5): error MSB3073: :VCEnd”已退出，代码为 1。
[C:\steven\flutter-desktop-embedding\testbed\windows\Runner.vcxproj]
[   +9 ms] 已完成生成项目“C:\steven\flutter-desktop-embedding\testbed\windows\Runner.vcxproj”(默认目标)的操作 - 失败。
[   +6 ms] 已完成生成项目“C:\steven\flutter-desktop-embedding\testbed\windows\Runner.sln”(默认目标)的操作 - 失败。
[   +3 ms] 生成失败。

**Comment by stuartmorgan** [comment]
From testbed/README.md:

> The examples build the plugins from source, so you will need to ensure you have all the dependencies for building the plugins on your platform.

Which links to plugins/README.md. From plugins/README.md

> Note: If you have `depot_tools` installed, ensure that the copy of `gn` you install is before it in your path. If you see build failures that contain` gn.py: Could not find checkout in any parent of the current path` then the `gn` script from `depot_tools` is being used instead.

Most of the issues you've raised in the issues you've filed here have been directly addressed in the READMEs. If you encounter issues in the future, *please check the READMEs* before filing issues.

**Comment by boyen747** [comment]
Now it works well used built engine. I'm not familiar with windows, or dart, gn, vs2017 etc. Thank you very much. And the engine I'm using is built in debug mode. If build it in release mode, I get the error below. I have post the [question ](https://github.com/flutter/flutter/issues/32746) in flutter page, but nobody anwsers yet.
