### ISSUE TITLE
Flutter Application Requirements: `Getter not found: Platform`

### ISSUE THREAD

**Issue by adam-mcdaniel** [google/flutter-desktop-embedding#389]
In the `Flutter Application Requirements` markdown document says we can switch over `Platform`, but `Platform` isn't defined. Where can I import `Platform`?

**Describe Request**

**Comment by stuartmorgan** [comment]
It's a standard Dart class: https://api.dartlang.org/stable/2.3.0/dart-io/Platform-class.html

**Comment by adam-mcdaniel** [comment]
Thank you v much! :)
