### ISSUE TITLE
Failed to find engine stamp file

### ISSUE THREAD

**Issue by kasnet** [google/flutter-desktop-embedding#390]
I open ExampleEmbedder.xcodeproj on macos, it fail.
Please help me how to solve this problem.

`
Running git merge-base --is-ancestor 4e1bfca8470ff088ecb68aaa72086f290b316fd1 HEAD
Running /Users/zk/Documents/wwwroot/FlutterDesktop/flutter/bin/flutter unpack --target-platform=darwin-x64 --cache-dir=/Users/zk/Documents/wwwroot/FlutterDesktop/flutter_framework
Failed to find engine stamp file
Failed to unpack desktop artifacts.
Unhandled exception:
Exception: /Users/zk/Documents/wwwroot/FlutterDesktop/flutter/bin/flutter unpack --target-platform=darwin-x64 --cache-dir=/Users/zk/Documents/wwwroot/FlutterDesktop/flutter_framework failed with exit code 1
#0      runCommand (file:///Users/zk/Documents/wwwroot/FlutterDesktop/flutter-desktop-embedding/tools/dart_tools/lib/run_command.dart:45:5)
<asynchronous suspension>
#1      runFlutterCommand (file:///Users/zk/Documents/wwwroot/FlutterDesktop/flutter-desktop-embedding/tools/dart_tools/lib/flutter_utils.dart:59:9)
<asynchronous suspension>
#2      main (file:///Users/zk/Documents/wwwroot/FlutterDesktop/flutter-desktop-embedding/tools/dart_tools/bin/sync_flutter_library.dart:82:9)
<asynchronous suspension>
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
Command /bin/sh failed with exit code 255
`

**Comment by stuartmorgan** [comment]
ExampleEmbedder was renamed at least a month ago, but the script output here is from a very recent version. How did you set up your build environment to get into this state?

**Comment by kasnet** [comment]
```
<parent dir>
  ├─ flutter (from http://github.com/flutter/flutter)
  ├─ flutter-desktop-embedding (from https://github.com/google/flutter-desktop-embedding)
  └─ flutter_slides (from https://github.com/flutter/slideplayer)
```
I open ExampleEmbedder.xcodeproj in slideplayer project.

**Comment by stuartmorgan** [comment]
FDE is very explicitly not a stable API surface; an app build against an arbitrary version of it isn't going to work with new versions of FDE without updates (which that project doesn't appear to have had recently).

The README there gives hashes of Flutter and FDE versions that are known to work; if you want to try the project out you'll need to use those. (Or port their native code changes into a current version of FDE's example Runner).
