### ISSUE TITLE
Build Failed in Windows Desktop

### ISSUE THREAD

**Issue by KumarSunil17** [google/flutter-desktop-embedding#398]
**Describe Request**
 Unable to build: could not find vcvars64.bat while I run in windows desktop.

**Comment by stuartmorgan** [comment]
Did you follow [the setup instructions](https://github.com/google/flutter-desktop-embedding#tools)? If so, what is the installation path for Visual Studio on your machine?

**Comment by KumarSunil17** [comment]
> Did you follow [the setup instructions](https://github.com/google/flutter-desktop-embedding#tools)? If so, what is the installation path for Visual Studio on your machine?

Here is my path for Visual Studio : D:\Program Files\Microsoft Visual Studio. I also installed "Desktop development with C++" workload in VC

**Comment by stuartmorgan** [comment]
The script can currently only find it if it's installed to `%PROGRAMFILES(X86)%` (https://github.com/flutter/flutter/issues/33249 tracks improving it) or in your path, so for now you'd need to add the directory containing it (`<version>\<flavor>\VC\Auxiliary\Build\` under that directory) to your path.

However, the fact that it's installed to `Program Files\` suggests that you are running 32-bit Windows, which Flutter doesn't support.

**Comment by KumarSunil17** [comment]
> The script can currently only find it if it's installed to `%PROGRAMFILES(X86)%` ([flutter/flutter#33249](https://github.com/flutter/flutter/issues/33249) tracks improving it) or in your path, so for now you'd need to add the directory containing it (`<version>\<flavor>\VC\Auxiliary\Build\` under that directory) to your path.
> 
> However, the fact that it's installed to `Program Files\` suggests that you are running 32-bit Windows, which Flutter doesn't support.

No, I installed it into my custom path i.e. D:\Program FIles instead of C:\Program Files.

**Comment by stuartmorgan** [comment]
> instead of C:\Program Files

Well, normally on a 64-bit Windows installation it would be in `C:\Program Files (x86)`, not `C:\Program Files`, thus my confusion.

But if you're on 64-bit Windows, then things should work fine once your path includes the `Build` directory containing `vcvars64.bat`

**Comment by stuartmorgan** [comment]
As a quick follow-up question, to help with solving this is general in the script: do you have `%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe` on your machine? It's unclear to me from the documentation I've found whether the `%ProgramFiles(x86)%\Microsoft Visual Studio` portion of that is guaranteed, on whether it's itself subject to custom install paths.

**Comment by stuartmorgan** [comment]
Never mind, I just found https://github.com/Microsoft/vswhere/issues/41#issuecomment-296251196 which has the definitive answer. Sounds like it'll be straightforward to make the lookup used by `flutter build` robust given that.
