### ISSUE TITLE
[macOS] Support VoiceOver

### ISSUE THREAD

**Issue by stuartmorgan** [google/flutter-desktop-embedding#40]
Currently VoiceOver has no visibility into the Flutter surface. Since it works on iOS presumably macOS could also be wired up, but it may require exposing something via the embedding API (or it may be entirely within Flutter, in which case this just tracks the need to ensure that work is done on the Flutter side).

**Comment by gedw99** [comment]
this would be amazing :)

**Comment by stuartmorgan** [comment]
This should be unblocked now due to https://github.com/flutter/engine/pull/7891

**Comment by stuartmorgan** [comment]
Moved to https://github.com/flutter/flutter/issues/23601
