### ISSUE TITLE
[linux] build.sh: not found

### ISSUE THREAD

**Issue by hemnathmouli** [google/flutter-desktop-embedding#404]
**Describe the bug**
I copied `linux` from `example` folder to my current project. And the `ENABLE_FLUTTER_DESKTOP` is set `true`

And the with CLI, I get the following error:
```
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                           
Build process failed
/bin/sh: 1: /home/hemz/Apps/android/hn_app/linux/build.sh: not found
```

**Development Environment (please complete the following information):**
* OS: Linux 17.04
* Developer tools version (Xcode, Visual Studio, or gcc): GCC 7.4.0

**Doctor Output**
For build issues, please provide the output of `flutter doctor -v`:
```
[✓] Flutter (Channel beta, v1.5.4-hotfix.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.5.4-hotfix.2 at /home/hemmy/Apps/flutter
    • Framework revision 7a4c33425d (4 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/hemmy/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/hemmy/Apps/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /home/hemmy/Apps/android-studio
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] VS Code (version 1.34.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.0.2

[✓] Connected device (1 available)
    • Linux • Linux • linux-x64 • Linux

• No issues found!
```

**Comment by stuartmorgan** [comment]
> [✓] Flutter (Channel beta, v1.5.4-hotfix.2, on Linux, locale en_US.UTF-8)

That version is too old for this project; build.sh is no longer part of the buildjprocess. Per the very first instruction in the example README:
> Ensure that you are on the latest version of the Flutter master channel.

See also [the bolded text here](https://github.com/google/flutter-desktop-embedding/blob/master/Quick-Start.md#copy-the-linux-macos-andor-windows-directories-from-example).
