### ISSUE TITLE
Support send scancode, action, mods on KeyboardHook function

### ISSUE THREAD

**Issue by vimesdev** [google/flutter-desktop-embedding#405]
Could you send scancode, action, mods in the function KeyboardHook
Like function OnHandleKeyboardEvent of class PlatformView
https://github.com/flutter/engine/blob/master/shell/platform/fuchsia/flutter/platform_view.cc

**Describe Request**

**Comment by stuartmorgan** [comment]
This request belongs in the Flutter repository, not here, since it's about what the engine is sending.

That work is already in progress; I filed https://github.com/flutter/flutter/issues/33395 to track it since a bug hadn't been filed yet even though it's under development.
