### ISSUE TITLE
Space in framework causing build error in Windows

### ISSUE THREAD

**Issue by joseinazusa** [google/flutter-desktop-embedding#415]
When the SDK for flutter was placed in a folder where there was a space, in this case
c:\Program Files\flutter\sdk
Build would fail
When I moved to non space path
c:\flutter\flutter-sdk
Build was successful.

![1_J1NQMcoUwVHUYau5qrW4kw](https://user-images.githubusercontent.com/1221190/58761509-0ad60780-84fa-11e9-86de-f36ba6031cf7.png)

**Comment by stuartmorgan** [comment]
The patch above should fix the error you saw. I don't have my Windows machine to test on at the moment so it's possible that there are other space-related issues deeper in the build scripts, but I didn't see any in quick audit. If you still can't build, please post the new error.
