### ISSUE TITLE
canvas.drawParagraph() dosen't show text on desktop

### ISSUE THREAD

**Issue by rafalbednarczuk** [google/flutter-desktop-embedding#417]
Paragraph has to pushStyle with custom font set in order to show text in CustomPainter. Setting fontFamily in MaterialApp's theme dosen't solve this issue. It makes packages like chart_flutter not showning text on charts.

**Comment by stuartmorgan** [comment]
This is https://github.com/flutter/flutter/issues/30700

> Paragraph has to pushStyle with custom font set in order to show text in CustomPainter. Setting fontFamily in MaterialApp's theme dosen't solve this issue.

I'll update the wiki to make it clearer that setting the theme won't solve every problem stemming from the lack of good default font handling, just a common instance.
