### ISSUE TITLE
Error Building Example Plugin Provided for windows

### ISSUE THREAD

**Issue by canewsin** [google/flutter-desktop-embedding#426]
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol __imp_ExamplePluginRegisterWithRegistrar referenced in function main	Runner	C:\flutter\flutter-desktop-embedding\example\windows\flutter_embedder_example.obj	1	
```

What i do is :
fetched latest copy of this repo
open visual studio
open example app sln file
added example_plugin to project by file>add>add existing proj
and build example_plugin by solution explorer > right clicked example_plugin > build

added line to flutter_embedder_example.cpp 
> #include "../build/windows/x64/Debug/Plugins/example_plugin.h"

added line 
>  ExamplePluginRegisterWithRegistrar(flutter_controller.GetRegistrarForPlugin("ExamplePlugin"));

after these lines

``` c++
  // Start the engine.
  if (!flutter_controller.CreateWindow(800, 600, "Flutter Desktop Example",
                                       assets_path, arguments)) {
    return EXIT_FAILURE;
  }
```
and try to build runner in solution explorer > Above Error Occured

**Comment by stuartmorgan** [comment]
The first line in [the section on adding a plugin to Windows is](https://github.com/google/flutter-desktop-embedding/tree/master/plugins#adding-to-an-application-1):
> Link the library files for the plugins you want to include into your exe.

The error above indicates that you didn't do that.

If you're not familiar with how to add libraries in Visual Studio I recommend you diff `example/windows` and `testbed/windows` to see what changes were made. The Windows version of `testbed` is exactly the working result of what you are trying to do.

**Comment by ManasMalla** [comment]
Actually I didn't really get what was going on in the link you provided - 

> The first line in [the section on adding a plugin to Windows is](https://github.com/google/flutter-desktop-embedding/tree/master/plugins#adding-to-an-application-1):
> 
> > Link the library files for the plugins you want to include into your exe.
> 
> The error above indicates that you didn't do that.
> 
> If you're not familiar with how to add libraries in Visual Studio I recommend you diff `example/windows` and `testbed/windows` to see what changes were made. The Windows version of `testbed` is exactly the working result of what you are trying to do.

**Comment by stuartmorgan** [comment]
> Actually I didn't really get what was going on in the link you provided -

That link was to instructions that haven't existed for well over a year. They were about manually integrating plugins into projects before `flutter` had Windows plugin support.

This issue was about using a plugin that no longer exists, using long-obsolete instructions, and has no relevance to current use of Flutter.
