### ISSUE TITLE
[linux] IsCreationThreadCurrent(). failure in newest engine build when exiting.

### ISSUE THREAD

**Issue by awdavies** [google/flutter-desktop-embedding#43]
Flutter Version: 824b806bfc08ba99cf6d6fe64cc52a5dc92a0808
Flutter Engine: 76cb311d9c33720dcd19274228b39ecdbad8d9af

```
[FATAL:flutter/fml/memory/weak_ptr.h(178)] Check failed: (checker_.checker).IsCreationThreadCurrent().
```

Is printed out when exiting the engine.  This is a low priority fix.

**Comment by stuartmorgan** [comment]
I'm not seeing this in recent versions of Flutter.
