### ISSUE TITLE
Windows build fails using target other than lib/main.dart

### ISSUE THREAD

**Issue by jaysephjw** [google/flutter-desktop-embedding#436]
Windows build fails when using an entrypoint other than lib/main.dart.

`flutter run --verbose -t lib/some/file.dart`
`...`
**`[+2089 ms]   Target file "lib/main.dart" not found.`**
`Build process failed`

I had no main.dart. Creating one fixed the problem.

<details><summary>Full verbose output</summary>
<code>
$ flutter run --verbose -t lib/glossy/glossy.dart
...
[ +216 ms] Launching lib/glossy/glossy.dart on Windows in debug mode...
[  +92 ms] Building Windows application...
[ +127 ms] **********************************************************************
[        ] ** Visual Studio 2019 Developer Command Prompt v16.1.1
[        ] ** Copyright (c) 2019 Microsoft Corporation
[        ] **********************************************************************
[+1165 ms] [vcvarsall.bat] Environment initialized for: 'x64'
[  +50 ms] Microsoft (R) Build Engine version 16.1.76+g14b0a930a7 for .NET Framework
[        ] Copyright (C) Microsoft Corporation. All rights reserved.
[   +1 ms] Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
[  +32 ms] Build started 6/19/2019 12:38:24 PM.
[ +141 ms] Project "C:\Users\Jay\projects\glossy-flutter\windows\Runner.sln" on node 1 (default targets).
[        ] ValidateSolutionConfiguration:
[        ]   Building solution configuration "Debug|x64".
[ +146 ms] Project "C:\Users\Jay\projects\glossy-flutter\windows\Runner.sln" (1) is building "C:\Users\Jay\projects\glossy-flutter\windows\Runner.vcxproj" (2) on node 1 (default targets).
[        ] InitializeBuildStatus:
[        ]   Touching "C:\Users\Jay\projects\glossy-flutter\windows\..\build\windows\intermediates\x64\Debug\Runner\Runner.tlog\unsuccessfulbuild".
[        ] PreBuildEvent:
[        ]   Sync and build dependencies
[  +12 ms]   "C:\Users\Jay\projects\glossy-flutter\windows\scripts\prepare_dependencies" debug
[        ]   :VCEnd
[+2089 ms]   Target file "lib/main.dart" not found.
[  +23 ms] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(128,5): error MSB3073: The command ""C:\Users\Jay\projects\glossy-flutter\windows\scripts\prepare_dependencies" debug [C:\Users\Jay\projects\glossy-flutter\windows\Runner.vcxproj]
[        ] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(128,5): error MSB3073: :VCEnd" exited with code 1. [C:\Users\Jay\projects\glossy-flutter\windows\Runner.vcxproj]
[   +1 ms] Done Building Project "C:\Users\Jay\projects\glossy-flutter\windows\Runner.vcxproj" (default targets) -- FAILED.
[   +1 ms] Done Building Project "C:\Users\Jay\projects\glossy-flutter\windows\Runner.sln" (default targets) -- FAILED.
[   +1 ms] Build FAILED.
[   +3 ms] "C:\Users\Jay\projects\glossy-flutter\windows\Runner.sln" (default target) (1) ->
[        ] "C:\Users\Jay\projects\glossy-flutter\windows\Runner.vcxproj" (default target) (2) ->
[        ] (PreBuildEvent target) ->
[        ]   C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(128,5): error MSB3073: The command ""C:\Users\Jay\projects\glossy-flutter\windows\scripts\prepare_dependencies" debug [C:\Users\Jay\projects\glossy-flutter\windows\Runner.vcxproj]
[        ] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(128,5): error MSB3073: :VCEnd" exited with code 1. [C:\Users\Jay\projects\glossy-flutter\windows\Runner.vcxproj]
[        ]     0 Warning(s)
[        ]     1 Error(s)
[        ] Time Elapsed 00:00:02.42
[  +16 ms] Building Windows application... (completed in 3.8s)
[   +2 ms] "flutter run" took 4,246ms.
[        ] "flutter run" took 4,246ms.
Build process failed
</code>
</details>

**Development Environment (please complete the following information):**
* OS: Windows 10
* Developer tools version (Xcode, Visual Studio, or gcc): MS Visual Studio Community 2019 16.1.1

**Doctor Output**
For build issues, please provide the output of `flutter doctor -v`:
```
$ flutter doctor -v
[√] Flutter (Channel master, v1.6.7-pre.30, on Microsoft Windows [Version 10.0.17763.557], locale en-US)
    • Flutter version 1.6.7-pre.30 at C:\Users\Jay\tools\flutter
    • Framework revision fa3fbc89a3 (3 weeks ago), 2019-05-30 10:03:31 -0700
    • Engine revision 58eff77ef2
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 fee615c5a5)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Jay\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    X Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] Connected device (1 available)
    • Windows • Windows • windows-x64 • Microsoft Windows [Version 10.0.17763.557]
```
Likely as easy as parsing and using that parameter in the script (I don't know windows dev so haven't looked).

Cheers!

**Comment by stuartmorgan** [comment]
`flutter` tool support for `--target` was never wired up for desktop. Coincidentally there's a PR that adds it already reviewed and waiting for presubmits though: https://github.com/flutter/flutter/pull/34660

If you still see issues after that PR lands, please file a bug in the Flutter bug tracker (the relevant code is within the `flutter` tool, not code in this repository).

> I don't know windows dev so haven't looked

The `flutter` tool is written in Dart, FWIW.

**Comment by jaysephjw** [comment]
thanks!
