### ISSUE TITLE
[MacOS] Flutter view is not rebuild after a screen density change

### ISSUE THREAD

**Issue by rxlabz** [google/flutter-desktop-embedding#439]
On MacOS, when I move my app between two screens with different densities ( retina to non retina ), the UI is not automatically rebuild.
Things get back to normal only after manually resizing the app window. 

Doctor summary
[✓] Flutter (Channel dev, v1.7.8, on Mac OS X 10.14.5 18F132, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.4)
[✓] Connected device (3 available)

**Comment by stuartmorgan** [comment]
This is an issue in the framework, not the FDE runner. Filed https://github.com/flutter/flutter/issues/35095 to track.
