### ISSUE TITLE
Can not find macOS device after update flutter to 1.8.0

### ISSUE THREAD

**Issue by zhouweidong** [google/flutter-desktop-embedding#443]
I can run a desktop application successful on macOS. but after update flutter version, Now I can not find device for macOS.

bogon:example zhouweidong$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.8.0, on Mac OS X 10.14.4 18E226, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.3)
[!] IntelliJ IDEA Ultimate Edition (version 2017.2.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

bogon:example zhouweidong$ printenv
FLUTTER_HOME=/Users/zhouweidong/flutter/flutter
rvm_bin_path=/Users/zhouweidong/.rvm/bin
GEM_HOME=/Users/zhouweidong/.rvm/gems/ruby-2.3.0
TERM=xterm-256color
SHELL=/bin/bash
IRBRC=/Users/zhouweidong/.rvm/rubies/ruby-2.3.0/.irbrc
TMPDIR=/var/folders/gl/08d7x5qs1bg51m22z8mmvtkh0000gn/T/
GRADLE_HOME=/Applications/Android Studio.app/Contents/gradle/gradle-4.10.1
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.avQKM0eaKi/Render
MY_RUBY_HOME=/Users/zhouweidong/.rvm/rubies/ruby-2.3.0
rvm_stored_umask=0022
USER=zhouweidong
LD_LIBRARY_PATH=/Users/zhouweidong/torch/install/lib:
_system_type=Darwin
rvm_path=/Users/zhouweidong/.rvm
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.ugmvHxpsy8/Listeners
PUB_HOSTED_URL=https://pub.flutter-io.cn
__CF_USER_TEXT_ENCODING=0x1F5:0x19:0x34
ENABLE_FLUTTER_DESKTOP=true
……

bogon:example zhouweidong$ flutter devices
No devices detected.

Run 'flutter emulators' to list and start any available device emulators.

Or, if you expected your device to be detected, please run "flutter doctor" to diagnose potential issues, or visit https://flutter.dev/setup/ for troubleshooting tips.

**Comment by stuartmorgan** [comment]
In the future, please file issues with the `flutter` tool itself in the Flutter issue tracker, not here.

This was an intentional change; see https://github.com/flutter/flutter/pull/35221. You need to be on the master branch (as described in this project's README), and your `doctor` output shows `dev`.
