### ISSUE TITLE
[linux] Makefile doesn't handle spaces in Flutter path

### ISSUE THREAD

**Issue by sachinkum0009** [google/flutter-desktop-embedding#446]
flutter run is not working for desktop in ubuntu 16.04. I am using a master channel of flutter and clone the git repository of example and when I try "flutter run". I get an error "Build Process failed". The error is related to Makefile.

```
flutter run
Launching lib/main.dart on Linux in debug mode...
Makefile:107: warning: overriding recipe for target '/home/hunter/Android'
Makefile:100: warning: ignoring old recipe for target '/home/hunter/Android'
Makefile:107: warning: overriding recipe for target 'Developer/Flutter' 
Makefile:100: warning: ignoring old recipe for target 'Developer/Flutter'
Makefile:111: warning: overriding recipe for target '/home/hunter/Android'
Makefile:107: warning: ignoring old recipe for target '/home/hunter/Android'
Makefile:111: warning: overriding recipe for target 'Developer/Flutter' 
Makefile:107: warning: ignoring old recipe for target 'Developer/Flutter'
make: Circular /home/hunter/Android <- /home/hunter/Android dependency dropped.
make: Circular Developer/Flutter <- /home/hunter/Android dependency dropped.
make: Circular Developer/Flutter <- Developer/Flutter dependency dropped.
cp: target                                                              
'Mobile/flutter-desktop-embedding/example/linux/../build/linux/debug/data/icudtl
.dat' is not a directory
make: *** [Developer/Flutter] Error 1                                   
Building Linux application...                                           
Build process failed
```

**Comment by stuartmorgan** [comment]
I'm guessing from the output that you have installed flutter in a directory called `/home/hunter/Android Developer/Flutter`?

Make does very poorly with spaces in paths. We should try to make it handle this if possible, but the simple solution in the short term would be to not have spaces in your installation path. (Generally speaking, it's a bad idea to use spaces in paths on Linux.)

**Comment by SACHINKUMARHACKER** [comment]
Thank you for your suggestion I would definitely correct this.

**Comment by codenoid** [comment]
how

**Comment by SACHINKUMARHACKER** [comment]
The problem was that there were spaces in the path defined for the flutter. That's why I got up this error.
BTW why did you reopened the issue?

**Comment by codenoid** [comment]
not me, i'm just askin how was this going, any PR yet ?

**Comment by stuartmorgan** [comment]
@SACHINKUMARHACKER I reopened it because it is a bug that should be fixed if possible, even if there is a workaround.

**Comment by SACHINKUMARHACKER** [comment]
Any Idea how can we fix this problem.

**Comment by stuartmorgan** [comment]
The most robust solution would be to eliminate any possibility of spaces in any variable used in dependency analysis. At least some of the initial errors here should already be fixed now that `assemble` is putting all the Flutter files we need into `flutter/emphemeral`, so thing like `icudtl.dat` are just relative paths.

All use of `abspath` needs to be replaced, which means among other things a different construction will be needed for objfile paths. That may be tricky to get the rule right for.

**Comment by msarkrish** [comment]
> I'm guessing from the output that you have installed flutter in a directory called `/home/hunter/Android Developer/Flutter`?
> 
> Make does very poorly with spaces in paths. We should try to make it handle this if possible, but the simple solution in the short term would be to not have spaces in your installation path. (Generally speaking, it's a bad idea to use spaces in paths on Linux.)



> I'm guessing from the output that you have installed flutter in a directory called `/home/hunter/Android Developer/Flutter`?
> 
> Make does very poorly with spaces in paths. We should try to make it handle this if possible, but the simple solution in the short term would be to not have spaces in your installation path. (Generally speaking, it's a bad idea to use spaces in paths on Linux.)

I'm having space in project location and now i solved.

**Comment by stuartmorgan** [comment]
Closing, as this will be obsoleted by https://github.com/flutter/flutter/issues/52751.
