### ISSUE TITLE
[Macos] Crash on launch

### ISSUE THREAD

**Issue by iamsabet** [google/flutter-desktop-embedding#447]
hi im having a trouble running flutter desktop on mac os 
flutter master version 
this is what happens : 

> build successful but application crashes on launch 

<img width="964" alt="Screen Shot 2019-07-06 at 1 41 00 PM" src="https://user-images.githubusercontent.com/20267993/60754260-e3d88d00-9ff3-11e9-915b-4361b6725f42.png">

* OS: 
> Mac os 10.14 , Xcode 10.2.1

**Doctor Output**

<img width="1158" alt="Screen Shot 2019-07-06 at 1 02 05 PM" src="https://user-images.githubusercontent.com/20267993/60753891-4fb7f700-9fee-11e9-8440-27758aaf8f6e.png">

i appreciate your help 
@stuartmorgan

**Comment by iamsabet** [comment]
so i opened macos folder with xcode and run it and got this 

<img width="1423" alt="Screen Shot 2019-07-06 at 2 13 29 PM" src="https://user-images.githubusercontent.com/20267993/60754581-5c414d00-9ff8-11e9-8fd9-b76b3db86073.png">

<img width="1097" alt="Screen Shot 2019-07-06 at 2 15 53 PM" src="https://user-images.githubusercontent.com/20267993/60754597-96aaea00-9ff8-11e9-8b60-249609d18980.png">


> looks like memory leak or something i do not understand totally

**Comment by stuartmorgan** [comment]
This is a regression from https://github.com/flutter/engine/pull/9655; will be fixed by https://github.com/flutter/engine/pull/9697

**Comment by stuartmorgan** [comment]
(Until that lands, a0c47e2216a2b50b70c478001cf5652f31a783af is the last Flutter commit that will work with FDE.)

**Comment by iamsabet** [comment]
Thanks a lot @stuartmorgan dude , that was the case

**Comment by stuartmorgan** [comment]
The engine fix has rolled into Flutter, so it's now safe to update to the latest master again.
