### ISSUE TITLE
How to build exe？

### ISSUE THREAD

**Issue by YourksChan** [google/flutter-desktop-embedding#448]

**Comment by stuartmorgan** [comment]
https://github.com/google/flutter-desktop-embedding#setting-up

If you are following the project's instructions and having issues, you'll need to provide details about what you are doing and what is failing.

**Comment by ankitsdglobal** [comment]
First check the build options with - flutter build -h

Then run flutter build windows

Then you can find the build in the following path- \build\windows\x64\Release\Runner

Although it is created in the release folder it is still just a debug build.
