### ISSUE TITLE
[Missing file] fatal error: flutter/flutter_window_controller.h: No such file or directory

### ISSUE THREAD

**Issue by Minabsapi** [google/flutter-desktop-embedding#456]
Hello, 
I tried to compile and run `flutter_embedder_example.cpp` (for Windows), but I get an error:
``fatal error: flutter/flutter_window_controller.h: No such file or directory``
This error is due to a file, `flutter_window_controller.h`, that's missing. But there's no mention of where it is supposed to be found.
It's not present locally in a folder of this branch, nor installed as a library for any compiler. And I didn't find any flutter doc mentioning the installation of a C++ flutter library.
What am I supposed to do ?
Thanks in advance.

**Comment by stuartmorgan** [comment]
That file is part of the C++ wrapper that's cached with the Flutter library. Did you use `flutter run` to build, per the README?

**Comment by Minabsapi** [comment]
Thanks for the fast reply !
Seems like I missed this part, I actually flied over the README without reading much deeply, I'm sorry.
Just tried, I got the following output
``No connected devices.``
Looks like it's waiting for an Android device or something, while it is supposed to be directly running on the computer. Unless I missed something again.

**Comment by stuartmorgan** [comment]
Did you follow [the setup instructions](https://github.com/google/flutter-desktop-embedding#setting-up)?

**Comment by Minabsapi** [comment]
Reread and I don't see any particular step I would have missed. Ran ``flutter doctor`` to detect potential problems and no major issues were found.
In the meantime I launched an upgrade to flutter -- That I thought was already on the latest version. Will tell you if it fixed something.

**Comment by stuartmorgan** [comment]
If it's still not working please provide the output from `flutter doctor -v`

**Comment by Minabsapi** [comment]
Upgrade completed, and still the same result
Ouput from flutter doctor -v:
```
[ÔêÜ] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [version 6.1.7601], locale fr-FR)
    ÔÇó Flutter version 1.7.8+hotfix.3 at C:\Dev\flutter_v1.5.4
    ÔÇó Framework revision b712a172f9 (2 days ago), 2019-07-09 13:14:38 -0700
    ÔÇó Engine revision 54ad777fd2
    ÔÇó Dart version 2.4.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ÔÇó Android SDK at C:\Users\User\AppData\Local\Android\sdk
    ÔÇó Android NDK location not configured (optional; useful for native profiling support)
    ÔÇó Platform android-28, build-tools 28.0.3
    ÔÇó ANDROID_HOME = C:\Users\User\AppData\Local\Android\sdk
    ÔÇó Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    ÔÇó Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (version 3.3)
    ÔÇó Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    ÔÇó Dart plugin version 182.5215
    ÔÇó Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

**Comment by stuartmorgan** [comment]
> Channel stable, v1.7.8+hotfix.3

Per the instructions I linked to above, you must be on the master channel; you are on the stable channel. See also https://github.com/flutter/flutter/wiki/Desktop-shells#tooling

**Comment by Minabsapi** [comment]
Alright, thanks for your help !
