### ISSUE TITLE
Building Version with prereqs included

### ISSUE THREAD

**Issue by xeu100** [google/flutter-desktop-embedding#463]
Hey, I'm wondering if a version can be built that doesn't require the Visual Studio reqs, with the DLLs included and such. I need to test the app on another machine for compatibility but it can't run Visual Studio. Any suggestions?

**Comment by stuartmorgan** [comment]
Please use the mailing list, not the bug tracker, for questions, as requested in the project README.

This [came up recently there](https://groups.google.com/d/msg/flutter-desktop-embedding-dev/xqsDSL4gl6s/-5-M9jBbBgAJ), so that message may answer your question.
