### ISSUE TITLE
Build Error VS 2019 -  Wrong full snapshot version, expected '1d7acad1540192ac459cf60344efb7c1' found '34948253b59d5a56b2ec161e17975a4e'

### ISSUE THREAD

**Issue by diegomgarcia** [google/flutter-desktop-embedding#465]
Hi guys I'm getting the build error when trying to run the example...

I've done the follow steps:

1- git clone flutter
2- add path to enviroment variables (flutter\bin)
3- changed the to master. flutter channel master
4- flutter upgrade
5- git clone https://github.com/google/flutter-desktop-embedding.git
6- cd into example folder
7- flutter package get
8- flutter run -v

I've installed previously installed visual studio with all windows sdks...
I've tried to chande the dart sdk version, but it didnt work out ...

And here is the log after flutter run:

[ +1 ms] | example_flutter:lib/
[ +26 ms] Running "flutter pub get" in example... (completed in 4,2s)
[ +240 ms] Launching lib\main.dart on Windows in debug mode...
[ +99 ms] Building Windows application...
[ +218 ms]

[ +1 ms] ** Visual Studio 2019 Developer Command Prompt v16.2.0
[ ] ** Copyright (c) 2019 Microsoft Corporation
[ ]

[ +985 ms] [vcvarsall.bat] Environment initialized for: 'x64'
[ +91 ms] Microsoft(R) Build Engine versÃ£o 16.2.32702+c4012a063 para .NET
Framework
[ ] Copyright (C) Microsoft Corporation. Todos os direitos reservados.
[ +14 ms] Compilando os projetos desta soluÃ§Ã£o um por vez. Para habilitar o
build paralelo, adicione a opÃ§Ã£o "-m".
[ +241 ms] CompilaÃ§Ã£o de 28/07/2019 00:32:27 iniciada.
[ +718 ms] Projeto
"C:\Files\flutter-desktop-embedding-master\example\windows\Runner.sln" no nÃ³ 1
(destinos padrÃ£o).
[ +14 ms] ValidateSolutionConfiguration:
[ ] Compilando a configuraÃ§Ã£o de soluÃ§Ã£o "Debug|x64".
[ +513 ms] O projeto
"C:\Files\flutter-desktop-embedding-master\example\windows\Runner.sln" (1) estÃ¡

compilando
"C:\Files\flutter-desktop-embedding-master\example\windows\Runner.vcxproj" (2)
no nÃ³ 1 (destinos padrÃ£o).
[ +2 ms] InitializeBuildStatus:
[ ] Tocando
"C:\Files\flutter-desktop-embedding-master\example\windows..\build\windows\inte

rmediates\x64\Debug\Runner\Runner.tlog\unsuccessfulbuild".
[ +2 ms] PreBuildEvent:
[ +12 ms] Sync and build dependencies
[ +6 ms]
"C:\Files\flutter-desktop-embedding-master\example\windows\scripts\prepare_depen

dencies" debug
[ +6 ms] :VCEnd

Wrong full snapshot version, expected '1d7acad1540192ac459cf60344efb7c1' found '34948253b59d5a56b2ec161e17975a4e'

C:\Files\flutter-desktop-embedding-master\example\lib\main.dart
[ +22 ms] C:\Program Files (x86)\Microsoft Visual
Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(128,

5): error MSB3073: O comando
""C:\Files\flutter-desktop-embedding-master\example\windows\scripts\prepare_depe

ndencies" debug
[C:\Files\flutter-desktop-embedding-master\example\windows\Runner.vcxproj]
[ +1 ms] C:\Program Files (x86)\Microsoft Visual
Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(128,

5): error MSB3073: :VCEnd" foi encerrado com o c├│digo 1.
[C:\Files\flutter-desktop-embedding-master\example\windows\Runner.vcxproj]
[ +5 ms] Projeto de compila├º├úo pronto
"C:\Files\flutter-desktop-embedding-master\example\windows\Runner.vcxproj"
(destinos padr├úo) -- FALHA.
[ +19 ms] Projeto de compila├º├úo pronto
"C:\Files\flutter-desktop-embedding-master\example\windows\Runner.sln" (destinos

padr├úo) -- FALHA.
[ +26 ms] FALHA da compila├º├úo.
[ +4 ms]
"C:\Files\flutter-desktop-embedding-master\example\windows\Runner.sln" (destinopadr├úo) (1) ->
[ +1 ms]
"C:\Files\flutter-desktop-embedding-master\example\windows\Runner.vcxproj"
(destino padr├úo) (2) ->
[ +1 ms] (PreBuildEvent destino) ->
[ ] C:\Program Files (x86)\Microsoft Visual
Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(128,5): error MSB3073: O comando ""C:\Files\flutter-desktop-embedding-master\example\windows\scripts\prepare_dependencies" debug
[C:\Files\flutter-desktop-embedding-master\example\windows\Runner.vcxproj]
[ +2 ms] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(128,

**Comment by clarkezone** [comment]
Are you on the master branch of flutter?

**Comment by diegomgarcia** [comment]
Yeap, I've updated with the steps I've done after accidentally posted just
the title of the problem.

Em dom, 28 de jul de 2019 00:58, James Clarke <notifications@github.com>
escreveu:

**Comment by stuartmorgan** [comment]
That message is coming from Flutter (or more specifically the Flutter-bundled Dart, I believe), not the FDE, layer, so it's out of the scope of this project. I can't suggest anything other than trying the various steps (cache removal, aggressive `git clean`, etc.) that people list in the Flutter bug that you've already found.

**Comment by diegomgarcia** [comment]
@stuartmorgan I was thinking that to but I couldnt figure it out how to solve it, I've performed all the steps mentioned to cleanup caches, revert git, forced remove all, clear pub cache, manually deleted the appdata/roaming/pub dir. But it keeps getting the same error ... 

Will try some more things, maybe changing the dart version until find the one that works with...

Please if some of you has any tips, comment it here.

**Comment by diegomgarcia** [comment]
hey guys just to update this for anyone have problem, I've fully removed flutter, pub caches from AppData and everything and started over direct with git clone -b master https://github.com/flutter/flutter.git

It seems that cloning from stable and changing to master doesnt updates the dart-sdk version and put us on this error. 

performing the clone directly from the master branch solves this issue.

Regards,
Diego Garcia

**Comment by stuartmorgan** [comment]
> It seems that cloning from stable and changing to master doesnt updates the dart-sdk version

This is not true in general. If it didn't happen for you then something unusual went wrong during the update (and the fact that it wasn't automatically caught/recovered would presumably be a Flutter tooling bug).
