### ISSUE TITLE
Stop using internal system channel for text input handling

### ISSUE THREAD

**Issue by stuartmorgan** [google/flutter-desktop-embedding#47]
The current text input plugin is based on implementation details of the engine that are not public/stable API. Once there's a clearly defined text input API for embedders we need to switch to using that instead of the current unsupported approach.

**Comment by krisgiesing** [comment]
Can you elaborate on which specific implementation details of the engine are relevant?

**Comment by stuartmorgan** [comment]
My understanding is that essentially everything in the text input system as currently implemented: the platform channel names of the messages the plugin handles, the keys and structures in the response objects, and in general the whole concept of implementing text input through the generic platform messaging system rather than a formal API.

**Comment by krisgiesing** [comment]
Ah, I think you mean "framework" then rather than "engine"? That is, these are Dart constructs we're referencing, not C/C++ constructs.

**Comment by stuartmorgan** [comment]
Closing; this is a non-issue now that the shells are part of flutter/engine. (There should probably still be a solution to this for other embedders, but that's no longer in scope for the desktop work.)
