### ISSUE TITLE
你好，我想问一下怎么自定义标题。

### ISSUE THREAD

**Issue by zxqSmile** [google/flutter-desktop-embedding#471]
我想问一下，怎么自定义标题栏。窗口的标题栏图标，我不知道怎么换。

**Comment by stuartmorgan** [comment]
If this is on macOS, you change the title by editing the XIB. If it's on Windows or Linux, you would call `FlutterDesktopWindowSetTitle` and/or `FlutterDesktopWindowSetIcon` in your runner.

In the future, please using the mailing list for questions.

**Comment by zxqSmile** [comment]
thanks, my english is terrible! so,i ask you for question that use english or chinese?




------------------ 原始邮件 ------------------
发件人: "stuartmorgan"<notifications@github.com>; 
发送时间: 2019年8月1日(星期四) 中午1:32
收件人: "google/flutter-desktop-embedding"<flutter-desktop-embedding@noreply.github.com>; 
抄送: "1723544852"<1723544852@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [google/flutter-desktop-embedding] 你好，我想问一下怎么自定义标题。 (#471)




If this is on macOS, you change the title by editing the XIB. If it's on Windows or Linux, you would call FlutterDesktopWindowSetTitle and/or FlutterDesktopWindowSetIcon in your runner.
 
In the future, please using the mailing list for questions.

**Comment by zxqSmile** [comment]
我指向传递一个文件路径，然后就改变图标。



这是我的图标地址，因为在run方法中



你的data地址已经设置了，所以我的相对路径是images/icon/ic_launcher.png。
我可以只传递，这个相对路径获取 uint8_t* 对象吗
。
因为我一直是使用java开发的，所以我不知道怎么转换.
你能写下如何设置图片的代码，然后截图给我吗，非常感谢！








------------------ 原始邮件 ------------------
发件人: "stuartmorgan"<notifications@github.com>; 
发送时间: 2019年8月1日(星期四) 中午1:32
收件人: "google/flutter-desktop-embeddin"<flutter-desktop-embedding@noreply.github.com>; 
抄送: "1723544852"<1723544852@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [google/flutter-desktop-embedding] 你好，我想问一下怎么自定义标题。 (#471)




If this is on macOS, you change the title by editing the XIB. If it's on Windows or Linux, you would call FlutterDesktopWindowSetTitle and/or FlutterDesktopWindowSetIcon in your runner.
 
In the future, please using the mailing list for questions.

**Comment by zxqSmile** [comment]
窗口能固定大小吗?

我不想让用户改变它的尺寸！






------------------ 原始邮件 ------------------
发件人: "stuartmorgan"<notifications@github.com>; 
发送时间: 2019年8月1日(星期四) 中午1:32
收件人: "google/flutter-desktop-embeddin"<flutter-desktop-embedding@noreply.github.com>; 
抄送: "1723544852"<1723544852@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [google/flutter-desktop-embedding] 你好，我想问一下怎么自定义标题。 (#471)




If this is on macOS, you change the title by editing the XIB. If it's on Windows or Linux, you would call FlutterDesktopWindowSetTitle and/or FlutterDesktopWindowSetIcon in your runner.
 
In the future, please using the mailing list for questions.

**Comment by stuartmorgan** [comment]
> 你的data地址已经设置了，所以我的相对路径是images/icon/ic_launcher.png。
我可以只传递，这个相对路径获取 uint8_t* 对象吗

The API takes image data, not a file path. How you create that data, whether it's loading from a file or some other way, is up to you.

> 因为我一直是使用java开发的，所以我不知道怎么转换.
你能写下如何设置图片的代码，然后截图给我吗，非常感谢！

If you need help learning how to load image data from a file in C++, I recommend posting a question on StackOverflow.

**Comment by zxqSmile** [comment]
好的，十分感谢。不过，我想面临这个问题的，可能不仅仅我一个。和我水平类似，停留在应用层的程序员。应该都会有相同的苦恼。

还是希望，您能来开发一个接口，让我们直接传递图片路径，就可以设置ICON。




------------------ 原始邮件 ------------------
发件人: "stuartmorgan"<notifications@github.com>; 
发送时间: 2019年8月1日(星期四) 晚上9:31
收件人: "google/flutter-desktop-embeddin"<flutter-desktop-embedding@noreply.github.com>; 
抄送: "1723544852"<1723544852@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [google/flutter-desktop-embedding] 你好，我想问一下怎么自定义标题。 (#471)



 
你的data地址已经设置了，所以我的相对路径是images/icon/ic_launcher.png。
 我可以只传递，这个相对路径获取 uint8_t* 对象吗
  
The API takes image data, not a file path. How you create that data, whether it's loading from a file or some other way, is up to you.
  
因为我一直是使用java开发的，所以我不知道怎么转换.
 你能写下如何设置图片的代码，然后截图给我吗，非常感谢！
  
If you need help learning how to load image data from a file in C++, I recommend posting a question on StackOverflow.

**Comment by stuartmorgan** [comment]
The GLFW embedding is a placeholder, as described at flutter.dev/desktop. None of these APIs will be part of an eventual stable release of Flutter for desktop.

I agree that setting the icon is currently non-trivial for someone without C++ experience, but people without any C++ experience aren't the expected audience for early experimentation with something that isn't even at an alpha stage.

**Comment by zxqSmile** [comment]
好吧，我理解你的意思了。加油，期代未来的flutter框架，它一定能改善我们这群c/s开发程序员的尴尬地位。






------------------ 原始邮件 ------------------
发件人: "stuartmorgan"<notifications@github.com>; 
发送时间: 2019年8月2日(星期五) 上午10:56
收件人: "google/flutter-desktop-embeddin"<flutter-desktop-embedding@noreply.github.com>; 
抄送: "1723544852"<1723544852@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [google/flutter-desktop-embedding] 你好，我想问一下怎么自定义标题。 (#471)




The GLFW embedding is a placeholder, as described at flutter.dev/desktop. None of these APIs will be part of an eventual stable release of Flutter for desktop.
 
I agree that setting the icon is currently non-trivial for someone without C++ experience, but people without any C++ experience aren't the expected audience for early experimentation with something that isn't even at an alpha stage.
