### ISSUE TITLE
Build errors with Visual Studio 2012

### ISSUE THREAD

**Issue by Tumbler0809** [google/flutter-desktop-embedding#473]
Log
---------------------------------------flutter run --verbose-------------------------------------
```
C:\src\flutter-desktop-embedding\example>flutter run --verbose
[  +22 ms] executing: [C:\src\flutter\] git log -n 1 --pretty=format:%H
[  +65 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] e6dc6a8b5f26cb2092257da07fc1d1818e4b4cce
[        ] executing: [C:\src\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +54 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.8.3-52-ge6dc6a8b5
[   +8 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +46 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/master
[        ] executing: [C:\src\flutter\] git ls-remote --get-url origin
[  +40 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[  +77 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref HEAD
[  +39 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] master
[ +113 ms] executing: C:\Users\Orion\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[  +27 ms] Exit code 0 from: C:\Users\Orion\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
[  +23 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[ +123 ms] Launching lib\main.dart on Windows in debug mode...
[  +82 ms] Building Windows application...
[ +121 ms] \nodejs\node_global";C:\src\flutter\bin;;C:\src\flutter\bin\mingit\cmd" was unexpected at this time.
[  +15 ms] Building Windows application... (completed in 0.1s)
[   +3 ms] "flutter run" took 571ms.
Build process failed

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildWindows (package:flutter_tools/src/windows/build_windows.dart:84:5)
<asynchronous suspension>
#2      WindowsDevice.startApp (package:flutter_tools/src/windows/windows_device.dart:85:13)
<asynchronous suspension>
#3      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:379:54)
<asynchronous suspension>
#4      HotRunner.run (package:flutter_tools/src/run_hot.dart:247:39)
<asynchronous suspension>
#5      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:473:37)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#8      _rootRunUnary (dart:async/zone.dart:1132:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#13     Future._complete (dart:async/future_impl.dart:473:7)
#14     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#15     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#16     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#17     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#18     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#19     _rootRunUnary (dart:async/zone.dart:1132:38)
#20     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#21     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#22     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#23     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#24     Future._complete (dart:async/future_impl.dart:473:7)
#25     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#26     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#27     _rootRun (dart:async/zone.dart:1120:38)
#28     _CustomZone.run (dart:async/zone.dart:1021:19)
#29     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#30     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#34     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#35     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#36     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#37     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```
-----------------------------------------------------flutter doctor -v----------------------------
```
C:\src\flutter-desktop-embedding\example>flutter doctor -v
[√] Flutter (Channel master, v1.8.4-pre.52, on Microsoft Windows [Version 10.0.17134.885], locale zh-CN)
    • Flutter version 1.8.4-pre.52 at C:\src\flutter
    • Framework revision e6dc6a8b5f (3 hours ago), 2019-08-01 10:29:06 +0200
    • Engine revision b41c172bcd
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 bd049f5b53)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Orion\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Orion\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.2.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.2.29123.88

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.36.1)
    • VS Code at C:\Users\Orion\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.2.0

[√] Connected device (1 available)
    • Windows • Windows • windows-x64 • Microsoft Windows [Version 10.0.17134.885]

• No issues found!
```
--------------------------------

**Comment by stuartmorgan** [comment]
> \nodejs\node_global";C:\src\flutter\bin;;C:\src\flutter\bin\mingit\cmd" was unexpected at this time.

This looks like part of a path variable, but it's not clear to where this message is coming from. The next output at this point should have been from `vcvars` though, suggest that's what failed.

What happens if you run `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliar\Buildvcvars64.bat` in a console?

**Comment by Tumbler0809** [comment]
There is no Buildvcvars64.bat under the directory.

**Comment by stuartmorgan** [comment]
There was a missing slash in the path; I've updated the comment to fix it.

**Comment by Tumbler0809** [comment]
I have installed Visual Studio 2019, but Flutter can't find it.

**Comment by Tumbler0809** [comment]
I have configured it in the environment variable  “C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build”

**Comment by Tumbler0809** [comment]
C:\src\flutter-desktop-embedding\example>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.8.4-pre.66, on Microsoft Windows [Version 10.0.17134.885], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.2.0)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
      development with C++" workload, and include these components:
        MSBuild
        MSVC v142 - VS 2019 C++ x64/x86 build tools (v14.21)
        Windows 10 SDK (10.0.17763.0)
[√] Android Studio (version 3.4)
[√] VS Code (version 1.36.1)
[√] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by stuartmorgan** [comment]
> I have installed Visual Studio 2019, but Flutter can't find it.

I'm not sure how you came to that conclusion, since your `flutter doctor` output is showing that it has located your Visual Studio installation, and your build error is not the result of Flutter being unable to locate Visual Studio.

Could you respond to my initial question about running vcvars64.bat manually please?

**Comment by Tumbler0809** [comment]
I uninstalled Visual Studio and reinstalled it

**Comment by Tumbler0809** [comment]
This is the latest log
----------------------------------------------------------------------------------------------------
C:\Users\Orion>flutter channel master
Switching to flutter channel 'master'...
git: From https://github.com/flutter/flutter
git:    18418dffd..84fe2aded  master     -> origin/master
git: Your branch is behind 'origin/master' by 1 commit, and can be fast-forwarded.
git:   (use "git pull" to update your local branch)
git: Already on 'master'

C:\Users\Orion>flutter upgrade
Upgrading Flutter from C:\src\flutter...
Updating e4ebcdf6f..84fe2aded
 .../ios_host_app/Flutter/.gitkeep                  |   0
 247 files changed, 8880 insertions(+), 2470 deletions(-)

Upgrading engine...
Building flutter tool...
Running pub upgrade...

Flutter 1.8.4-pre.66 • channel master • https://github.com/flutter/flutter.git
Framework • revision 18418dffda (33 minutes ago) • 2019-08-01 20:04:49 -0700
Engine • revision eac7ef065d
Tools • Dart 2.5.0 (build 2.5.0-dev.1.0 bd049f5b53)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.8.4-pre.67, on Microsoft Windows [Version 10.0.17134.885], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] VS Code (version 1.36.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

C:\Users\Orion>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.8.4-pre.67, on Microsoft Windows [Version 10.0.17134.885], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] VS Code (version 1.36.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

C:\Users\Orion>set ENABLE_FLUTTER_DESKTOP=true

C:\Users\Orion>flutter devices
1 connected device:

Windows • Windows • windows-x64 • Microsoft Windows [Version 10.0.17134.885]

C:\Users\Orion>cd C:\src\flutter-desktop-embedding\example

C:\src\flutter-desktop-embedding\example>flutter packages get
Running "flutter pub get" in example...                             0.5s

C:\src\flutter-desktop-embedding\example>flutter precache --windows

C:\src\flutter-desktop-embedding\example>flutter run
Launching lib\main.dart on Windows in debug mode...
Unable to find suitable Visual Studio toolchain. Please run `flutter doctor` for more details.

C:\src\flutter-desktop-embedding\example>

**Comment by Tumbler0809** [comment]
C:\src\flutter-desktop-embedding\example>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.8.4-pre.67, on Microsoft Windows [Version 10.0.17134.885], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.2.0)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
      development with C++" workload, and include these components:
        MSBuild
        MSVC v142 - VS 2019 C++ x64/x86 build tools (v14.21)
        Windows 10 SDK (10.0.17763.0)
[√] Android Studio (version 3.4)
[√] VS Code (version 1.36.1)
[√] Connected device (1 available)

! Doctor found issues in 1 category.

C:\src\flutter-desktop-embedding\example>

**Comment by Tumbler0809** [comment]
Why can't I find Visual Studio, I obviously have it installed?

**Comment by Tumbler0809** [comment]
Vcvars64.bat flashback without any reaction

**Comment by stuartmorgan** [comment]
Please post only the relevant commands and output, not your entire terminal history relating to setup. (Also, based on the commands you are running you don't appear to be following this project's README; if you want to use this project successfully, please read its README and use those instructions, not instructions that come from somewhere else and are not necessarily accurate.)

> Why can't I find Visual Studio, I obviously have it installed?

It can find Visual Studio, which is why `flutter doctor` is listing a version. But your VS installation isn't usable by Flutter, which is why `flutter doctor` is reporting an error and telling you what you need to install.

**Comment by stuartmorgan** [comment]
> Vcvars64.bat flashback without any reaction

I don't understand what this means. Please provide the output that was printed when you ran it.

**Comment by Tumbler0809** [comment]
C:\src\flutter-desktop-embedding\example>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.8.4-pre.67, on Microsoft Windows [Version 10.0.17134.885], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.2.0)
[√] Android Studio (version 3.4)
[√] VS Code (version 1.36.1)
[√] Connected device (1 available)

• No issues found!

C:\src\flutter-desktop-embedding\example>flutter run
Launching lib\main.dart on Windows in debug mode...
\nodejs\node_global";C:\src\flutter\bin;C:\Program Files (x86)\Microsoft Visual
Studio\2019\Community\VC\Auxiliary\Build;;C:\src\flutter\bin\mingit\cmd" was unexpected at this time.
Building Windows application...
Build process failed. To view the stack trace, please run `flutter run -d windows -v`.

C:\src\flutter-desktop-embedding\example>flutter run -d windows -v
[  +21 ms] executing: [C:\src\flutter\] git log -n 1 --pretty=format:%H
[  +72 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 84fe2adedb52b4ba85f99b5ab84e57f353f19a33
[        ] executing: [C:\src\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +55 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.8.3-67-g84fe2aded
[   +8 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +45 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/master
[        ] executing: [C:\src\flutter\] git ls-remote --get-url origin
[  +41 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[  +76 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref HEAD
[  +40 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] master
[ +107 ms] executing: C:\Users\Orion\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[  +26 ms] Exit code 0 from: C:\Users\Orion\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[   +1 ms] List of devices attached
[  +22 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[ +126 ms] Launching lib\main.dart on Windows in debug mode...
[  +82 ms] Building Windows application...
[ +128 ms] \nodejs\node_global";C:\src\flutter\bin;C:\Program Files (x86)\Microsoft Visual
                    Studio\2019\Community\VC\Auxiliary\Build;;C:\src\flutter\bin\mingit\cmd" was unexpected at this
time.
[  +15 ms] Building Windows application... (completed in 0.1s)
[   +3 ms] "flutter run" took 575ms.
Build process failed. To view the stack trace, please run `flutter run -d windows -v`.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildWindows (package:flutter_tools/src/windows/build_windows.dart:84:5)
<asynchronous suspension>
#2      WindowsDevice.startApp (package:flutter_tools/src/windows/windows_device.dart:85:13)
<asynchronous suspension>
#3      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:379:54)
<asynchronous suspension>
#4      HotRunner.run (package:flutter_tools/src/run_hot.dart:247:39)
<asynchronous suspension>
#5      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:473:37)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#8      _rootRunUnary (dart:async/zone.dart:1132:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#13     Future._complete (dart:async/future_impl.dart:473:7)
#14     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#15     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#16     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#17     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#18     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#19     _rootRunUnary (dart:async/zone.dart:1132:38)
#20     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#21     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#22     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#23     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#24     Future._complete (dart:async/future_impl.dart:473:7)
#25     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#26     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#27     _rootRun (dart:async/zone.dart:1120:38)
#28     _CustomZone.run (dart:async/zone.dart:1021:19)
#29     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#30     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#34     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#35     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#36     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#37     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

**Comment by stuartmorgan** [comment]
This is basically the first error again, which means I still need an answer to my original question.

**Comment by Tumbler0809** [comment]
C:\src\flutter-desktop-embedding\example>"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
此时不应有 \nodejs\node_global";C:\src\flutter\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build;"。

C:\src\flutter-desktop-embedding\example>

**Comment by stuartmorgan** [comment]
That confirms that the error you are seeing is coming from your VS toolchain. You'll need to resolve that; it's outside the scope of Flutter.
