### ISSUE TITLE
[macOS] Release builds fail

### ISSUE THREAD

**Issue by JMVoid** [google/flutter-desktop-embedding#474]
there is flutter doctor -v
JMVoid-Mac:example jmvoid$ flutter doctor -v
[✓] Flutter (Channel master, v1.8.4-pre.50, on Mac OS X 10.14 18A391, locale en-HK)
    • Flutter version 1.8.4-pre.50 at /Users/jmvoid/Android/flutter
    • Framework revision 2e183b6233 (8 hours ago), 2019-07-31 23:28:18 -0700
    • Engine revision f790c9ad7e
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 bd049f5b53)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jmvoid/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/jmvoid/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • macOS • macOS • darwin-x64 • Mac OS X 10.14 18A391

• No issues found!

I am clone flutter-desktop-embedding. 
the app can run well when run "flutter run -d macos"
but have a error when run "flutter build macos" 
----------------
JMVoid-Mac:example jmvoid$ flutter build macos
** BUILD FAILED **                                                                                                                                                                                       
The following build commands failed:                                    
        CpResource /Users/jmvoid/goProject/src/github.com/google/flutter-desktop-embedding/example/.dart_tool/flutter_build/7d69d8478dbcc2ce7b4b10c3f84b5fdc/flutter_assets
	/Users/jmvoid/goProject/src/github.com/google/flutter-desktop-embedding/example/.dart_tool/flutter_build/7d69d8478dbcc2ce7b4b10c3f84b5fdc/Build/Products/Debug/Flutter\ Desktop\
	Example.app/Contents/Resources/flutter_assets
(1 failure)                                                             
Building macOS application...                                           
Build process failed
-------------
anyone know how to solve this problem?

**Comment by jonahwilliams** [comment]
Fix is pending here: https://github.com/flutter/flutter/pull/37365
