### ISSUE TITLE
macOS build of testbed is broken

### ISSUE THREAD

**Issue by stuartmorgan** [google/flutter-desktop-embedding#478]
Failing on CI, and I've reproduced locally at least once. Looks like it's related to CocoaPods changes on the Flutter side.

**Comment by csells** [comment]
This seems to be working for me this morning:

macOS Mojave, 10.14.6 (18G84)

➜ flutter --version
Flutter 1.8.4-pre.108 • channel master • https://github.com/flutter/flutter.git
Framework • revision 841707365a (49 minutes ago) • 2019-08-06 09:45:25 -0400
Engine • revision f404a064f1
Tools • Dart 2.5.0 (build 2.5.0-dev.1.0 8cd01287b4)

**Comment by stuartmorgan** [comment]
Clean builds still fail; I think it's not running the pod install step. I haven't had time to investigate in detail yet, but hopefully today.

**Comment by stuartmorgan** [comment]
To see if this was `assemble` related, I retested again just after the revert landed this morning... and this is now fixed. So the CoocaPods integration breakage is apparently also `assemble`-related.

@jonahwilliams A completely clean (make sure `macos/Pods/` is deleted) build of `testbed/` should be part of pre-reland testing as well.

**Comment by jonahwilliams** [comment]
Sounds good. I'll plan on following up with a less ambitious change based on what we're doing for iOS/Android
