### ISSUE TITLE
What is the minimum OS version of Windows ,Linux and macOS that needed to run production build of Flutter Desktop App?

### ISSUE THREAD

**Issue by TechRova** [google/flutter-desktop-embedding#480]
**Describe Request**

I want to know the minimum OS version needed to run flutter desktop applications 

i need for 

- Windows 
  - XP and above
- Linux
  - Debian 
  - Ubuntu 
  - Fedora 
  - Open Suse
  - Arch
- MacOS
  - Mountain Lion and above

Please answer me

**Comment by stuartmorgan** [comment]
In the future, please use the mailing list, not the issue tracker, for questions.

As explained in the project README, there is currently no such thing as a production build of a Flutter desktop application. See also https://github.com/flutter/flutter/wiki/Desktop-shells#current-status which is linked from the README's introduction.

At such time as there are releasable builds, there will be minimum distribution requirements.
