### ISSUE TITLE
[Question] How can I use this to build an x86 exe to run on the x86 operating systems

### ISSUE THREAD

**Issue by ResetPower** [google/flutter-desktop-embedding#481]
Hi! I am a Chinese. I can't speak English very well.
How can I build an x86 exe? There are many users are using x86 operating systems. Especially Windows XP, it has 2.29% market, in China, it has 19.23%! There are too many old computers run in China. I want my application to support more platforms, thank you very much!
By the way, I hope Google back to China. All the service that Google's are the world's best.

**Comment by stuartmorgan** [comment]
That is not currently possible. See https://github.com/flutter/flutter/issues/33862.
