### ISSUE TITLE
[window_size] Allow setting min/max sizes

### ISSUE THREAD

**Issue by zhujintao** [google/flutter-desktop-embedding#483]

**Comment by stuartmorgan** [comment]
Currently the way you would do this is using NSWindow APIs in the Runner code (or set it directly in the XIB).

This is something the window_size prototype should support though, as it's come up several times.

**Comment by stuartmorgan** [comment]
It's going to require some thought to figure out how to make this work on Windows. Unlike macOS and GLFW, where it's a settable property, on Windows it's implemented by replying to a window message that's send during resize (`WM_GETMINMAXINFO`), so we'll need to figure out how to bridge between a plugin and the window class, and maybe set up a generic message handling delegation system.

**Comment by Krysl** [comment]
I made a plugin just now. Because I'm really not good at windows development, this implementation is very bad.
![demo gif](https://github.com/Krysl/win_messages/raw/master/doc/demo.gif)

**Comment by stuartmorgan** [comment]
Now implemented on all platforms.
