### ISSUE TITLE
CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler

### ISSUE THREAD

**Issue by GanZhiXiong** [google/flutter-desktop-embedding#485]
![image](https://user-images.githubusercontent.com/27394631/63070739-ff1dad00-bf4e-11e9-80c3-508ea3bd85ad.png)

![image](https://user-images.githubusercontent.com/27394631/63070747-08a71500-bf4f-11e9-8251-398ee1c48cf4.png)

**Comment by stuartmorgan** [comment]
Given the timing of this bug this was almost certainly #484 

If you can still reproduce after updating FDE, please post the log from `flutter run -v` (build failure output without `-v` isn't useful at the moment due to https://github.com/flutter/flutter/issues/33582) and I'll re-open.

**Comment by GanZhiXiong** [comment]
The following two pictures are the logs that execute the flutter run-v output

![image](https://user-images.githubusercontent.com/27394631/63245992-2d272800-c294-11e9-9954-ec1fbcb94add.png)

![image](https://user-images.githubusercontent.com/27394631/63246005-3912ea00-c294-11e9-8852-3f650ab08111.png)

I didn't upgrade the flutter that was working before, but I didn't upgrade it after

**Comment by stuartmorgan** [comment]
> I didn't upgrade the flutter that was working before

As it says in the project README, you always need to update flutter when you update FDE. The only supported configuration is using the latest master of each.

**Comment by Chesterguan** [comment]
I have updated the flutter with master channel and still got the same problem. The `flutter run -v` results are shown below :

`[  +41 ms] executing: [/Users/ziyuanguan/FlutterFiles/flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[  +58 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[        ] fcaf9c4070bc726585a221279b3c94e37f49698d
[        ] executing: [/Users/ziyuanguan/FlutterFiles/flutter/] git describe
--match v*.*.* --first-parent --long --tags
[  +25 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long
--tags
[        ] v1.13.5-16-gfcaf9c407
[  +12 ms] executing: [/Users/ziyuanguan/FlutterFiles/flutter/] git rev-parse
--abbrev-ref --symbolic @{u}
[  +13 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/Users/ziyuanguan/FlutterFiles/flutter/] git ls-remote
--get-url origin
[  +12 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +73 ms] executing: [/Users/ziyuanguan/FlutterFiles/flutter/] git rev-parse
--abbrev-ref HEAD
[  +14 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[   +7 ms] executing: sw_vers -productName
[  +17 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +17 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.2
[        ] executing: sw_vers -buildVersion
[  +17 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19C57
[  +32 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[  +40 ms] executing: /Users/ziyuanguan/Library/Android/sdk/platform-tools/adb
devices -l
[   +7 ms] Exit code 0 from:
/Users/ziyuanguan/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[  +17 ms] executing:
/Users/ziyuanguan/FlutterFiles/flutter/bin/cache/artifacts/libimobiledevice/idev
ice_id -h
[  +87 ms] executing: /usr/bin/xcode-select --print-path
[   +9 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +1 ms] executing: /usr/bin/xcodebuild -version
[ +130 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[   +3 ms] Xcode 11.3
           Build version 11C29
[   +5 ms] /usr/bin/xcrun simctl list --json devices
[ +140 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[   +3 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[ +137 ms] Found plugin flutter_webview_plugin at
/Users/ziyuanguan/FlutterFiles/flutter/.pub-cache/hosted/pub.dartlang.org/flutte
r_webview_plugin-0.3.10/
[  +29 ms] Found plugin share at
/Users/ziyuanguan/FlutterFiles/flutter/.pub-cache/hosted/pub.dartlang.org/share-
0.6.3+5/
[   +8 ms] Found plugin sqflite at
/Users/ziyuanguan/FlutterFiles/flutter/.pub-cache/hosted/pub.dartlang.org/sqflit
e-1.1.0/
[  +15 ms] Found plugin url_launcher at
/Users/ziyuanguan/FlutterFiles/flutter/.pub-cache/hosted/pub.dartlang.org/url_la
uncher-5.4.1/
[   +1 ms] Found plugin url_launcher_macos at
/Users/ziyuanguan/FlutterFiles/flutter/.pub-cache/hosted/pub.dartlang.org/url_la
uncher_macos-0.0.1+2/
[   +4 ms] Found plugin url_launcher_web at
/Users/ziyuanguan/FlutterFiles/flutter/.pub-cache/hosted/pub.dartlang.org/url_la
uncher_web-0.1.0+2/
[  +47 ms] Found plugin flutter_webview_plugin at
/Users/ziyuanguan/FlutterFiles/flutter/.pub-cache/hosted/pub.dartlang.org/flutte
r_webview_plugin-0.3.10/
[  +12 ms] Found plugin share at
/Users/ziyuanguan/FlutterFiles/flutter/.pub-cache/hosted/pub.dartlang.org/share-
0.6.3+5/
[   +3 ms] Found plugin sqflite at
/Users/ziyuanguan/FlutterFiles/flutter/.pub-cache/hosted/pub.dartlang.org/sqflit
e-1.1.0/
[   +8 ms] Found plugin url_launcher at
/Users/ziyuanguan/FlutterFiles/flutter/.pub-cache/hosted/pub.dartlang.org/url_la
uncher-5.4.1/
[   +1 ms] Found plugin url_launcher_macos at
/Users/ziyuanguan/FlutterFiles/flutter/.pub-cache/hosted/pub.dartlang.org/url_la
uncher_macos-0.0.1+2/
[   +2 ms] Found plugin url_launcher_web at
/Users/ziyuanguan/FlutterFiles/flutter/.pub-cache/hosted/pub.dartlang.org/url_la
uncher_web-0.1.0+2/
[  +65 ms] Generating
/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgery
risk/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +97 ms] Launching lib/main.dart on macOS in debug mode...
[  +61 ms] Found plugin flutter_webview_plugin at
/Users/ziyuanguan/FlutterFiles/flutter/.pub-cache/hosted/pub.dartlang.org/flutte
r_webview_plugin-0.3.10/
[  +14 ms] Found plugin share at
/Users/ziyuanguan/FlutterFiles/flutter/.pub-cache/hosted/pub.dartlang.org/share-
0.6.3+5/
[   +3 ms] Found plugin sqflite at
/Users/ziyuanguan/FlutterFiles/flutter/.pub-cache/hosted/pub.dartlang.org/sqflit
e-1.1.0/
[   +9 ms] Found plugin url_launcher at
/Users/ziyuanguan/FlutterFiles/flutter/.pub-cache/hosted/pub.dartlang.org/url_la
uncher-5.4.1/
[   +1 ms] Found plugin url_launcher_macos at
/Users/ziyuanguan/FlutterFiles/flutter/.pub-cache/hosted/pub.dartlang.org/url_la
uncher_macos-0.0.1+2/
[   +1 ms] Found plugin url_launcher_web at
/Users/ziyuanguan/FlutterFiles/flutter/.pub-cache/hosted/pub.dartlang.org/url_la
uncher_web-0.1.0+2/
[  +48 ms] executing: which pod
[  +19 ms] executing: pod --version
[ +958 ms] 1.8.4
[   +6 ms] executing:
[/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurger
yrisk/macos/] /usr/bin/xcodebuild -list -project Runner.xcodeproj
[+1476 ms] Information about project "Runner":
                        Targets:
                            Runner
                            Flutter Assemble

                        Build Configurations:
                            Debug
                            Release
                            Profile

                        If no build configuration is specified and -scheme is not passed then "Release" is used.

                        Schemes:
                            Flutter Assemble
                            Runner
[   +2 ms] Building macOS application...
[   +3 ms] executing: /usr/bin/env xcrun xcodebuild -workspace /Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/macos/Runner.xcworkspace -configuration Debug -scheme
Runner -derivedDataPath /Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos
OBJROOT=/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Intermediates.noindex
SYMROOT=/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Products COMPILER_INDEX_STORE_ENABLE=NO
[ +731 ms] User defaults from command line:
[        ]     IDEDerivedDataPathOverride = /Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos
[   +1 ms] Build settings from command line:
[        ]     COMPILER_INDEX_STORE_ENABLE = NO
[        ]     OBJROOT = /Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Intermediates.noindex
[        ]     SYMROOT = /Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Products
[ +725 ms] note: Using new build system
[   +5 ms] note: Planning build
[ +146 ms] note: Constructing build description
[ +255 ms] CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (in target 'url_launcher_macos' from project 'Pods')
[        ]     cd /Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/macos/Pods
[        ]     export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
[        ]     export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk
[        ]     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name url_launcher_macos -Onone -enable-batch-mode -enforce-exclusivity=checked
@/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Intermediates.noindex/Pods.build/Debug/url_launcher_macos.build/Objects-normal/x86_64/url_launcher_macos.SwiftFileList -DDEBUG -D COCOAPODS -sdk
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -target x86_64-apple-macos10.11 -g -module-cache-path /Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/ModuleCache.noindex
-Xfrontend -serialize-debugging-options -enable-testing -swift-version 5 -I /Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Products/Debug/url_launcher_macos -F
/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Products/Debug/url_launcher_macos -F
/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/macos/Flutter/ephemeral/.symlinks/flutter/darwin-x64 -parse-as-library -c -j8 -output-file-map
/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Intermediates.noindex/Pods.build/Debug/url_launcher_macos.build/Objects-normal/x86_64/url_launcher_macos-OutputFileMap.json -parseable-output -serialize-diagnostics
-emit-dependencies -emit-module -emit-module-path /Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Intermediates.noindex/Pods.build/Debug/url_launcher_macos.build/Objects-normal/x86_64/url_launcher_macos.swiftmodule
-Xcc -I/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Intermediates.noindex/Pods.build/Debug/url_launcher_macos.build/swift-overrides.hmap -Xcc -iquote -Xcc
/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Intermediates.noindex/Pods.build/Debug/url_launcher_macos.build/url_launcher_macos-generated-files.hmap -Xcc
-I/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Intermediates.noindex/Pods.build/Debug/url_launcher_macos.build/url_launcher_macos-own-target-headers.hmap -Xcc
-I/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Intermediates.noindex/Pods.build/Debug/url_launcher_macos.build/url_launcher_macos-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc
/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Intermediates.noindex/Pods.build/Debug/url_launcher_macos.build/all-product-headers.yaml -Xcc -iquote -Xcc
/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Intermediates.noindex/Pods.build/Debug/url_launcher_macos.build/url_launcher_macos-project-headers.hmap -Xcc
-I/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Products/Debug/url_launcher_macos/include -Xcc
-I/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Intermediates.noindex/Pods.build/Debug/url_launcher_macos.build/DerivedSources-normal/x86_64 -Xcc
-I/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Intermediates.noindex/Pods.build/Debug/url_launcher_macos.build/DerivedSources/x86_64 -Xcc
-I/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Intermediates.noindex/Pods.build/Debug/url_launcher_macos.build/DerivedSources -Xcc -DPOD_CONFIGURATION_DEBUG=1 -Xcc -DDEBUG=1 -Xcc -DCOCOAPODS=1 -emit-objc-header
-emit-objc-header-path /Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Intermediates.noindex/Pods.build/Debug/url_launcher_macos.build/Objects-normal/x86_64/url_launcher_macos-Swift.h -import-underlying-module -Xcc
-ivfsoverlay -Xcc /Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Intermediates.noindex/Pods.build/Debug/url_launcher_macos.build/unextended-module-overlay.yaml -working-directory
/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/macos/Pods
[ +128 ms] CompileSwift normal x86_64 /Users/ziyuanguan/FlutterFiles/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+2/macos/Classes/UrlLauncherPlugin.swift (in target 'url_launcher_macos' from project 'Pods')
[        ]     cd /Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/macos/Pods
[        ]     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -c -primary-file
/Users/ziyuanguan/FlutterFiles/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+2/macos/Classes/UrlLauncherPlugin.swift -emit-module-path
/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Intermediates.noindex/Pods.build/Debug/url_launcher_macos.build/Objects-normal/x86_64/UrlLauncherPlugin\~partial.swiftmodule -emit-module-doc-path
/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Intermediates.noindex/Pods.build/Debug/url_launcher_macos.build/Objects-normal/x86_64/UrlLauncherPlugin\~partial.swiftdoc -serialize-diagnostics-path
/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Intermediates.noindex/Pods.build/Debug/url_launcher_macos.build/Objects-normal/x86_64/UrlLauncherPlugin.dia -emit-dependencies-path
/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Intermediates.noindex/Pods.build/Debug/url_launcher_macos.build/Objects-normal/x86_64/UrlLauncherPlugin.d -emit-reference-dependencies-path
/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Intermediates.noindex/Pods.build/Debug/url_launcher_macos.build/Objects-normal/x86_64/UrlLauncherPlugin.swiftdeps -target x86_64-apple-macos10.11 -enable-objc-interop
-sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -I /Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Products/Debug/url_launcher_macos -F
/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Products/Debug/url_launcher_macos -F
/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/macos/Flutter/ephemeral/.symlinks/flutter/darwin-x64 -enable-testing -g -import-underlying-module -module-cache-path
/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/ModuleCache.noindex -swift-version 5 -enforce-exclusivity=checked -Onone -D DEBUG -D COCOAPODS -serialize-debugging-options -Xcc -working-directory -Xcc
/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/macos/Pods -enable-anonymous-context-mangled-names -Xcc
-I/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Intermediates.noindex/Pods.build/Debug/url_launcher_macos.build/swift-overrides.hmap -Xcc -iquote -Xcc
/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Intermediates.noindex/Pods.build/Debug/url_launcher_macos.build/url_launcher_macos-generated-files.hmap -Xcc
-I/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Intermediates.noindex/Pods.build/Debug/url_launcher_macos.build/url_launcher_macos-own-target-headers.hmap -Xcc
-I/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Intermediates.noindex/Pods.build/Debug/url_launcher_macos.build/url_launcher_macos-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc
/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Intermediates.noindex/Pods.build/Debug/url_launcher_macos.build/all-product-headers.yaml -Xcc -iquote -Xcc
/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Intermediates.noindex/Pods.build/Debug/url_launcher_macos.build/url_launcher_macos-project-headers.hmap -Xcc
-I/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Products/Debug/url_launcher_macos/include -Xcc
-I/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Intermediates.noindex/Pods.build/Debug/url_launcher_macos.build/DerivedSources-normal/x86_64 -Xcc
-I/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Intermediates.noindex/Pods.build/Debug/url_launcher_macos.build/DerivedSources/x86_64 -Xcc
-I/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Intermediates.noindex/Pods.build/Debug/url_launcher_macos.build/DerivedSources -Xcc -DPOD_CONFIGURATION_DEBUG=1 -Xcc -DDEBUG=1 -Xcc -DCOCOAPODS=1 -Xcc -ivfsoverlay
-Xcc /Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Intermediates.noindex/Pods.build/Debug/url_launcher_macos.build/unextended-module-overlay.yaml -parse-as-library -module-name url_launcher_macos -o
/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/Build/Intermediates.noindex/Pods.build/Debug/url_launcher_macos.build/Objects-normal/x86_64/UrlLauncherPlugin.o
[  +16 ms] <unknown>:0: error: PCH was compiled with module cache path '/Users/ziyuanguan/flutter-desktop-embedding/example/build/macos/ModuleCache.noindex/3DF2L6QORS30I', but the path is currently
'/Users/ziyuanguan/MySurgeryRisk_Flutter_Mobile_App-MSR_desktop_chester/mysurgeryrisk/build/macos/ModuleCache.noindex/3DF2L6QORS30I'
[        ] <unknown>:0: error: missing required module 'SwiftShims'
[  +41 ms] ** BUILD FAILED **
[   +2 ms] The following build commands failed:
[        ] 	CompileSwift normal x86_64 /Users/ziyuanguan/FlutterFiles/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+2/macos/Classes/UrlLauncherPlugin.swift
[        ] 	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
[        ] (2 failures)
[  +26 ms] Building macOS application... (completed in 2.1s)
[   +6 ms] "flutter run" took 5,717ms.
Build process failed

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildMacOS (package:flutter_tools/src/macos/build_macos.dart:88:5)
<asynchronous suspension>
#2      MacOSDevice.buildForDevice (package:flutter_tools/src/macos/macos_device.dart:44:11)
#3      DesktopDevice.startApp (package:flutter_tools/src/desktop_device.dart:87:13)
#4      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:430:54)
<asynchronous suspension>
#5      HotRunner.run (package:flutter_tools/src/run_hot.dart:334:39)
#6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:555:37)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:626:18)
#8      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:75:64)
#9      _rootRunUnary (dart:async/zone.dart:1134:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#14     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#15     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
#16     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:293:13)
#17     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#18     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:75:64)
#19     _rootRunUnary (dart:async/zone.dart:1134:38)
#20     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#21     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#22     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#23     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#24     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#25     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#26     _rootRun (dart:async/zone.dart:1126:13)
#27     _CustomZone.run (dart:async/zone.dart:1023:19)
#28     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#29     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#30     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#31     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#32     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)



➜  mysurgeryrisk flutter channel master
Switching to flutter channel 'master'...
git: Already on 'master'
git: Your branch is up to date with 'origin/master'.
➜  mysurgeryrisk flutter upgrade
Upgrading Flutter from /Users/ziyuanguan/FlutterFiles/flutter...
Updating 41a911099..fcaf9c407
 .../test/src/{ => real_tests}/extension_test.dart  |   0
 94 files changed, 3161 insertions(+), 901 deletions(-)
Flutter is already up to date on channel master
Flutter 1.13.6-pre.16 • channel master • https://github.com/flutter/flutter.git
Framework • revision fcaf9c4070 (2 days ago) • 2019-12-21 14:03:01 -0800
Engine • revision 33813929e3
Tools • Dart 2.8.0 (build 2.8.0-dev.0.0 886615d0f9)
➜  mysurgeryrisk flutter doctor -v
Building flutter tool...
[✓] Flutter (Channel master, v1.13.6-pre.16, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.13.6-pre.16 at /Users/ziyuanguan/FlutterFiles/flutter
    • Framework revision fcaf9c4070 (2 days ago), 2019-12-21 14:03:01 -0800
    • Engine revision 33813929e3
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 886615d0f9)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ziyuanguan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • macOS • macOS • darwin-x64 • Mac OS X 10.15.2 19C57

• No issues found!
`

**Comment by stuartmorgan** [comment]
@Chesterguan Your log has nothing to do with this issue; the only thing it has in common is that the build failed, but the failure is totally different. In your case it appears that you likely moved the project and didn't clear Xcode caches. If you are still having issues building, please file a new bug (in the Flutter repo since it's macOS).

**Comment by Chesterguan** [comment]
> @Chesterguan Your log has nothing to do with this issue; the only thing it has in common is that the build failed, but the failure is totally different. In your case it appears that you likely moved the project and didn't clear Xcode caches. If you are still having issues building, please file a new bug (in the Flutter repo since it's macOS).

That's correct,  after `flutter clean` , it works. tx 👍
