### ISSUE TITLE
[windows] Full Screen  App without Title bar

### ISSUE THREAD

**Issue by canewsin** [google/flutter-desktop-embedding#489]
May be this implementation can be useful for Full Screen Apps

**Comment by canewsin** [comment]
This Also requires minimize, maximize and close handles Api for App, so that we can do such tasks within Full Screen App

**Comment by stuartmorgan** [comment]
API requests for the framework need to be [filed in flutter/flutter](https://github.com/flutter/flutter/issues/new/choose) since the frameworks are part of Flutter, not this project.
