### ISSUE TITLE
Desktop cross-platform options?

### ISSUE THREAD

**Issue by GanZhiXiong** [google/flutter-desktop-embedding#495]
Ask me a question. Now I am working on a cross-platform desktop application. It needs to support Windows, macOS and Linux. Now I need to communicate with USB.

**Comment by stuartmorgan** [comment]
Closing, as there's no issue being reported here; please use the mailing list for general questions.

If you want to add hardware-level interactions, you will need to [write a plugin](https://github.com/google/flutter-desktop-embedding/tree/master/plugins).
