### ISSUE TITLE
didChangeMetrics don't work on window snapping, minimizing, maximizing

### ISSUE THREAD

**Issue by jascodes** [google/flutter-desktop-embedding#502]
**Describe the bug**
didChangeMetrics from mixin WidgetsBindingObserver is supposed to be run when the size of screen changes. On resize it works without any issue but when I snap window or minimize or maximize window it does't rebuilt as its supposed to.

**Doctor Output**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.9.6-pre.3, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.36.0)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by stuartmorgan** [comment]
The relevant code is all below the level of FDE, so this needs to be filed at https://github.com/flutter/flutter/issues. Once you file it, if you reference it here I can make sure it gets the right tags applied.
