### ISSUE TITLE
RawKeyboardListener returns incorrect keys on Windows

### ISSUE THREAD

**Issue by bramvbilsen** [google/flutter-desktop-embedding#519]
I am using `RawKeyboardListener` to listen to keyboard key presses. This works great on MacOS, but on Windows, incorrect keys are being in the `onKey` callback (I have not tested on Linux). Pretty much all keystrokes are incorrect.

I have tried switching keyboard layouts without any luck.

**Comment by stuartmorgan** [comment]
The current implementation is a placeholder. Please follow https://github.com/flutter/flutter/issues/37710 for updates.

Closing as this is out of the scope of FDE, and tracked in Flutter.

**Comment by esDotDev** [comment]
Found a bunch of issues with physical key-mappings on Windows. Posting here for visibility, but the bug is here: 
https://github.com/flutter/flutter/issues/72533
