### ISSUE TITLE
Use system setting for font smoothing

### ISSUE THREAD

**Issue by denizzzka** [google/flutter-desktop-embedding#524]
For many years I have been using disabling of font smoothing because I find this comfortable for eyes when using monitor for a long time. I also know that I am not alone. My wish: please use system settings of this mode.

For Linux you can take this setting from any toolkit (Qt, GTK, etc) what appropriate for Flutter project.

![image](https://user-images.githubusercontent.com/974632/64102782-dabd2f80-cd9a-11e9-89a2-7f1e01f8a9a1.png)

**Comment by stuartmorgan** [comment]
Please file a [Flutter issue](https://github.com/flutter/flutter/issues) requesting support for disabling  font smoothing in the engine, since without that there's no way to control it at the FDE level.

**Comment by stuartmorgan** [comment]
Moved to https://github.com/flutter/flutter/issues/53170
