### ISSUE TITLE
Cannot run built application on Windows

### ISSUE THREAD

**Issue by jablonskipj** [google/flutter-desktop-embedding#534]
**Describe the bug**
I have built the .exe file of the application. Next step was to try to run it on another PC with windows operating system. When I have run the app the Error dialog appeared where was an info `Cannot run the application. There is no flutter_windows_glfw.dll. Try to install the application one more time to fix the problem.`. Where can I find the `dll` that the .exe expects? Where to put it to make the built application work? Unfortunately, I have got the ScreenShot of the error only in Polish

![pobrane](https://user-images.githubusercontent.com/12045510/64259697-d410f280-cf29-11e9-8be5-25504047307f.jpeg)

**Comment by stuartmorgan** [comment]
You need to move the entire folder containing the exe, which includes DLLs and resources.

Closing, as this isn't a bug.
