### ISSUE TITLE
align AppSandbox entitlements with iOS

### ISSUE THREAD

**Issue by lesnitsky** [google/flutter-desktop-embedding#536]
On iOS flutter can run a dart server and make requests.
With latest changes in macos template you have to manually add

```
    <key>com.apple.security.network.client</key>
    <true/>
    <key>com.apple.security.network.server</key>
    <true/>
```

Maybe makes sense to have some sort of consistency between platforms?

**Comment by stuartmorgan** [comment]
iOS doesn't have a concept of network access as a capability; macOS does. The inconsistency here is at at the layer of the platform sandboxing itself, not Flutter's configuration (i.e., it's not that we are explicitly adding this permission on iOS but not macOS).

This is consistent with how Android, which does have such a permission, is configured. If you think having internet only enabled by default for debug builds on platforms that have internet access permissions, you may want to argue the point with the author of [this PR](https://github.com/flutter/flutter/pull/22139) 😉
