### ISSUE TITLE
[linux] Add native menu bar support

### ISSUE THREAD

**Issue by stuartmorgan** [google/flutter-desktop-embedding#54]
We'll need to define a protocol on the Dart side for populating and managing native menu bars, and receiving callbacks when they are selected, then implement corresponding plugins for each platform.

On macOS the native side should be relatively straightforward. Currently for Linux it will be tricky, since GLFW doesn't have menu bar support. If the GTK version is working by the time we get to this it'll be much more straightforward, otherwise we can look into a temporary solution like a floating menu window on Linux.

**Comment by krisgiesing** [comment]
The most Flutter-like way to do this is probably to have a MenuBuilder widget (name subject to bikeshedding) that controls an underlying MenuManager class that does the channel communication. Then the menu configuration is set in the build pipeline the same way as other UI elements.

**Comment by krisgiesing** [comment]
Also, just to capture something we discussed out of band: menus get more complex when keyboard shortcuts enter the picture, because keyboard shortcut handling requires coordination with other kinds of input (e.g. IME). So I think this issue is meant to capture menus without shortcuts, and we'll file another issue to track keyboard shortcuts.

**Comment by mrmcq2u** [comment]
GtkUIManager was deprecated in gtk3 and will be removed in 4. AMTK might prove useful to you, it's recently moved to be part of the tepl project. 
https://developer.gnome.org/amtk/unstable/amtk-intro.html
https://developer.gnome.org/tepl/stable/amtk.html

**Comment by stuartmorgan** [comment]
Retitling to reflect the remaining scope.

**Comment by stuartmorgan** [comment]
PR #130 fixed this (in the limited way we can using GLFW); just forgot to close this.
