### ISSUE TITLE
[linux]cannot build on manjaro

### ISSUE THREAD

**Issue by godot0413301** [google/flutter-desktop-embedding#543]
**Describe the bug**
run flutter doctor，fail to download tool

**Doctor Output**
![900B25A6-7E23-473B-8713-2FDECAF4F627](https://user-images.githubusercontent.com/44113641/64469134-9f867c00-d15f-11e9-84de-074c5c43528e.jpeg)
![EC42F9FD-7A9C-4D70-8D77-8A3236D6987C](https://user-images.githubusercontent.com/44113641/64469136-a01f1280-d15f-11e9-9db1-b76bd8b98744.jpeg)

**Comment by stuartmorgan** [comment]
Being unable to run any `flutter` commands is not an issue with this project. You should file this in the Flutter issue tracker.
