### ISSUE TITLE
Instability when the window is set to a larger default resolution in Windows

### ISSUE THREAD

**Issue by thebf** [google/flutter-desktop-embedding#548]
When i set the window size to be 1280x800 instead of 800x600 the production build only starts intermittently (about 10% chance of successfully starting).
The window appears and quickly disappears again.
When actually starts it is rock solid and the window can freely be resized.
When i take the exact same project and revert the window size it becomes stable.
The issue does not manifest when starting the project through visual studio debugging and very rarely appears when starting it through flutter run -d windows.
The issue is less likely to occur when running on a machine with an Nvidia GPU and seems to be slightly less frequent the newer your Intel GPU is.
I've successfully reproduced the issue on 7 machines.
The error in the event viewer is as follows:
"Faulting module name: flutter_windows.dll, version: 0.0.0.0, time stamp: 0x5d71bfec
Exception code: 0xc0000005
Fault offset: 0x00000000007d12b2"

**Comment by stuartmorgan** [comment]
I'm not able to reproduce this so far. Just to be sure that I'm doing the same thing you are, what I tried:
- Check out master, and go into `example\`
- Edit `window_configuration.cpp` to set `kFlutterWindowWidth`/`Height` to `1280`/`800`
- `flutter build windows`
- Manually launch the `Flutter Desktop Example` executable from the `Release` portion of the `build` directory.

Does that match your steps?

**Comment by thebf** [comment]
You might need a heavier flutter project loaded into the example folder for it to happen. The issue does not occur with the example project but with the proprietary application that my company currently ships on IOS and Android it reliably happens on all 7 different windows machines I've tried it on. 
Is there any good way to attach a debugger to the built exe when it closes immediately upon starting?

**Comment by stuartmorgan** [comment]
Windows may have a pause-and-wait-for-debugger command you could add (I have minimal experience with Windows debugging), but I'm not sure if that would end up being different in practice from launching via the VS debugger which you indicated doesn't reproduce it.

Just to confirm: you are building with the latest master? (I.e., after the switch from GLFW to Win32)

**Comment by thebf** [comment]
Aye, building from the latest master.
If anyone familiar with Windows debugging wants to have a look and potentially bolster the stability/capacity for complex projects in FDE I would love some hints. Alternately I can arrange an environment where they can remote in through parsec and have an interactive look under my supervision.

**Comment by stuartmorgan** [comment]
I think the next step would be to get a dump file, [as described here](https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps). It looks like that would allow for after-the-fact investigation via the VS debugger.
