### ISSUE TITLE
[Feature][Desktop] 2 or more apps running (debug)

### ISSUE THREAD

**Issue by iamsabet** [google/flutter-desktop-embedding#562]
hi , im using flutter for some time now, lightest debug process is for desktop as i tried , 
i,ve been thinking How Exactly should we run 2 or more flutter apps running , (Macos)
because right now when i run second one , the first one quits , 
is that even possible for now (2 or more (different or even similar) apps for desktop platform on the fly) (debug)(parallel independent hot_view as another dart process or whatever)?
i appreciate your answer <3

1.10.2pre

<img width="813" alt="Screen Shot 2019-09-14 at 2 28 51 AM" src="https://user-images.githubusercontent.com/20267993/64897095-6d14db80-d697-11e9-9151-de91f3280a76.png">

**Comment by jonahwilliams** [comment]
We currently kill the old desktop process if a new one starts up, I think I should just remove that behavior.

**Comment by stuartmorgan** [comment]
This is tracked already as https://github.com/flutter/flutter/issues/37889; closing this version since it's a `flutter` behavior, not an FDE behavior.
