### ISSUE TITLE
Is there any way to using Firebase Mlkit ?

### ISSUE THREAD

**Issue by kalismeras61** [google/flutter-desktop-embedding#573]

**Comment by stuartmorgan** [comment]
Please use the mailing list, not the issue tracker, for questions.

From https://firebase.google.com/docs/ml-kit:
> ML Kit is a mobile SDK that brings Google's machine learning expertise to Android and iOS

You can't use a mobile SDK on desktop; you'd need something that supports your desktop platform(s).
