### ISSUE TITLE
[Windows] Consider building using static runtime

### ISSUE THREAD

**Issue by jablonskipj** [google/flutter-desktop-embedding#587]
**Describe the bug**
After the upgrade of the Visual Studio to version 16.3.2, I have encountered a bug. I have built the application via `flutter build windows` and now when I try to run it it gives me an error modal that sais that the `VCRUNTIME140_1.dll` is missing. I am not able to run the app on another computer than the one that I develop on. Is there any possibility to fix this issue?

**Comment by stuartmorgan** [comment]
Currently the Runner and plugins use the stand runtime, so [the C++ runtime](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) needs to be installed on the machines. My understanding is that standard practice for apps that require this is to include it in the application's installer.

The other option is to statically link the runtime. We may go that route at some point, but it means duplicating it in each plugin. We need to see what the size implications of that are. However, it might be desirable for better build isolation of plugins. See also https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

Leaving this open to track the need for us to evaluate and make a final decision on this.

**Comment by jablonskipj** [comment]
@stuartmorgan so summing up -> I have to install the same version of the C++ runtime as the one that I have used to build the app, for now. Is that correct?

**Comment by stuartmorgan** [comment]
Yes, or edit the project to link the runtime statically.

**Comment by wav** [comment]
The approach I've taken is to use a build variable called `VCInstallDir` in a post build script.

Using that I can copy the necessary assemblies to the output folder in a post build event. The folder I reference is the following:

`${VCInstallDir}\Redist\MSVC\14.23.27820\x64\Microsoft.VC142.CRT`

**Comment by Lx** [comment]
> [**stuartmorgan**](https://github.com/stuartmorgan) commented [on 8 Oct 2019](https://github.com/google/flutter-desktop-embedding/issues/587#issuecomment-539078924)
> > Yes, or edit the project to link the runtime statically.

Can I trouble someone for instructions on how to do this?

I've copied a built Flutter desktop app to a PC that doesn't have internet access, and whose configuration I don't have permission to change (so installing the C++ runtime is not an option).

Am I correct in understanding that statically linking the runtime as part of the build/run means runtime installation isn't necessary?

**Comment by stuartmorgan** [comment]
> Can I trouble someone for instructions on how to do this?

[Here are the official instructions](https://docs.microsoft.com/en-us/cpp/build/reference/md-mt-ld-use-run-time-library?view=vs-2019#to-set-this-compiler-option-in-the-visual-studio-development-environment).

> I've copied a built Flutter desktop app to a PC that doesn't have internet access, and whose configuration I don't have permission to change (so installing the C++ runtime is not an option).

Can't you just include the necessary runtime DLL(s) in the project directory next to the exe with the other required DLLs (flutter_windows.dll, any plugin DLLs)?

**Comment by stuartmorgan** [comment]
I did a quick experiment, and using the static runtime increases the size of each of the current FDE plugins from ~50-70K to ~300-500K, and Testbed.exe from ~100K to ~500K.

While that's not all that much in current desktop machine size terms, it's not clear to me that the benefit of doing that vs. having a simple path to bundling the necessary runtime libraries (e.g., adding to bundle_assets_and_deps) is the right approach. We should look more into the tradeoffs in terms of potential interactions between plugins, which would be more isolated with a static runtime.

**Comment by 926** [comment]
> > Can I trouble someone for instructions on how to do this?
> 
> Here are [the official instructions](https://docs.microsoft.com/en-us/cpp/build/reference/md-mt-ld-use-run-time-library?view=vs-2019#to-set-this-compiler-option-in-the-visual-studio-development-environment). If you use any plugins, you'll have to do it for all of them too.
> 
> > I've copied a built Flutter desktop app to a PC that doesn't have internet access, and whose configuration I don't have permission to change (so installing the C++ runtime is not an option).
> 
> Can't you just include the necessary runtime DLL(s) in the project directory next to the exe with the other required DLLs (flutter_windows.dll, any plugin DLLs)?

First thank you @stuartmorgan for making it possible to port flutter to windows.
The app works, we shipped it to the client, now we could use some help to help them launch it without this error.

I read official instructions several times for static linking.
I do not understand how to get/write the necessary runtime DLL.
Is this something that VS generates ?

Anyway, clients have access to internet. So having a path to bundling the necessary runtime libraries on startup would solve the problem. Could you please point me to any instructions on how to do this ?
. Please could you

**Comment by stuartmorgan** [comment]
> I read official instructions several times for static linking.
> I do not understand how to get/write the necessary runtime DLL.

If you use static linking, you don't need a runtime DLL. It's one or the other.

> Could you please point me to any instructions on how to do this ?

I don't have any instructions to point you to. Documenting how to distribute builds to end users when we don't yet have support for release builds is not a priority, given that people should not be distributing debug builds.

This isn't specific to Flutter though—any C++ Win32 application using a dynamic runtime will need the same set of libraries—so I would imagine that there are resources out there that could help you.

**Comment by stuartmorgan** [comment]
Closing in favor of https://github.com/flutter/flutter/issues/53167 now that the VS project source of truth is the `flutter create` template.

**Comment by 926** [comment]
Hi ,

Sharing alternative in case I am not the only one unable to modify the runner. 

1. Convince user to download Visual Studio on their laptop
2. Ask them to also install C++Development package
![image](https://user-images.githubusercontent.com/14161798/78973751-d024fe80-7b10-11ea-9c16-c1eee2a7f049.png)
