### ISSUE TITLE
[Windows] SDK version not found; retargeting solution has no effect

### ISSUE THREAD

**Issue by mtcliatt** [google/flutter-desktop-embedding#592]
When building the example (or testbed) app  for Windows, I get this error stating that the Windows SDK version 8.1 was not found.

A fix is suggested: either installing the required version of the SDK or retargeting the projects.
I've attempted to fix the issue by retargeting the solutions to my current Windows SDK version (>10.0), but I see the same error after doing so.

```
[ ] Project "C:\Users\matth\code\flutter-desktop-embedding\example\windows\Runner.vcxproj.metaproj" (2) is building "C:\Users\matth\code\flutter-desktop-embedding\example\windows\FlutterBuild.vcxproj" (3) on node 1 (default targets).
[ ] C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.WindowsSDK.targets(46,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\matth\code\flutter-desktop-embedding\example\windows\FlutterBuild.vcxproj]
```

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.10.13-pre.12, on Microsoft Windows [Version 10.0.18362.418], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Visual Studio - develop for Windows (Visual Studio Community 2017 15.9.11)
[√] Android Studio (version 3.2)
[√] IntelliJ IDEA Community Edition (version 2018.3)
[√] VS Code (version 1.39.2)
[√] Connected device (1 available)
```

**Comment by stuartmorgan** [comment]
This sounds like I was wrong about the stripped-down FlutterBuild target not needing an SDK. Does https://github.com/stuartmorgan/flutter-desktop-embedding/tree/windows-flutter-build-sdk work for you? If so I'll make a PR from it.

**Comment by mtcliatt** [comment]
Confirmed working, thanks for the fix!

**Comment by mtcliatt** [comment]
Just a note, I would have assumed that SDK 10.0 would have worked as well, but it didn't. In Visual Studio in the retarget prompt, it shows that the latest installed version I have is 10.0, so I tried retargeting to that. Relative to your change, the only difference is the version number, but it doesn't work. I get an error similar to my original, stating that I'm missing SDK 10.0 this time. That doesn't seem right since VS is telling me I do have 10.0.

**Comment by l1n3n01z** [comment]
I was able to get the build working by simply setting the SDK target to the current Windows SDK I have. 

```
diff --git a/example/windows/FlutterBuild.vcxproj b/example/windows/FlutterBuild.vcxproj
index 5a347b1..883c3b7 100644
--- a/example/windows/FlutterBuild.vcxproj
+++ b/example/windows/FlutterBuild.vcxproj
@@ -14,6 +14,7 @@
     <VCProjectVersion>15.0</VCProjectVersion>
     <ProjectGuid>{6419BF13-6ECD-4CD2-9E85-E566A1F03F8F}</ProjectGuid>
     <ProjectName>Flutter Build</ProjectName>
+    <WindowsTargetPlatformVersion>10.0.17763.0</WindowsTargetPlatformVersion>^M
   </PropertyGroup>
   <Import Project="$(VCTargetsPath)\Microsoft.Cpp.Default.props" />
   <PropertyGroup Label="Configuration">
@@ -42,4 +43,4 @@ 
```

**Comment by stuartmorgan** [comment]
Yes, that's what the PR does. It just hasn't landed yet.
