### ISSUE TITLE
FlutterViewController.init(project: project) initializes default project in release mode

### ISSUE THREAD

**Issue by lesnitsky** [google/flutter-desktop-embedding#599]
`FlutterViewController` runs default flutter project in release mode on macos:

```swift
func openFlutterProject(_ result: @escaping FlutterResult) {
    panel.beginSheetModal(for: window) { (response) in
      if response.rawValue == NSFileHandlingPanelOKButton {

        guard let bundle = Bundle(
          url: panel.urls[0].appendingPathComponent("build")
        ) else {
          print("can't load project bundle")
          return
        }

        print(bundle.bundleURL)

        runProjectFromBundle(bundle)

        result(nil)
      }
    }
  }
}

func runProjectFromBundle(_ bundle: Bundle) {
    let project = FlutterDartProject(precompiledDartBundle: bundle)
    let flutterViewController = FlutterViewController.init(project: project)

    flutterViewController.view.contentFilters = [DiscardBlackFilter()]
    flutterViewController.view.layerUsesCoreImageFilters = true

    addChild(flutterViewController)

    self.projectFlutterView = flutterViewController.view

    self.view.addSubview(
      self.projectFlutterView!,
      positioned: .below,
      relativeTo: self.view.subviews.first
    )
}
```

This code works perfectly in debug mode (opens correct project), but opens _itself_ in release mode

**Comment by lesnitsky** [comment]
`print(bundle.bundleURL)` prints correct bundle URL in release mode

**Comment by stuartmorgan** [comment]
> `FlutterViewController` runs default flutter project in release mode on macos:
> ...
> This code works perfectly in debug mode (opens correct project), but opens _itself_ in release mode

I'm not clear on what the bug you're reporting is. What do "default flutter project" and "itself" mean?

**Comment by lesnitsky** [comment]
my flutter app (host) runs another flutter app (guest) inside
by "default flutter project" I mean "host"
"itself" = "host" as well

> It seems like you are trying to make a generic runner; this is not a good idea for a number of reasons.

this is exactly what I'm doing. Can you explain why this is a bad idea?

I came up with the following "problems"
- engine/framework version conflicts ("guest" app may require different engine version)
- missing plugins in "host"

**Comment by lesnitsky** [comment]
> What is "build"?

build folder created by `flutter build`

> how are you making them

`flutter build bundle`

**Comment by lesnitsky** [comment]
when "host" runs in debug mode – "guest" is running correctly as well
when "host" runs in release – it renders one more instance of "host" inside (instead of guest)

**Comment by stuartmorgan** [comment]
> my flutter app (host) runs another flutter app (guest) inside

I'm confused why the host is a Flutter app, but okay, that clarifies things somewhat.

> Can you explain why this is a bad idea?
>
> I came up with the following "problems"
> - engine/framework version conflicts ("guest" app may require different engine version)
> - missing plugins in "host"

Those are probably the biggest ones. Others include likely problems with signing, and missing entitlements.

> `flutter build bundle`

So you're building the "guest" the same way for both debug and release mode, but expecting the "host" VM to be able to load it regardless? Or is there more to how you are creating the bundle?

I'm also confused as to why the thing you are loading is called "build". Are you actually pointing it directly at the "build" folder? That's not a bundle.

**Comment by lesnitsky** [comment]
> The bundle must either contain a flutter_assets resource directory, or set the Info.plist key FLTAssetsPath to override that name (if you are doing a custom build using a different name).

I may have interpreted this incorrectly. My understanding was that any folder containing `flutter_assets` may be treated as a bundle (this assumption seems to be confirmed since everything works fine in debug mode)

> So you're building the "guest" the same way for both debug and release mode, but expecting the "host" VM to be able to load it regardless?

The way this question is formulated implies "you're wrong" in case of "yes" answer :)
What I'm doing is:

* `flutter build bundle` (creates `flutter_asset` in `build` folder)
* opening project folder in "host" app
* loading `<project_path>/build` (works fine in debug mode)

both `flutter build bundle --debug` and `flutter build bundle` work fine when host runs in debug

**Comment by lesnitsky** [comment]
> I don't know why you put problems in quotes, since just the first by itself will cause complete failure in any scenario where the guest wasn't built using exactly the same version as the host, and I'm having a hard time imagining a scenario where you can guarantee that but where this structure serves a useful purpose.

I'm building a developer tool. Those constraints are known and left up to "user" to deal with (use exact flutter version/plugin etc.)

**Comment by stuartmorgan** [comment]
> > The bundle must either contain a flutter_assets resource directory, or set the Info.plist key FLTAssetsPath to override that name (if you are doing a custom build using a different name).
> 
> I may have interpreted this incorrectly. My understanding was that any folder containing `flutter_assets` may be treated as a bundle

You need to pass a valid macOS Flutter project bundle. Part of that bundle must be an assets directory, using either the default directory name or a key-specified directory.

> (this assumption seems to be confirmed since everything works fine in debug mode)

Debug happens to only use the assets directory, since that's where JIT snapshots live; that doesn't mean the assumption was correct.

> > So you're building the "guest" the same way for both debug and release mode, but expecting the "host" VM to be able to load it regardless?
> 
> The way this question is formulated implies "you're wrong" in case of "yes" answer :)
> What I'm doing is:
> 
> * `flutter build bundle` (creates `flutter_asset` in `build` folder)
> * opening project folder in "host" app
> * loading `<project_path>/build` (works fine in debug mode)

Yes, this is wrong. `build bundle` makes only the assets directory (per help description). That's not the only thing that a valid project needs.

> both `flutter build bundle --debug` and `flutter build bundle` work fine when host runs in debug

Well, those do the same thing, so that's not surprising; without `--precompiled` it always does debug (per recently-fixed help). And to save more trouble/confusion: passing `--precompiled` for release isn't going to help, because that's going to give you assets without the JIT snapshot, but you still won't have the AOT piece you need because that's not part of the assets.

If you want to support anything other than debug, `build bundle` isn't what you want. You'd need correctly constructed `assemble` calls, and you'd need to be using the generated framework, and you'd need to dynamically load that code.

Closing, as this is a misunderstanding of how to construct a valid project bundle, rather than a Flutter or FDE bug.

> I'm building a developer tool. Those constraints are known and left up to "user" to deal with

I think you are underestimating the difficulty of "just deal with it" here. E.g., I don't see how an end user can possibly deal with the plugin problem (unless you expect everyone using this tool to alter it for all of their guest apps... at which point how is it a generic runner?)

**Comment by lesnitsky** [comment]
Thanks for your clarifications
One more comment: I'd expect engine failing to run if bundle is invalid
rather than falling back to some "default" option it can find

**Comment by stuartmorgan** [comment]
Yes, I was thinking about that last night since I wasn't sure at first why it wasn't failing. Filed the bug above (which after having thought about it enough I'm pretty sure means even if you make the "guest" framework correctly it won't work right now).
