### ISSUE TITLE
[Windows] Input cursor behavior while using the numeric keyboard

### ISSUE THREAD

**Issue by jablonskipj** [google/flutter-desktop-embedding#603]
**Describe the bug**
Hello. During the work with the flutter on the desktop, I have encountered a problem with the Input fields on windows. The main problem that I have is that the cursor is switching the position randomly while using the numeric keyboard. This leads to a situation when typing for example `123` on the keyboard I can see `132` in the input field. Unfortunately, `onChange` function gives me the same result (the sequence is the same as the value that I can see in the input field), so I am not able to easily distinguish if I should reorganize the String manually.

Steps to reproduce:
- Implement a small input field in the application
- run the app on Windows
- type something into the field with the use of numeric keyboard
- see the result where string in the input is different than the one you typed on the keyboard.

Am I missing something in the InputField configuration?

**Comment by stuartmorgan** [comment]
Text input behavior is controlled by the framework and engine, below the level of the code in this repository, so you'll need to file this in the Flutter issue tracker. (Unfortunately I can't move it.)
