### ISSUE TITLE
flutter-desktop-embedding have a blank window after run the built program on linux

### ISSUE THREAD

**Issue by biij5698** [google/flutter-desktop-embedding#604]
on linux 64 bit system,after i built a flutter-desktop-embedding program,when i run it,a blank window appeared quickly

**Comment by stuartmorgan** [comment]
A blank window is often the result of an exception. Please provide the console log from running (in debug mode).

Also, can you reproduce this with the `example` here, or only with your own application?

**Comment by biij5698** [comment]
The program's postition is :~/pro/flutter-desktop-embedding/example
Then i run the command:flutter run --debug
Then a blank widnow appeared about two seconds and then the normal window appeared.
Here can not upload the pictures of the blank window.
The follow is the running log:
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                           
flutter: ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a platform message callback:
flutter: 'package:flutter/src/widgets/shortcuts.dart': Failed assertion: line 76 pos 16: 'keys.isNotEmpty':
flutter: is not true.                                                   
flutter:                                                                
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:                                                                
flutter: When the exception was thrown, this was the stack:             
flutter: #2      new KeySet.fromSet (package:flutter/src/widgets/shortcuts.dart:76:16)
flutter: #3      new LogicalKeySet.fromSet (package:flutter/src/widgets/shortcuts.dart:138:63)
flutter: #4      ShortcutManager.handleKeypress (package:flutter/src/widgets/shortcuts.dart:192:63)
flutter: #5      _ShortcutsState._handleOnKey (package:flutter/src/widgets/shortcuts.dart:342:20)
flutter: #6      FocusManager._handleRawKeyEvent (package:flutter/src/widgets/focus_manager.dart:1314:38)
flutter: #7      RawKeyboard._handleKeyEvent (package:flutter/src/services/raw_keyboard.dart:528:17)
flutter: <asynchronous suspension>                                      
flutter: #8      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:74:49)
flutter: <asynchronous suspension>                                      
flutter: #9      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:200:33)
flutter: <asynchronous suspension>                                      
flutter: #10     _invoke3.<anonymous closure> (dart:ui/hooks.dart:303:15)
flutter: #14     _invoke3 (dart:ui/hooks.dart:302:10)                   
flutter: #15     _dispatchPlatformMessage (dart:ui/hooks.dart:162:5)    
flutter: (elided 5 frames from class _AssertionError and package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
Syncing files to device Linux...                                        
Lost connection to device.                                      
Syncing files to device Linux...

**Comment by stuartmorgan** [comment]
What key are you pressing to trigger this?

**Comment by biij5698** [comment]
The same problem is appeared on window 10 system,but the blank window appeared less than one seconed.

**Comment by biij5698** [comment]
I did not pressed any key and then i clicked the close button of the appeared window.

**Comment by biij5698** [comment]
The Linux system is Deepin

**Comment by biij5698** [comment]
This seems to be caused by insufficient performance.

**Comment by biij5698** [comment]
The Linux system's computer is used Mechanical hard disk

**Comment by stuartmorgan** [comment]
> The same problem is appeared on window 10 system

With the exact same stack trace?

> I did not pressed any key

Odd, since the stack is showing that the key handler is being invoked.

> This seems to be caused by insufficient performance.

I'm not sure how you are coming to that conclusion; there is no reason for whether or not a set contains elements in a key event handler to be performance-sensitive. If you have clear evidence that this is related to performance, please provide details.

**Comment by stuartmorgan** [comment]
Also, please provide your `flutter doctor` output so that we have exact version information.

In general, please always include that when filing a bug. The template requests it because it's almost always important to know the version where a bug happens.

**Comment by stuartmorgan** [comment]
> The program's postition is :~/pro/flutter-desktop-embedding/example

To be clear: are you saying you are running the FDE example without modification? Or do you have your own code added to it?

**Comment by thavlik** [comment]
I get `flutter: 'package:flutter/src/widgets/shortcuts.dart': Failed assertion: line 76 pos 16: 'keys.isNotEmpty'` on macOS 10.15.1 Catalina (latest) with no apparent cause or consequence. It just shows up completely randomly in the console. I do have a keyboard listener, so I am guessing it has to do with that.

**Comment by stuartmorgan** [comment]
Please file that exception in the Flutter issue tracker; if you're seeing it in an otherwise-working app it doesn't sounds like that's actually the cause of the blank screen reported here, but it would be good to investigate that on the framework side.

**Comment by stuartmorgan** [comment]
Closing due to lack of response. @biij5698 if you can supply the information requested above, I can re-open.
