### ISSUE TITLE
The Windows application UI scale has increased after v1.9.0

### ISSUE THREAD

**Issue by SahajRana** [google/flutter-desktop-embedding#605]
Hi Flutter team, It's been great using the framework. I'm encountering some issue like, 
In the master channel versions (above v1.9.0), for Windows.

- The window UI scale has increased (I think the dpi ratio is increased from embedder).

I initially thought it would be solved by time, but still on the latest version of flutter which I tried today v1.10.15-pre.330. The problem still persists due to which I have to revert back to v1.9.0. I hope you guys might help us out with this!

Everything has got scaled up including text, widget width, height, etc. after `v1.9.0`.

I dug deep in CPP code and found the `GetDpiForWindow(HWND)` returns `120` in place of `96` which I think is about 125% scale of the window. I have a hunch it's due to moving to win32api from glfw one. Is there a way to make it `96`?

**Doctor Output**
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.10.15-pre.330, on Microsoft Windows [Version 10.0.18362.418], locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.2.3)
[!] Android Studio (version 1.5)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    X Unable to find bundled Java version.
[√] Android Studio (version 3.1)
[√] VS Code, 64-bit edition (version 1.37.1)
[√] Connected device (3 available)

! Doctor found issues in 2 categories. 
```

**Comment by stuartmorgan** [comment]
Can you elaborate on what you mean by "in place of 96"? Do you believe that 96 is the correct value and the DPI check is giving the wrong value for your monitor?

It's not clear to me whether you are saying this is a bug, or you just want to manually use a DPI that doesn't actually match your monitor (and if the latter, why).

**Comment by SahajRana** [comment]
Hi @stuartmorgan, thanks for your reply. I just wanted to know how could we get the scale as it was previously on v1.9.0. 

Regarding DPI `96`, it was just my speculations which I found on Microsoft site while I tried to make it happen.
[link](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/dpi-related-apis-and-registry-settings)
![Screenshot (523)](https://user-images.githubusercontent.com/16938202/68709015-d8f1c280-05ba-11ea-95e9-47cad767f338.png)

**Comment by stuartmorgan** [comment]
There switch to Win32 improved DPI detection, so absent evidence to the contrary I am assuming that the current behavior is correct, and the old behavior was the bug. Closing given that; if you do have evidence that it's wrong please let me know.

If you want a way to override the DPI manually please file a feature request in the Flutter issue tracker for an API to do that. (You may also want to try turning off DPI detection in the runner's manifest, although that may break something.)
