### ISSUE TITLE
What's the time for release?

### ISSUE THREAD

**Issue by yangwuan55** [google/flutter-desktop-embedding#606]
Just the question.Thanks.

**Comment by stuartmorgan** [comment]
Please use the mailing list for questions in the future.

I'm not sure what "release" means in the context of this repository. Assuming you're asking when code will be moved to permanent locations:
- Windows and Linux templates will be created from `example` once the API on each platform is relatively stable.
- flutter/plugins implementations will move when the plugin API and tooling for each platform is stable.
- Other plugins will be removed as corresponding functionality is added to the framework.

All of those things are driven by completion, not date.
