### ISSUE TITLE
argument_type_not_assignable

### ISSUE THREAD

**Issue by NaveenMetta** [google/flutter-desktop-embedding#613]
**Describe the bug**
error: The argument type 'NormalizationMultipliers (where NormalizationMultipliers is defined in /Users/naveenkmetta/mettapps/kids_app/kids_app/lib/Slideplayer/models/normalization_multipliers.dart)' can't be assigned to the parameter type 'NormalizationMultipliers (where NormalizationMultipliers is defined in /Users/naveenkmetta/mettapps/kids_app/kids_app/lib/Slideplayer/models/normalization_multipliers.dart)'. (argument_type_not_assignable at [flutter_slides] content/slide_content_factory.dart:46)

**Doctor Output**
Please provide the output of `flutter doctor -v`:
```
Naveens-MBP:bin naveenkmetta$ flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-US)
    • Flutter version 1.9.1+hotfix.6 at /Users/naveenkmetta/development/flutter
    • Framework revision 68587a0916 (2 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/naveenkmetta/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 1734441B-3001-4350-B268-DC4596CDEA42 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

• No issues found!

Naveens-MBP:bin naveenkmetta$
``

**Comment by NaveenMetta** [comment]
Issue resolved after switching flutter version from v1.9.1+hotfix.6 to 1.12.11.

**Comment by NaveenMetta** [comment]
Naveens-MBP:bin naveenkmetta$ flutter doctor -v
[✓] Flutter (Channel unknown, v1.12.11, on Mac OS X 10.15.1 19B88, locale en-US)
    • Flutter version 1.12.11 at /Users/naveenkmetta/development/flutter
    • Framework revision f40dbf8ca0 (2 days ago), 2019-11-23 01:02:54 -0500
    • Engine revision d1cac77d5a
    • Dart version 2.7.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/naveenkmetta/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)
    • iPhone 11 Pro Max • 1734441B-3001-4350-B268-DC4596CDEA42 • ios        • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)
    • macOS             • macOS                                • darwin-x64 • Mac OS X 10.15.1 19B88

• No issues found!

**Comment by stuartmorgan** [comment]
There doesn't appear to be anything desktop-specific about this; you'll need to file a bug in the Flutter issue tracker instead.
