### ISSUE TITLE
Example of File Chooser

### ISSUE THREAD

**Issue by 926** [google/flutter-desktop-embedding#616]
Hi,

Would it be possible to have a short example of how to implement **[file_chooser](https://github.com/google/flutter-desktop-embedding/tree/master/plugins/file_chooser/lib/src)** plugin,
So far I understand we need to wrap the two functions (below), but cannot see how to use the ```FileChooserChannelController.instance.show(FileChooserType.open, options, callback);```

Also isn't it necessary to use Future / async / await ?

Thanks again for your help

```
showOpenPanel(callBack)
callBack(FileChooserResult result, List<String> paths)

**Comment by cbenhagen** [comment]
You might want to check the example in the testbed:
https://github.com/google/flutter-desktop-embedding/blob/master/testbed/lib/main.dart#L298-L339

**Comment by stuartmorgan** [comment]
Because the plugins in this repository are temporary, there is no plan to document them beyond the Dart code comments and the sample usage in `testbed`. When they become either part of the framework or official plugins, they will get the usual documentation.

**Comment by stuartmorgan** [comment]
As for Future/await, I'd be happy to take a PR that changed the API to use Futures. That would make it more idiomatic Dart.

**Comment by 926** [comment]
Thank you so much for lightning speed support !
@stuartmorgan changing API is out of my range for now, but will get there.

**Comment by stuartmorgan** [comment]
I filed #617 so it's tracked.
