### ISSUE TITLE
Windows Build Failure

### ISSUE THREAD

**Issue by mcoolidge** [google/flutter-desktop-embedding#624]
Running the example project fails with a build error. Running on flutter channel master.

Flutter run provides little info but loading the project in Visual Studio provides:

binary '=': no operator found which takes a right-hand operand of type 'void' (or there is no acceptable conversion)	
flutter-desktop-embedding-master\example\windows\main.cpp	110	

**Doctor Output**
flutter doctor -v     
[√] Flutter (Channel unknown, v1.10.6-pre.29, on Microsoft Windows [Version 10.0.19041.1], locale en-US)
    • Flutter version 1.10.6-pre.29 at C:\Users\Mat\development\flutter
    • Framework revision 919cc97f6a (3 months ago), 2019-09-20 14:57:05 -0700
    • Engine revision 99092a0436
    • Dart version 2.6.0 (build 2.6.0-dev.1.0 7c1821c4aa)

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Mat\development
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.4.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
    • Visual Studio Professional 2019 version 16.4.29613.14

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.4
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593

[√] VS Code, 64-bit edition (version 1.41.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • Windows • Windows • windows-x64 • Microsoft Windows [Version 10.0.19041.1]

**Comment by stuartmorgan** [comment]
> • Flutter version 1.10.6-pre.29 at C:\Users\Mat\development\flutter
> • Framework revision 919cc97f6a (3 months ago), 2019-09-20 14:57:05 -0700

Your version of Flutter is too old to use with this project. See the [setup instructions](https://github.com/google/flutter-desktop-embedding/blob/master/README.md#setting-up)

**Comment by mcoolidge** [comment]
I blew away my flutter directory and re-installed to make sure. Still seeing the same problem with the following output from flutter doctor -v

[√] Flutter (Channel master, v1.13.6-pre.34, on Microsoft Windows [Version 10.0.19041.1], locale en-US)
    • Flutter version 1.13.6-pre.34 at C:\Users\Mat\development\flutter
    • Framework revision 50d421224d (35 minutes ago), 2019-12-27 10:26:49 -0800
    • Engine revision 42bb7c9eea
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 c260e4e8da)

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Mat\development
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.4.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
    • Visual Studio Professional 2019 version 16.4.29613.14

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.4
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593

[√] VS Code, 64-bit edition (version 1.41.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • Windows • Windows • windows-x64 • Microsoft Windows [Version 10.0.19041.1]

**Comment by mcoolidge** [comment]
Clearing my builds, doing a clean, and rebuild seems to allow it to work now. The IDE's still show the error, but that might be some cache. Thanks for the help!
