### ISSUE TITLE
Error building for linux

### ISSUE THREAD

**Issue by murilinhoPs** [google/flutter-desktop-embedding#627]
**Describe Request**
I dont't know if I did something wrong, or if it's a bug or not. I hope I'm posting this issue in the right place. 
Everytime I build or run for linux (android is working) I get this output:

_'Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                                                                           
make: *** Nenhum alvo indicado e nenhum arquivo make encontrado.  Pare.
Building Linux application...                                           
Build process failed'_

Can someone help me?

**Comment by stuartmorgan** [comment]
The error says you have no makefile, which means you haven't followed the instructions [here](https://github.com/google/flutter-desktop-embedding/blob/master/README.md#running-other-flutter-projects) (linked from [the official instructions](https://github.com/flutter/flutter/wiki/Desktop-shells#tooling)) to make your project work on Linux.
