### ISSUE TITLE
[Linux on Manjaro] Crash on launch

### ISSUE THREAD

**Issue by Roger28** [google/flutter-desktop-embedding#632]
**Describe the bug**
When running the example or any application for desktop Linux opens the application window (does not load fully) and then closes appearing this error in the console.

![err1](https://user-images.githubusercontent.com/37430107/72095011-5f462e80-32f6-11ea-95ef-4b865cc6e44d.png)

**Doctor Output**
![err2](https://user-images.githubusercontent.com/37430107/72094532-64ef4480-32f5-11ea-97b7-440d2033e2ba.png)

**Comment by stuartmorgan** [comment]
In the future copy and paste output rather than posting screenshots.

If you run the executable under `gdb`, can you get crash details and/or a backtrace?

**Comment by stuartmorgan** [comment]
Possibly the same crash as https://github.com/flutter/flutter/issues/47954, but no way to know yet.

**Comment by Roger28** [comment]
> In the future copy and paste output rather than posting screenshots.
> 
> If you run the executable under `gdb`, can you get crash details and/or a backtrace?

That's all that appears when running, I don't know how to run the executable in gdb ...

**Comment by Roger28** [comment]
[this@this-pc example]$ flutter run -v
[  +31 ms] executing: [/home/this/flutter/] git -c log.showSignature=false log
-n 1 --pretty=format:%H
[  +58 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[        ] 51e24a3561ee4f50a2b4ddeb36b1f7ea59d768d2
[        ] executing: [/home/this/flutter/] git describe --match v*.*.*
--first-parent --long --tags
[ +365 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long
--tags
[   +3 ms] v1.13.7-65-g51e24a356
[   +8 ms] executing: [/home/this/flutter/] git rev-parse --abbrev-ref
--symbolic @{u}
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/this/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +70 ms] executing: [/home/this/flutter/] git rev-parse --abbrev-ref HEAD
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +58 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[  +22 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[  +93 ms] executing: /home/this/Android/Sdk/platform-tools/adb devices -l
[+3138 ms] Exit code 0 from: /home/this/Android/Sdk/platform-tools/adb devices
-l
[        ] List of devices attached
[        ] * daemon not running; starting now at tcp:5037
           * daemon started successfully
[  +20 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[  +24 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[ +467 ms] Launching lib/main.dart on Linux in debug mode...
[  +17 ms] Building Linux application...
[   +1 ms] executing: make -C
/home/this/AndroidStudioProjects/flutter-desktop-embedding/example/linux
BUILD=debug
[ +157 ms] make: Entering directory
'/home/this/AndroidStudioProjects/flutter-desktop-embedding/example/linux'
[        ] /home/this/flutter/packages/flutter_tools/bin/tool_backend.sh
linux-x64 debug
[+8688 ms] mkdir -p /home/this/AndroidStudioProjects/flutter-desktop-embedding/example/linux/../build/linux/obj/debug
[        ] clang++  -std=c++14 -Wall -Werror  -Iflutter/ephemeral
-I/home/this/AndroidStudioProjects/flutter-desktop-embedding/example/linux/flutter/ephemeral/cpp_client_wrapper_glfw/include  -MMD -c main.cc
-o /home/this/AndroidStudioProjects/flutter-desktop-embedding/example/linux/../build/linux/obj/debug/main.o
[+4246 ms] mkdir -p /home/this/AndroidStudioProjects/flutter-desktop-embedding/example/linux/../build/linux/obj/debug/flutter
[        ] clang++  -std=c++14 -Wall -Werror  -Iflutter/ephemeral
-I/home/this/AndroidStudioProjects/flutter-desktop-embedding/example/linux/flutter/ephemeral/cpp_client_wrapper_glfw/include  -MMD -c
flutter/generated_plugin_registrant.cc -o
/home/this/AndroidStudioProjects/flutter-desktop-embedding/example/linux/../build/linux/obj/debug/flutter/generated_plugin_registrant.o
[ +304 ms] mkdir -p /home/this/AndroidStudioProjects/flutter-desktop-embedding/example/linux/../build/linux/debug
[        ] clang++  -std=c++14 -Wall -Werror  -Iflutter/ephemeral
-I/home/this/AndroidStudioProjects/flutter-desktop-embedding/example/linux/flutter/ephemeral/cpp_client_wrapper_glfw/include
/home/this/AndroidStudioProjects/flutter-desktop-embedding/example/linux/../build/linux/obj/debug/main.o
/home/this/AndroidStudioProjects/flutter-desktop-embedding/example/linux/../build/linux/obj/debug/flutter/generated_plugin_registrant.o
/home/this/AndroidStudioProjects/flutter-desktop-embedding/example/linux/../build/linux/obj/debug//home/this/AndroidStudioProjects/flutter-des
ktop-embedding/example/linux/flutter/ephemeral/cpp_client_wrapper_glfw/flutter_window_controller.o
/home/this/AndroidStudioProjects/flutter-desktop-embedding/example/linux/../build/linux/obj/debug//home/this/AndroidStudioProjects/flutter-des
ktop-embedding/example/linux/flutter/ephemeral/cpp_client_wrapper_glfw/plugin_registrar.o
/home/this/AndroidStudioProjects/flutter-desktop-embedding/example/linux/../build/linux/obj/debug//home/this/AndroidStudioProjects/flutter-des
ktop-embedding/example/linux/flutter/ephemeral/cpp_client_wrapper_glfw/engine_method_result.o
-L/home/this/AndroidStudioProjects/flutter-desktop-embedding/example/linux/../build/linux/debug/lib -lflutter_linux_glfw
-Wl,-rpath=\$ORIGIN/lib -o
/home/this/AndroidStudioProjects/flutter-desktop-embedding/example/linux/../build/linux/debug/flutter_desktop_example
[ +447 ms] mkdir -p /home/this/AndroidStudioProjects/flutter-desktop-embedding/example/linux/../build/linux/debug/data
[        ] rsync -rpu --delete /home/this/AndroidStudioProjects/flutter-desktop-embedding/example/linux/../build/flutter_assets
/home/this/AndroidStudioProjects/flutter-desktop-embedding/example/linux/../build/linux/debug/data
[  +30 ms] make: Leaving directory '/home/this/AndroidStudioProjects/flutter-desktop-embedding/example/linux'
[  +19 ms] Building Linux application... (completed in 13,9s)
[+1054 ms] Error waiting for a debug connection: Bad state: No element
[   +2 ms] Error launching application on Linux.
[   +5 ms] "flutter run" took 18.836ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:27:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:559:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:625:18)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:521:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:511:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:338:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:289:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:232:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:65:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:63:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:65:24)
#37     run (package:flutter_tools/runner.dart:52:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///home/this/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

**Comment by topisani** [comment]
Same issue, also manjaro. When running in gdb, i get the following segfault:
```
Thread 8 "io.flutter.io" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe2ffd700 (LWP 1685)]
0x00007ffff7835794 in GrGLExtensions::init(GrGLStandard, GrGLFunction<unsigned char const* (unsigned int)>, GrGLFunction<unsigned char const* (unsigned int, unsigned int)>, GrGLFunction<void (unsigned int, int*)>, GrGLFunction<char const* (void*, int)>, void*) () from /home/topisani/dev/flutter-desktop-embedding/example/build/linux/debug/lib/libflutter_linux_glfw.so
```

**Comment by pchampio** [comment]
Same issue, but on [go-flutter](https://github.com/go-flutter-desktop/go-flutter), also manjaro.
```log
Thread 13 "io.flutter.io" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd8cce700 (LWP 26433)]
0x00007ffff74b1c74 in GrGLExtensions::init(GrGLStandard, GrGLFunction<unsigned char const* (unsigned int)>, GrGLFunction<unsigned char const* (unsigned int, unsigned int)>, GrGLFunction<void (unsigned int, int*)>, GrGLFunction<char const* (void*, int)>, void*) ()
   from /home/pchampio/lab/flutter/go-flutter-example/text_demo/go/build/outputs/linux/libflutter_engine.so
```

**Comment by topisani** [comment]
I just recently installed Manjaro, so I don't have the old package on my system. Could you shoot me a link?

**Comment by pchampio** [comment]
Uhhfff, I've seach Dichotomic which package was causing this issue.
It's `lib32-libglvnd` and `libglvnd`!!!

You need to downgrade:
```log
[2020-01-12T00:01:01+0100] [ALPM] upgraded lib32-libglvnd (1.2.0-3 -> 1.3.0-1)
[2020-01-12T00:01:01+0100] [ALPM] upgraded libglvnd (1.2.0-5 -> 1.3.0-1)
```
> I just recently installed Manjaro, so I don't have the old package on my system. Could you shoot me a link?

Please use the something like: https://wiki.manjaro.org/index.php?title=Downgrading_packages, don't trust people^^

**Comment by stuartmorgan** [comment]
The crash is in Skia, so it seems like this is either a Skia bug, or in (based on the above) libglvnd.

@topisani I would suggest getting a backtrace in addition to the crash itself, then filing a Skia bug for further investigation by the Skia team as a starting point; they would better be able to tell if it's an issue in Skia or in the library.

**Comment by stuartmorgan** [comment]
This is definitely the same crash as https://github.com/flutter/flutter/issues/47954. Closing in favor of that bug, since it's all within the GLFW embedding that's in the engine rather than code at the level of this repository.

**Comment by Roger28** [comment]
> Uhhfff, I've seach dichotomic-ly which package was causing this issue.
> It's `lib32-libglvnd` and `libglvnd`!!!
> 
> You need to downgrade them to `1.2.X`:
> 
> ```
> [2020-01-12T00:01:01+0100] [ALPM] upgraded lib32-libglvnd (1.2.0-3 -> 1.3.0-1)
> [2020-01-12T00:01:01+0100] [ALPM] upgraded libglvnd (1.2.0-5 -> 1.3.0-1)
> ```
> 
> > I just recently installed Manjaro, so I don't have the old package on my system. Could you shoot me a link?
> 
> Please use the something like: https://wiki.manjaro.org/index.php?title=Downgrading_packages, don't trust peoples with your package binaries^^

This solution solved the problem, thank you bro.

**Comment by lycstar** [comment]
@pchampio Solved,thank you!
