### ISSUE TITLE
File picker dialog does not block interaction with the Flutter app underneath

### ISSUE THREAD

**Issue by emshack** [google/flutter-desktop-embedding#633]
**Describe the bug**
My desktop app is using the file_chooser plugin. On a Mac desktop, when I bring up a native dialog via that plugin (eg. showOpenPanel, showSavePanel), my expectation is that until I closed that dialog, I would not be able to interact with the rest of the app. What I'm seeing currently is that I am able to click back into the main app window and interact freely, including both mouse and keyboard events, while the file chooser dialog is still open.

**Doctor Output**
```
[✓] Flutter (Channel unknown, v1.13.3-pre.9, on Mac OS X 10.14.6 18G2022, locale en-US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Community Edition (version 2019.1.2)
[✓] Connected device (1 available)
```

**Comment by stuartmorgan** [comment]
It's supposed to be a window-modal sheet; something regressed here. I'm seeing it as a standalone window in `testbed`, which it definitely didn't used to be.
