### ISSUE TITLE
[Linux] Support EventChannel API

### ISSUE THREAD

**Issue by Kurun-pan** [google/flutter-desktop-embedding#649]
**Describe Request**

Hi there,

Currently, it looks like Plugin doesn't support EventChannel API. Do you have any plans to support it? I can contribute with Flutter's Linux support, how?

**Comment by stuartmorgan** [comment]
You'll need to file this in [the Flutter bug tracker](https://github.com/flutter/flutter/issues), as plugin APIs are part of Flutter itself, not this repository. I do expect that the C++ plugin API should support EventChannel at some point, it just hasn't been implemented (and nobody has requested it yet, so there's not an existing issue tracking it).

> I can contribute with Flutter's Linux support, how?

I'm not sure if you mean EventChannel support specifically, or Linux support in general. If the former, please feel free to implement it and send a PR using [the standard process for contributing to the Flutter engine](https://github.com/flutter/engine/blob/master/CONTRIBUTING.md). If the latter, the best approach would be finding issues either in this repository or the Flutter repository that you are interested in working on, and posting a comment there to indicate you would like to work on it. You can @-mention me to ensure that I see it and can provide guidance/feedback as necessary.

**Comment by long1eu** [comment]
@Kurun-pan did you open an issues for this?
