### ISSUE TITLE
[linux] Text input plugin broken in master branch

### ISSUE THREAD

**Issue by awdavies** [google/flutter-desktop-embedding#65]
Flutter version: bf531ba87119cb2292ec3bb4c88231c15e115a6b
Flutter engine version: 15ddcd448d972381cfa9c93c041dfa31a2061e0c

When building a binary that should run the `examples/flutter_gallery` app in the embedder, text input fails to function correctly.  This should be investigated after #61 has landed to prevent spurious bugs/conflicts from merging.

**Comment by stuartmorgan** [comment]
It still works on macOS, so it doesn't seem to be a protocol change.

**Comment by awdavies** [comment]
Right.  I went through and checked a few things out (changing line breaks, indenting, etc) but all for naught.  I'm pretty stumped on this one.

**Comment by stuartmorgan** [comment]
I'll try bisecting with older Flutter trees next week to see if I can figure out if this was indeed broken by a Flutter change, and if so narrow down the range.

**Comment by stuartmorgan** [comment]
Seems to be broken back to at least Flutter 2e24351fb1a329cbf279cd87e1b647898e609262 (May 17th engine roll), which is as far back as prebuilt engines go. Further bisecting will require building the engine, so at that point it's probably easier to just debug trunk unfortunately.
