### ISSUE TITLE
MacOS frame rate isn't synced to display

### ISSUE THREAD

**Issue by luigi-rosso** [google/flutter-desktop-embedding#656]
I'm running on a 120hz monitor, I've scheduled a persistent frame callback and can see that I get ~60fps. It would be great if Flutter could use something like CADisplayLink to sync frame rendering with the display. 

Gist of a simple app showing this: https://gist.github.com/luigi-rosso/0e3ed273e52764bf1d7bdacca49cccd2

![image](https://user-images.githubusercontent.com/454182/73402560-713a4200-42a2-11ea-87b3-2680aea714c3.png)

I can see in various [sites](https://jsfiddle.net/greggman/ULxVp/), apps, and games that the display is actually refreshing at 120hz.
![image](https://user-images.githubusercontent.com/454182/73402973-4dc3c700-42a3-11ea-90d0-9c30b0274a5b.png)

**Comment by stuartmorgan** [comment]
Rendering is controlled by the embedding, which is part of the Flutter engine, so you'll need to file this in the [Flutter issue tracker](https://github.com/flutter/flutter/issues). (Unfortunately I can't move bugs between the repos.)
