### ISSUE TITLE
[linux/windows] Add support for StandardMethodCodec

### ISSUE THREAD

**Issue by stuartmorgan** [google/flutter-desktop-embedding#67]
Currently the native plugin APIs are hard-coded to use JSON, so the Dart side must use JSONMethodCodec. We should support all the codec options that are supported on mobile, and a way to specify the codec to use for a given plugin.

**Comment by stuartmorgan** [comment]
It's now possible to use custom method codecs. Leaving this open (and adjusting title) for the remaining work of implementing StandardMethodCodec. It should be straightforward in ObjC, but on the C++ side will involve creating a typed object hierarchy or something similarly inspectable containing all the types supported by the codec.

**Comment by gedw99** [comment]
DO you think its possible to  support golang ?
I currently use golang to write plugins for Flutter mobile.

See this:
https://github.com/adieu/flutter_go
Its awesome.

**Comment by stuartmorgan** [comment]
If someone wants to write a plugin like that one for use on desktop, they are welcome to do so, but that has nothing to do with this issue.

**Comment by gedw99** [comment]
@stuartmorgan Ok thanks for the clarification.

**Comment by pauldemarco** [comment]
It seems like some recent commits are allowing for this issue to be worked on.

Is this on the docket any time soon?

**Comment by stuartmorgan** [comment]
> It seems like some recent commits are allowing for this issue to be worked on.

This hasn't been blocked since #110, actually; the recent (and remaining) plugin refactors are tangential to codecs.

> Is this on the docket any time soon?

I have no plans to work on this in the foreseeable future, since so far we haven't encountered any cases where we need StandardMethodCodec to unblock important functionality. I'm happy to review patches from anyone interested in working on it though.

**Comment by pauldemarco** [comment]
I would like to start working on Firebase auth and RTDB for Linux, using C++ sdk, but unfortunately blocked on this issue.

**Comment by pulyaevskiy** [comment]
@pauldemarco

Sorry for off topic but which cpp sdk you’re planning to use for auth? The official one says it works for iOS and Android only with limited support for desktop (mac)

**Comment by pauldemarco** [comment]
@pulyaevskiy 

https://firebase.google.com/docs/auth/cpp/start

Can you link me to the clause about the limited support? I can't seem to find it...

**Comment by pulyaevskiy** [comment]
Here are a few references:

Top of the page https://firebase.google.com/docs/cpp/setup

> The Firebase C++ SDK provides a C++ interface on top of Firebase for iOS and Android.

And this section: https://firebase.google.com/docs/cpp/setup#desktop_workflow_implementations_beta_feature_

![image](https://user-images.githubusercontent.com/441756/49244699-482fd000-f3c5-11e8-8745-5077dba5ce63.png)

**Comment by stuartmorgan** [comment]
If you'd like to continue that discussion, https://groups.google.com/forum/#!topic/flutter-desktop-embedding-dev/QPz9quNmB3o would be a much better place.

Returning to the topic of this issue: as I said I'm happy to review patches adding Standard{Message,Method}Codec support. A general approach for a C++ implementation is outlined above.

**Comment by stuartmorgan** [comment]
With the migration to `flutter/engine`, which included switching to using the relevant iOS classes, StandardMethodCodec is now supported for macOS. Leaving open for Linux and Windows.

**Comment by stuartmorgan** [comment]
Moved to https://github.com/flutter/flutter/issues/30670
