### ISSUE TITLE
[window_size] Allow toggling full screen

### ISSUE THREAD

**Issue by emshack** [google/flutter-desktop-embedding#679]
Currently, via the window size plugin one can set a window frame, but it appears this frame cannot take up the full screen, as at least on mac the menu bar and app icon bar will remain visible. It would be great to have a way to toggle in and out of full-screen mode programmatically, to for example enable a keyboard shortcut that does this.

**Comment by stuartmorgan** [comment]
Yes, full screen is something there have been questions about from time to time for quite a while. Definitely something that should go in window_size in the short term.

**Comment by BasedMusa** [comment]
How can I set window frame max and minimum size on macOS?

**Comment by stuartmorgan** [comment]
@BasedMusa If you have issues with the existing functionality of the `window_size` plugin, please file a new issue rather than commenting in an unrelated issue.

**Comment by stuartmorgan** [comment]
Per [the updated scope](https://github.com/google/flutter-desktop-embedding/blob/master/plugins/window_size/README.md#scope) of this plugin, this isn't something that will be added.
