### ISSUE TITLE
The code execution can not proceed because MSVCP140.dll was not found.

### ISSUE THREAD

**Issue by hariom-dev** [google/flutter-desktop-embedding#681]
I've facing issue when windows build upload on another windows system It'll give error
"The code execution cannot proceed because MSVCP140.dll was not found."
Please help!

**Comment by gsx123** [comment]
Same problem. To fix it , I just put MSVCP140.dll in the folder with the exe file

**Comment by hariom-dev** [comment]
> Same problem. To fix it , I just put MSVCP140.dll in the folder with the exe file

where you get the MSVCP140.dll file?

**Comment by hariom-dev** [comment]
Actually this not only the MSVCP140.dll file is missing.When i put this file with build It'll return another file is not found, May be it's a whole error about the C++ extension. But I don't know how to we put the whole c++ extension in build. Suppose i put whole C++ extension on the build size exceeded.
I not understand what should I do about that.

**Comment by rubgithub** [comment]
@hariom-dev get here #51119 `DebugDllEmbedding.rar`

**Comment by stuartmorgan** [comment]
Duplicate of #587

**Comment by Slihao** [comment]
> 实际上，这不仅是MSVCP140.dll文件丢失了，当我将这个文件与Build放在一起时，它会返回另一个文件，可能是C++扩展名的一个整体错误。但我不知道如何将整个c++扩展放在构建中。假设我将整个C++扩展放在超出的构建大小上。
> 我不明白该怎么办。

Did you do it? I had the same problem
