### ISSUE TITLE
Flutter Desktop (Windows) and Keyboard Number Pad

### ISSUE THREAD

**Issue by a344254** [google/flutter-desktop-embedding#683]
I don't know if this is a flutter-desktop-embedding thing, or just a pure flutter thing, but I have something strange going on.  I cloned the flutter-desktop-embedding repository then added a textfield to the scaffold, and noticed that when entering numbers via the number pad on a desktop keyboard, it's sending the numbers along with the functions of the keys.  For example, the 4 key sends a left arrow function, then types the letter 4.  The 6 key sends a right arrow function, then the number 6.  The 1 key sends the "end" function to go to the end of the line, then enters the number 1.  If I use the number keys above the qwerty portion of the keyboard, the numbers function normally.

This is running on Windows 10, with either a physical or on-screen keyboard

[√] Flutter (Channel master, v1.15.4-pre.155, on Microsoft Windows [Version 10.0.17763.1039], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.3.1)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.42.1)
[!] Proxy Configuration
    ! NO_PROXY is not set
[√] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by stuartmorgan** [comment]
Please file this in the Flutter issue tracker; key handling is below the level of this repository.

There is a pending overhaul of key handling that may address this, but it would be good to get it filed in the Flutter repo so that it's part of the things we make sure to test with the new implementation.

**Comment by a344254** [comment]
OK done https://github.com/flutter/flutter/issues/51431
