### ISSUE TITLE
Add limiter function for max memory and cpu count 

### ISSUE THREAD

**Issue by 411c0d3d** [google/flutter-desktop-embedding#688]
**Describe Request**

Apps sometimes crash leading to draining of resources, would be practical to limit memory and cpu count from main.cc file, similar to VM emulator or so.

**Comment by stuartmorgan** [comment]
> Apps sometimes crash leading to draining of resources

I'm not sure what this means; an app that crashes is no longer using either memory or CPU.

> would be practical to limit memory and cpu count from main.cc file

main.cc isn't responsible for any meaningful memory allocation, so I don't understand what you are proposing here. As for CPU, arbitrarily capping it at the level of the main runloop would cause user-visible jank, and I'm not clear what problem you would be solving.

This is not something we'll be adding to the template. You're always welcome to edit main.cc in your own application, so if you feel there are limits you can add there that are useful in your specific case, that's always available as an option.
