### ISSUE TITLE
flutter driver and bottom sheet Pop-up handling

### ISSUE THREAD

**Issue by AGdivya** [google/flutter-desktop-embedding#696]
I am using flutter driver for testing my mobile application, facing issues while handling bottom sheet pop up.
for below screen When I am clicking on star or contact name to mark as favourite , I am getting bottom sheet pop up with options "Add to Favourites" and "delete Account"
But when I am verifying that is this Pop-up open, I am not able to verify it.
Please, someone, help me in it.
What I will use to handle this kind of situation.
I have been sharing my code snippets below please check and let me know what updates required here.
![Screenshot_1584552453](https://user-images.githubusercontent.com/48939088/76991113-12727a00-696f-11ea-87b7-879702cf4882.png)
**My page file where variables and method is  declared
<img width="1351" alt="Screenshot 2020-03-18 at 10 39 25 PM" src="https://user-images.githubusercontent.com/48939088/76991514-ba884300-696f-11ea-93a5-dfc1fac5dc40.png">
**
```
final SerializableFinder addFavouriteButtonKey =
      find.byValueKey('add_favourite_button');

  final SerializableFinder payFormonth = find.descendant(
      of: find.byValueKey('add_favourite_button'),
      matching: find.byType('Text'),
      firstMatchOnly: true);

  final SerializableFinder fav = find.text('Add to Favorites');
  ContactPage(FlutterDriver _driver) {
    driver = _driver;

Future<void> addToFavPopUpOpen() async {
    driver.waitFor(fav);
    await FlutterDriverUtils.tap(driver, fav);
    //return FlutterDriverUtils.isPresent(payFormonth, driver);
  }

  // Future<String> verifyTextOfPopUp() async {
  //   return FlutterDriverUtils.getText(driver, addFavouriteButtonKey);
  // }

  Future<void> clickOnFavourites() async {
    await FlutterDriverUtils.tap(driver, addFavouriteButtonKey);
  }
```

**Step Defination**

```
class VerifyPopUpPage extends WhenWithWorld<FlutterWorld> {
  VerifyPopUpPage()
      : super(StepDefinitionConfiguration()
          ..timeout = const Duration(seconds: 60));
  @override
  Future<void> executeStep() async {
    final ContactPage contactPage = ContactPage(world.driver);
    await contactPage.addToFavPopUpOpen();
    // if (await contactPage.addToFavPopUpOpen()) {
    //   print('########added ####');
    //   //await contactPage.verifyTextOfPopUp();
    // }
    print('%%%%%%%%% verify text %%%%%%%');
  }
```

**Comment by stuartmorgan** [comment]
This project is about building desktop applications with Flutter. You are looking for [Flutter's issue tracker](https://github.com/flutter/flutter/issues), not this one.
