### ISSUE TITLE
Keyboard issue when use Textfield

### ISSUE THREAD

**Issue by bing0ye** [google/flutter-desktop-embedding#698]
When I use textfield to input text, the keyboard association word position is displayed in the lower left corner of the screen. It should be displayed near the input box

**Comment by stuartmorgan** [comment]
Text input behavior is part of the framework and the engine, which are not part of this repository; you'll need to file this is the Flutter issue tracker.

When you file it there, please include more information:
- Your target platform (I'm not sure which of the three desktop OSes you're reporting this issue for)
- Exact repro steps (it's not clear to me what "the keyboard association word position" is, or how one would cause it to be displayed)
- Ideally a screenshot, to clarify what you are describing.
