### ISSUE TITLE
macOS Makefile

### ISSUE THREAD

**Issue by gedw99** [google/flutter-desktop-embedding#70]
any chance we could get a make file for MacOS, like Linux has ?

Oh and the linux one is quite complex make file structure. The macOS one can be much simpler 

Will make it easier to keep up with things changing.

thanks...

**Comment by stuartmorgan** [comment]
> any chance we could get a make file for MacOS, like Linux has ?

This seems like it's the same fundamental request as issue #48, so closing as a dup of that. As noted there, if you just want a workflow that doesn't involve launching Xcode you can easily make your own Makefile to invoke xcodebuild in the short term.

> Oh and the linux one is quite complex make file structure.

Patches welcome if you have specific improvements to simplify the makefile structure (although I hope to move to something more maintainable in the future; likely gn).

> Will make it easier to keep up with things changing.

Can you elaborate on this? I'm not sure what you mean.
