### ISSUE TITLE
Is it possible to acces cmd.exe on windows?

### ISSUE THREAD

**Issue by esDotDev** [google/flutter-desktop-embedding#702]
On Linux we are able to open url's using a simple io.Process call:
`io.Process.run("xdg-open", [ url, ])`

But trying to do the equivalent thing ("start $url") on windows fails with:
_The system cannot find the file specified._

I'm guessing we need the path of cmd.exe, which is located at _%ComSpec%_. Tried doing a 'echo _%ComSpec%_, but getting the same error. Also tried hard-coding the path, but no success.

**Comment by stuartmorgan** [comment]
Questions about how to use Dart APIs like `Process` should go to a help forum like StackOverflow; it's unrelated to this repository.

That said, if what you want is to launch a URL this repository has [url_launcher implementations for desktop](https://github.com/google/flutter-desktop-embedding/tree/master/plugins/flutter_plugins/url_launcher_fde).

**Comment by esDotDev** [comment]
Yes we're aware of that option, this is more of a general question of how you might accomplish this, as it has many applications. Just thought you might know. I've posted on SO, but the number of Dart developers that know this stuff is very low.

**Comment by stuartmorgan** [comment]
All the more reason to put the question in a relevant, popular location, where someone else could actually find and benefit from the answer in the future.

**Comment by esDotDev** [comment]
Sure, assuming it gets answered! To be clear, you don't know the answer off hand correct?
