### ISSUE TITLE
Pixelated icon rendering on windows

### ISSUE THREAD

**Issue by esDotDev** [google/flutter-desktop-embedding#708]
Using something like `Icon(Icons.star)` on Windows is rendering very pixelated compared to the other platforms.

Here's Linux left, and Window right, and then enlarged:
![Photoshop_2020-04-02_13-33-56](https://user-images.githubusercontent.com/736973/78294012-d3a00080-74e6-11ea-9d63-4dc1c7f20d14.png)

**Comment by stuartmorgan** [comment]
As it says both [in the README](https://github.com/google/flutter-desktop-embedding#feedback) and in the bug template, the only things that should be filed here at this point are bugs about the plugins in this repository.
