### ISSUE TITLE
How do permissions work for Windows?

### ISSUE THREAD

**Issue by GroovinChip** [google/flutter-desktop-embedding#715]
I would like to know how permissions work on Flutter Desktop, specifically for Windows. Do we have default access to things like internet, etc? If not, how do we enable them?

**Comment by stuartmorgan** [comment]
Please see https://github.com/google/flutter-desktop-embedding#feedback and https://groups.google.com/g/flutter-desktop-embedding-dev/c/XRwVxwpWo6g. Closing as this isn't related to the FDE plugins.

**Comment by GroovinChip** [comment]
Thanks @stuartmorgan, just FYI your second link errors out

**Comment by stuartmorgan** [comment]
Looks like the version I copied had been redirected. Should be fixed now.

**Comment by GroovinChip** [comment]
That worked, thanks
