### ISSUE TITLE
any plans for supporting simple audio play plugin for windows/linux? (mac os works)

### ISSUE THREAD

**Issue by softmarshmallow** [google/flutter-desktop-embedding#719]
simple audio play plugin request.

android/ios/mac works fine, but i cannot find any way to play sound on windows/ or linux.

**Comment by stuartmorgan** [comment]
No; see [the readme](https://github.com/google/flutter-desktop-embedding/tree/master/plugins#desktop-plugins) for the explanation of the types of plugins that would (temporarily) be developed in this repository. An audio player plugin isn't part of either category.
