### ISSUE TITLE
GLFW error thrown when initializing on embedded Linux Distribution.

### ISSUE THREAD

**Issue by nmcain** [google/flutter-desktop-embedding#725]
I am trying to get the desktop embedder to run on an embedded LFS system, but when I run the executable, it throws GLFW error 65545: EGL: Failed to find a suitable EGLConfig. This, in turn, causes a segmentation fault and stops the application from running.

I have included GLFW, Mesa, and OpenGL in the system package list, what would be the root of this issue?

**Comment by stuartmorgan** [comment]
Please read [the Feedback section of the README](https://github.com/google/flutter-desktop-embedding/blob/master/README.md#feedback). This issue is not related to the code in this repository.

**Comment by nmcain** [comment]
I'm not so sure it is. This is the code for the desktop embedder right?
