### ISSUE TITLE
[window_size] setWindowFrame doesn't seem to set "left" correctly

### ISSUE THREAD

**Issue by DanTup** [google/flutter-desktop-embedding#727]
I don't know if this is related to having two screens (or one being ultrawide), but if I run this code (expected to put the window in the top left corner), there's quite a gap from the left:

```dart
const width = 1280.0;
const height = 720.0;

final window = await window_size.getWindowInfo();
if (window.screen != null) {
  final left = 0.0;
  final top = 0.0;
  final frame = Rect.fromLTWH(left, top, width, height);
  window_size.setWindowFrame(frame);

  window_size.setWindowMinSize(Size(width, height));
  window_size.setWindowMaxSize(Size(width, height));
}
```

![Screenshot 2020-05-10 at 16 04 47](https://user-images.githubusercontent.com/1078012/81502790-00121e00-92d8-11ea-8c7e-197499f3a1db.png)

It's only only when I set 0 - if I try to center it, it also ends up way off to the right - I just used zero to simplify the example.

I'm running on macOS Catalina, on a 16" MacBook Pro, with an LG Ultrawide external monitor.

**Comment by stuartmorgan** [comment]
What is the `frame` of `window.screen`?

This is a pretty simple passthrough to the OS, so it's unlikely that this is a plugin bug.

**Comment by stuartmorgan** [comment]
Closing due to lack of response.
