### ISSUE TITLE
flutter linux  desktop中文字体显示方块

### ISSUE THREAD

**Issue by AndromedaX7** [google/flutter-desktop-embedding#730]
**Describe the bug**
Please provide a clear and concise description of the bug, including steps to reproduce, and, if relevant, screenshots.
![2020-05-16 16-26-53 的屏幕截图](https://user-images.githubusercontent.com/38732113/82114918-1dd8fa80-9792-11ea-8adf-52a0635ce949.png)

**Doctor Output**
Please provide the output of `flutter doctor -v`:
```
```
[✓] Flutter (Channel master, 1.19.0-2.0.pre.73, on Linux, locale zh_CN.UTF-8)
    • Flutter version 1.19.0-2.0.pre.73 at /home/mi/flutter
    • Framework revision 32547dcc7e (15 小时前), 2020-05-15 10:42:37 -0700
    • Engine revision 50e55cf69e
    • Dart version 2.9.0 (build 2.9.0-9.0.dev 2676764792)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/mi/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/mi/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Linux toolchain - develop for Linux desktop
    • clang++ 6.0.0
    • GNU Make 4.1

[✓] Android Studio (version 3.6)
    • Android Studio at /home/mi/android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.10.1

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.0/8,::1,127.0.0.1
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[✓] Connected device (1 available)
    • Linux • Linux • linux-x64 • Linux

**Comment by Youngermaster** [comment]
Could you provide more information? I mean the code, just watching that we may that the fonts that are used weren't "installed" correctly on the Flutter project or even in Ubuntu.

**Comment by Youngermaster** [comment]
Could you provide more information? I mean the code, just watching that we may assume that the fonts that are used weren't "installed" correctly on the Flutter project or even in Ubuntu.

**Comment by stuartmorgan** [comment]
Please read [the Feedback section of the README](https://github.com/google/flutter-desktop-embedding/blob/master/README.md#feedback). This issue is not related to the code in this repository.
