### ISSUE TITLE
[window_size] Add bring window to front capability?

### ISSUE THREAD

**Issue by domesticmouse** [google/flutter-desktop-embedding#761]
I have a desire to bring a Flutter desktop app window to the front of the stack (in response to an OAuth flow completion). I believe on macOS I need to use NSApp's [`activate(ignoringOtherApps:)`](https://developer.apple.com/documentation/appkit/nsapplication/1428468-activate). I'm assuming Linux and Windows have equivalent APIs.

Is this a reasonable thing to add? And is `window_size` the most appropriate place?

**Comment by stuartmorgan** [comment]
It sounds like you want to switch back to the app, which isn't exactly window-specific; I think a custom method channel or separate plugin would be a better option here. Do you expect to need this in multiple applications?

**Comment by domesticmouse** [comment]
Any desktop app that does OAuth2 or similar authentication using a browser to compete the auth flow will need this capability. Given that covers pretty much all APIs these days, I think it will become a recurring theme.

**Comment by stuartmorgan** [comment]
> Any desktop app that does OAuth2 or similar authentication using a browser to compete the auth flow will want this capability.

If they use a custom URL scheme for their auth callback, that should be handled automatically.

**Comment by Nealsoni00** [comment]
@stuartmorgan or @domesticmouse  I can't seem to find any examples on how to register a custom URL scheme on windows or MacOS to receive the OAuth2 callback? Were you able to get an OAuth2 flow working on desktop?

A use-case of adding the window to the front of the stack (that is useful to me) is to bring the app (or a dedicated window of the app) to the front of the screen when a notification comes in. Any advice on how to approach doing that would be super helpful.

**Comment by stuartmorgan** [comment]
See https://codelabs.developers.google.com/codelabs/flutter-github-graphql-client/index.html

**Comment by stuartmorgan** [comment]
Per [the updated scope](https://github.com/google/flutter-desktop-embedding/blob/master/plugins/window_size/README.md#scope) of this plugin, this isn't something that will be added.
