### ISSUE TITLE
support FlutterIsolate enable plugin usage in isolate

### ISSUE THREAD

**Issue by Nailik** [google/flutter-desktop-embedding#768]
Hi,
i wanted to request a Windows version of [FlutterIsolate ](https://pub.dev/packages/flutter_isolate) because there is no other possibility to call Native Code via Plugins inside an isolate. 
According to [Flutter 13937](https://github.com/flutter/flutter/issues/13937) this will not be resolved within flutter in the near feature so it would be nice if the plugin would be ported to Windows. For many devs it seems to be a showstopper by now.

**Comment by stuartmorgan** [comment]
See https://github.com/google/flutter-desktop-embedding/tree/master/plugins#desktop-plugins. Third-party plugins are out of scope here.

> it would be nice if the plugin would be ported to Windows

The place to request Windows support for a third-party plugin is that plugin's issue tracker.
