### ISSUE TITLE
[window_size] Add an option to prevent all resizing

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [google/flutter-desktop-embedding#774]
**Describe Request**
I wanna know how to set a window size that can't be changed. or Be changed at a locked aspect ratio

**Comment by YazeedAlKhalaf** [comment]
This is a temporary solution I made today:

```dart
import 'dart:io';

import 'package:flutter/widgets.dart';
import 'package:window_size/window_size.dart' as window_size;
import 'package:window_size/window_size.dart';

class WindowSizeService {
  static const double width = 800;
  static const double height = 500;

  Future<PlatformWindow> _getPlatformWindow() async {
    return await window_size.getWindowInfo();
  }

  void _setWindowSize(PlatformWindow platformWindow) {
    final Rect frame = Rect.fromCenter(
      center: Offset(
        platformWindow.frame.center.dx,
        platformWindow.frame.center.dy,
      ),
      width: width,
      height: height,
    );

    window_size.setWindowFrame(frame);

    setWindowTitle(
      'Flutter Installer for ${Platform.operatingSystem}',
    );

    if (Platform.isMacOS) {
      window_size.setWindowMinSize(Size(width, height));
      window_size.setWindowMaxSize(Size(width * 2, height * 2));
    }
  }

  Future<void> initialize() async {
    PlatformWindow platformWindow = await _getPlatformWindow();

    if (platformWindow.screen != null) {
      if (platformWindow.screen.visibleFrame.width != 800 ||
          platformWindow.screen.visibleFrame.height != 500) {
        _setWindowSize(platformWindow);
      }
    }
  }

  void setWindowTitle(String title) {
    window_size.setWindowTitle(title);
  }
}
```

Put the `initialize` method in the main function
Put the `initialize` method in every `build` method. Not the best solution but works.

To change the width and height, just change the variables at the top of the method 😊

I hope it helps 🚀

**Comment by stuartmorgan** [comment]
If you want the window to be permanently unresizable a much, much better solution would be to just add the necessary native code to each runner to make the window unresizable. It's probably only a line or two on each platform.

**Comment by YazeedAlKhalaf** [comment]
My Problem is that I don't have experience in Native code of any platform. So I used what I had in hand. Although I might do a google search to figure it out. Meanwhile, I guess this is great!

**Comment by esDotDev** [comment]
Some behavior we noticed today:
* On Ubuntu, setting minSize prevents the window from being resized, we need to assign a large maxSize in order to enable resize.
* On Windows, minSize just enforces min size (which seems expected). 
* Haven't tested on OSX

The hope would be that whatever the behavior is, it's the same on all platforms.

**Comment by stuartmorgan** [comment]
> * On Ubuntu, setting minSize prevents the window from being resized, we need to assign a large maxSize in order to enable resize.

Please file a new issue. That's not the correct behavior, but it's unrelated to this issue which is requesting fully disabling resize (which is not done via min and max size, but by separate window flags)

**Comment by Tembocs** [comment]
How far has this plugin gone? Can it be used in Flutter beta or master branches?

**Comment by stuartmorgan** [comment]
Per [the updated scope](https://github.com/google/flutter-desktop-embedding/blob/master/plugins/window_size/README.md#scope) of this plugin, this isn't something that will be added.
