### ISSUE TITLE
how to create sqflite db in folder location of application on windows desktop

### ISSUE THREAD

**Issue by amasahara** [google/flutter-desktop-embedding#777]
I try make an windows desktop application that connect with sqflite_ffi but don't know how to create this with custom path to current application folder, it always go to .dartool folder.

**Comment by stuartmorgan** [comment]
> For bug reports and feature requests *related to the plugins in this repository*, please file issues here.

This is not related to any of the FDE plugins, or is it a bug report or feature request. https://flutter.dev/community has a variety of resources for questions.
