### ISSUE TITLE
CMake Error at flutter/generated_plugins.cmake:13 (add_subdirectory)

### ISSUE THREAD

**Issue by 926** [google/flutter-desktop-embedding#778]
Hi,
deleted windows file
$ flutter clean
$ flutter create .
$ flutter run -d windows

But I still get the error below :

CMake Error at flutter/generated_plugins.cmake:13 (add_subdirectory):
  The source directory

    C:/.../windows/flutter/ephemeral/.plugin_symlinks/path_provider_fde/windows

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:51 (include)

**Comment by 926** [comment]
https://github.com/flutter/flutter/issues/62059

**Comment by stuartmorgan** [comment]
You can't use old versions of plugins with the latest master. As it says in the README:
> Breaking changes in Flutter for desktop are still relatively common.
