### ISSUE TITLE
[file_chooser] Can't build or run Mac app

### ISSUE THREAD

**Issue by matthew-carroll** [google/flutter-desktop-embedding#790]
I can no longer build or run a Mac app after adding and configuring `file_chooser`. This may be a Mac/XCode issue unrelated to the plugin, but I can't be sure because it happened after configuring the plugin.

This was the series of the events:

1 - Created a new Mac app and got it running.

2 - Added the `file_chooser` plugin. The app still ran, but I forgot to add entitlements.

3 - Added entitlements, and tried to run the app again. The app complained about needing a developer signing certificate due to entitlements, so I opened XCode and configured my developer account.

4 - Tried to run again from Android Studio, now it fails to launch the app. I tried going back to XCode, now it says build failed. I tried a `flutter clean` and I still get the same result. The output from AS and XCode are shown below:

Android Studio:
```
<module-includes>:1:1: warning: umbrella header for module 'FlutterMacOS' does not include header 'FLEViewController.h'
#import "Headers/FlutterMacOS.h"
^
note: Using new build system
note: Planning build
note: Constructing build description
Error waiting for a debug connection: The log reader stopped unexpectedly.
Error launching application on macOS.
```

XCode:
```
Runner
  - Swift Compiler Error
    - No such module 'file_chooser'
       GeneratedPluginRegistrant.swift
```

Version Info:

file_chooser ref: `7b6d3925b6cf6cde843c2680c232687d79177470`

Flutter version info:
```
Flutter 1.22.0-2.0.pre.123 • channel master • https://github.com/flutter/flutter.git
Framework • revision 366da56fb2 (2 hours ago) • 2020-08-28 19:19:37 -0400
Engine • revision 3f4f58f5f3
Tools • Dart 2.10.0 (build 2.10.0-73.0.dev)
```

**UPDATE:**
Just to see what would happen, I deleted my `macos` directory and regenerated it.

Initially after regeneration, the app built and ran.

Then I opened XCode and set my `Team` under `Signing & Capabilities`. After that I got the same build error again. I'm not sure what relevance the `Team` has here. My developer account should work just fine. I'm using it with other projects. But that seems to trigger something that breaks the build...

**UPDATE #2:**
After XCode failing to build as mentioned above, I decided to go back to AS and try to run again just for fun....shockingly it went ahead and built and run. I have no idea how XCode fails to even build but AS succeeds in building and running.

I then added the appropriate entitlements, and now I'm able to choose a file. I have no idea what has happened here, and XCode seems to still have a problem, but somehow I'm now unblocked.

I'm gonna leave this ticket open because there does seem to be a problem somewhere, I'm just not sure where it is or what the resolution should be...

**Comment by stuartmorgan** [comment]
> No such module 'file_chooser'

That suggests a `pod install` failure of some kind, so if there's a non-Xcode issue here it would be in the Flutter plugin tooling, not the `file_chooser` plugin. So this would need to be filed in the Flutter repo.
