### ISSUE TITLE
Chose directory in file_chooser

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [google/flutter-desktop-embedding#792]
**Describe Request**
 It would be great to have the opportunity to chose a directory instead of a file using `file_chooser`. Such an option would be necessary if you want the users to select a location once and access if (regardless of writing or reading) later several times or even frequently.

A common use case would be de default *library / documents* folder of a desktop app which should be configurable by the user.

**Comment by stuartmorgan** [comment]
https://github.com/google/flutter-desktop-embedding/blob/master/plugins/file_chooser/lib/src/utilities.dart#L25

**Comment by kakyoism** [comment]
> https://github.com/google/flutter-desktop-embedding/blob/master/plugins/file_chooser/lib/src/utilities.dart#L25

For whoever stumbled upon this question, the link above is broken, but this feature is now a part of the example app, as `Open a get directory dialog` button.

**Comment by stuartmorgan** [comment]
That link is broken because file_chooser, which is what this was about, no longer exists.
