### ISSUE TITLE
How can i change the application icon and remove the maximize button ?

### ISSUE THREAD

**Issue by gdias1992** [google/flutter-desktop-embedding#803]
I need guidance.

How can i change the default icon and remove the maximize button from the desktop app ?

![cryptogamer](https://user-images.githubusercontent.com/25283876/95667190-f0be2780-0b38-11eb-96c4-60bca5e601e6.PNG)

Thanks :D

**Comment by pascal91DA** [comment]
You can change .ico file in _windows/runner/resources_ folder.

However, to hide the maximize button, you need to change the GWL_STYLE attribute in the SetWindowLong function, so it no longer includes WS_MINIMIZEBOX, WS_MAXIMIZEBOX, etc. flags.

More info [here](https://docs.microsoft.com/ru-ru/windows/win32/api/winuser/nf-winuser-setwindowlonga?redirectedfrom=MSDN).

**Comment by gdias1992** [comment]
> You can change .ico file in _windows/runner/resources_ folder.
> 
> However, to hide the maximize button, you need to change the GWL_STYLE attribute in the SetWindowLong function, so it no longer includes WS_MINIMIZEBOX, WS_MAXIMIZEBOX, etc. flags.
> 
> More info [here](https://docs.microsoft.com/ru-ru/windows/win32/api/winuser/nf-winuser-setwindowlonga?redirectedfrom=MSDN).

Thank you very much!

**Comment by gdias1992** [comment]
I was able to disable the maximize button editing the win32_window.cpp.

I added changed the code "WS_OVERLAPPEDWINDOW | WS_VISIBLE" with "(WS_OVERLAPPEDWINDOW | WS_VISIBLE) & ~WS_MAXIMIZEBOX" and it worked like a charm.

![github](https://user-images.githubusercontent.com/25283876/95670514-9e91fc00-0b62-11eb-96ff-be6d3bf19523.PNG)

**Comment by stuartmorgan** [comment]
> I need guidance.

Please use resources like StackOverflow for questions; the issues tracker is for issues. Also, please [read the README](https://github.com/google/flutter-desktop-embedding#feedback), as nothing here is related to the plugins in this repository.
