### ISSUE TITLE
window_size plugin crash during app destroy process

### ISSUE THREAD

**Issue by imReker** [google/flutter-desktop-embedding#806]
When app is going to destroy (eg, close the window), it'll crash at: https://github.com/google/flutter-desktop-embedding/blob/8ea9f1ce79f04e44bd6392f4155a014b0a7eb6e8/plugins/window_size/windows/window_size_plugin.cpp#L181

When `RegisterTopLevelWindowProcDelegate`, the `PluginRegistrarWindows` store the delegate in it's member:`window_proc_delegates_`, and it seems like `PluginRegistrarWindows` destructed `window_proc_delegates_` before destruct the plugin. So, when the plugin tries to `UnregisterTopLevelWindowProcDelegate`, the std::map is already destroyed and lead to crash.

**Comment by stuartmorgan** [comment]
Good catch, thanks for the report. This is actually a bug in the client_wrapper code in flutter/engine rather than the plugin itself, since the registrar is supposed to be valid for the entire lifetime of the plugin.
