### ISSUE TITLE
[file_chooser]  Build process failed on Windows

### ISSUE THREAD

**Issue by bigbadboii1025** [google/flutter-desktop-embedding#809]
pc_demo\windows\flutter\ephemeral\.plugin_symlinks\file_chooser\windows\file_chooser_plugin.cpp(16,10): fatal error C1083: Unable to open include file: “ShObjIdl_core.h”: No such file or directory pc_demo\build\windows\plugins\file_chooser\file_chooser_plugin.vcxproj]

**Comment by stuartmorgan** [comment]
Please post the output of `flutter doctor -v`, as the bug template asked for.

**Comment by 926** [comment]
Hey @stuartmorgan long time no issue,
Same problem here :
boolValue / StringValue...  are not members of 'flutter::EncodableValue'

file chooser is declared in the yaml just like this :

  file_chooser:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/file_chooser
      ref: 282bb7b

here is what the doctor says :

S C:\Users\LENOVO\Desktop\yobi_windows_ok> flutter doctor -v
[√] Flutter (Channel master, 1.24.0-8.0.pre.304, on Microsoft Windows [Version 10.0.18363.1198], locale en-GB)
    • Flutter version 1.24.0-8.0.pre.304 at C:\Users\LENOVO\Documents\flutter
    • Framework revision c6290500f8 (6 days ago), 2020-11-18 17:29:28 -0800
    • Engine revision 35a0b9fe68
    • Dart version 2.12.0 (build 2.12.0-50.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\LENOVO\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30523.141
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.51.1)
    • VS Code at C:\Users\LENOVO\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (1 available)
    • Windows (desktop) • windows • windows-x64 • Microsoft Windows [Version 10.0.18363.1198]

**Comment by 926** [comment]
Here is what flutter gives after running flutter upgrade (issue persists)

[√] Flutter (Channel master, 1.24.0-8.0.pre.366, on Microsoft Windows [Version 10.0.18363.1198], locale en-GB)
    • Flutter version 1.24.0-8.0.pre.366 at C:\Users\LENOVO\Documents\flutter
    • Framework revision 2c793bb700 (4 hours ago), 2020-11-25 04:28:03 -0500
    • Engine revision 8eb8bd153f
    • Dart version 2.12.0 (build 2.12.0-75.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\LENOVO\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30523.141
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.51.1)
    • VS Code at C:\Users\LENOVO\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (1 available)
    • Windows (desktop) • windows • windows-x64 • Microsoft Windows [Version 10.0.18363.1198]

• No issues found!

**Comment by stuartmorgan** [comment]
Closing due to lack of response.

> Same problem here :
> boolValue / StringValue... are not members of 'flutter::EncodableValue'

That's not the same problem. The reported error here was

> file_chooser_plugin.cpp(16,10): fatal error C1083: Unable to open include file: “ShObjIdl_core.h”: No such file or directory

which is completely different. Your issue is that you're using a very old version of the plugin with the latest version of Flutter, which this project has never supported.

**Comment by bigbadboii1025** [comment]
> Please post the output of `flutter doctor -v`, as the bug template asked for.

[√] Flutter (Channel master, 1.24.0-8.0.pre.356, on Microsoft Windows [Version 6.3.9600], locale zh-CN)
    • Flutter version 1.24.0-8.0.pre.356 at C:\flutter\flutter
    • Framework revision e6bd95bc5c (2 days ago), 2020-11-23 14:10:58 -0800
    • Engine revision 23a8e027db
    • Dart version 2.12.0 (build 2.12.0-62.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.5.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
    • Visual Studio Professional 2019 version 16.5.30002.166
    • Windows 10 SDK version 10.0.18362.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at C:\IDE\IntelliJ IDEA 2020.1.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (1 available)
    • Windows (desktop) • windows • windows-x64 • Microsoft Windows [Version 6.3.9600]

! Doctor found issues in 2 categories.

**Comment by 926** [comment]
Thanks Stuart,
Indeed switching to the new file picker pub fixed it : https://pub.dev/packages/filepicker_windows

**Comment by stuartmorgan** [comment]
> Indeed switching to the new file picker pub fixed it

That's a completely different, and unrelated, plugin. If you prefer using it, that's fine, but just updating to the current version of this repository was all you needed to do.

**Comment by stuartmorgan** [comment]
@bigbadboii1025 I just landed an update to the way that include is done; that may resolve your issue. (If not, I suspect there's an issue with your Windows SDK installation.)

**Comment by 926** [comment]
yours is quicker, I updated the commit ref, works like a charm, thanks again :)

**Comment by bigbadboii1025** [comment]
> @bigbadboii1025 I just landed an update to the way that include is done; that may resolve your issue. (If not, I suspect there's an issue with your Windows SDK installation.)

it's work，resolve the issue， Thanks！
