### ISSUE TITLE
[filer_chooser] need dart 2.20 while flutter newest version shiped only with 2.10.4

### ISSUE THREAD

**Issue by jinfagang** [google/flutter-desktop-embedding#810]
How to build it anyway? Try upgrade flutter don't work.

**Comment by stuartmorgan** [comment]
I don't know how you came to that conclusion; there is no such restriction:
https://github.com/google/flutter-desktop-embedding/blob/master/plugins/file_chooser/pubspec.yaml#L19-L24

**Comment by jinfagang** [comment]
@stuartmorgan  Sorry, it's 2.12, higher than flutter default shipped one

**Comment by stuartmorgan** [comment]
```
$ flutter --version
Flutter 1.24.0-8.0.pre.187 • channel master •
https://github.com/flutter/flutter.git
Framework • revision 3700061b13 (6 days ago) • 2020-11-10 17:41:59 -0500
Engine • revision caf678d30f
Tools • Dart 2.12.0 (build 2.12.0-31.0.dev)
```
