### ISSUE TITLE
 [file_selector_linux] is this pluge didnt support below gtk3.2?

### ISSUE THREAD

**Issue by WGHCWC** [google/flutter-desktop-embedding#824]
`
linux/flutter/ephemeral/.plugin_symlinks/file_selector_linux/linux/file_selector_plugin.cc:115:31: error: use of undeclared identifier 'gtk_file_chooser_native_new'
`
`
/linux/flutter/ephemeral/.plugin_symlinks/file_selector_linux/linux/file_selector_plugin.cc:154:41: error: use of undeclared identifier 'GTK_NATIVE_DIALOG'`

**Comment by stuartmorgan** [comment]
Assuming you mean 3.20, not 3.2, that is correct. Supporting GTK versions that are more than five years old is not a priority.
