### ISSUE TITLE
'file_selector_macos' plugin ignores/overrides the preferred macOs's display language when showing open and save panel

### ISSUE THREAD

**Issue by shrey112710** [google/flutter-desktop-embedding#825]
The open and save panel's label's text is always in English even when my macOS's preferred(display) language is set to German. _I have tested 'file_selector_windows' on windows and it works perfectly without showing this bug,_ however, On macOS, the **default language seems to be English instead of German for the open and save panel**. Please refer to the attached screenshots to get a better understanding of the above-mentioned bug:-

**For Open Panel in macOS:** 
**Expected behavior:** 
![image](https://user-images.githubusercontent.com/65033125/105171304-577eb400-5b1e-11eb-85cb-6bf51029716e.png)

**Actual behavior:**
![image](https://user-images.githubusercontent.com/65033125/105171422-8006ae00-5b1e-11eb-9719-def841a021e4.png)

**For Save Panel in macOS:**
**Expected behavior:** 
![image](https://user-images.githubusercontent.com/65033125/105171576-b04e4c80-5b1e-11eb-8d10-11f94409a003.png)

**Actual behavior:**
![image](https://user-images.githubusercontent.com/65033125/105171728-dc69cd80-5b1e-11eb-9035-c6780a7d68e4.png)

**Comment by stuartmorgan** [comment]
The open panel has no language control; like any other native UI, it will use the language that macOS is running your application in, which is the first one on your ordered list of preferred languages (at the OS level) that your application declares support for. If your native UI is in English when your OS is set to German, then you haven't informed the OS that your application supports German, either via a German lproj, or via CFBundleLocalizations.

I filed https://github.com/flutter/flutter/issues/74321 to track documenting this (as it currently is for iOS) when the macOS release process is documented.
