### ISSUE TITLE
'file_selector' does not allow to select multiple directories in desktop's native open panel

### ISSUE THREAD

**Issue by shrey112710** [google/flutter-desktop-embedding#826]
Earlier `file_chooser` allowed the user to select multiple directories in the desktop's native open panel. Now that file_chooser has been superseded by `file_selector` it is obvious to use the latter but it does not allow the user to select multiple directories. It would be nice to have that functionality in `file_selector`, for desktop, as well.

**Comment by stuartmorgan** [comment]
The API for `file_selector` is controlled by [the front-end plugin](https://github.com/flutter/plugins/tree/master/packages/file_selector/file_selector); what is in this repository is just implementations of that interface. Requests for new APIs need to be made against the main plugin in flutter/flutter. (IIRC I raised this during the API design discussion for `file_selector`, and there were questions about whether it was something anyone would actually want to do, so it would be helpful when you file the request there you explain the use case.)
