### ISSUE TITLE
flutter to windows error

### ISSUE THREAD

**Issue by codersu007** [google/flutter-desktop-embedding#829]
Flutter is released as windows, embedded in the windows window, click to minimize and then open again, the window freezes, five responses

**Comment by stuartmorgan** [comment]
From https://github.com/google/flutter-desktop-embedding/blob/master/README.md:

> **Do not file issues about Flutter for desktop here.** Since the
embeddings have all moved to the Flutter project, the place for desktop bugs
and feature requests is now [the Flutter issue
tracker](https://github.com/flutter/flutter/issues).

This report is not related to any of the plugins in this repository, so closing.
