### ISSUE TITLE
window_size does not save the latest dimensions and position of the window on macOS Big Sur

### ISSUE THREAD

**Issue by moazelshebly** [google/flutter-desktop-embedding#830]
**Describe the bug**
It seems that since macOS Big Sur came out, the window dimensions and position of the last app session are not saved anymore. This leads to the app being launched every time in the same position and same dimension that are set in the app and not the ones that the user set during their last use of the app. 

It used to work on macOS Catalina but now it is not anymore.

**Doctor Output**
```
[✓] Flutter (Channel dev, 1.26.0-12.0.pre, on macOS 11.2 20D64 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-12.0.pre at /Users/moazelshebly/flutter
    • Framework revision a706cd2112 (3 weeks ago), 2021-01-14 18:20:26 -0500
    • Engine revision effb529ece
    • Dart version 2.12.0 (build 2.12.0-224.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/moazelshebly/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2 20D64 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.96

• No issues found!

```

**Comment by stuartmorgan** [comment]
The `window_size` plugin has never had that functionality; any restoration behavior you saw previously was entirely controlled by the OS.

Given that it's relatively straightforward to implement that logic in Dart using existing `window_size` functionality and something like `shared_preferences`, I don't plan to implement auto-save in this temporary plugin. (It's certainly something that would be reasonable to build into the eventual Flutter framework support for window management.)

**Comment by jagmit** [comment]
@stuartmorgan Sorry for bothering you again, but this feature that an application window restores it's dimensions and position from a previous session is common on Windows and macOS and the absence of it makes Flutter application feel less native on desktop. I think it is worth considering whether this should be implemented as a default behaviour.

As you have stated it is trivial to implement such behaviour thanks to the great `window_size` and `shared_preferences` plugins, but I am having difficulties figuring out when and where to hook into a "application window closed" event to read and persist the dimensions and position somewhere.

Can you give a hint where this could be done? Maybe somewhere in Dart, in the runner application or as part of the engine?
