### ISSUE TITLE
[window_size] Add title bar height to window info

### ISSUE THREAD

**Issue by aloisdeniel** [google/flutter-desktop-embedding#838]
I would like to know how big is the title bar since it is included in window size. Since each version of an operating system has a different behaviour it is difficult to deal with it.

```dart
final info = await getWindowInfo();
print('${info.barHeight}');
```

For the context, I want to have a window of a certain ratio, based on a device frame : 

![image](https://user-images.githubusercontent.com/7687231/111281672-7d679700-863d-11eb-958e-221899f19a18.png)

**Comment by stuartmorgan** [comment]
Adding a content rect to `PlatformWindow` seems reasonable. (Although I believe you could figure this out for the standard case of a windows containing nothing but a full-content-area Flutter view with the current API by getting the current window's information and comparing that to the size from `MediaQuery`.)

**Comment by aloisdeniel** [comment]
Thanks for the answer. 

You're right, something like this should do the trick : 

```dart
 final windowBarHeight = info.frame.height -
            (ui.window.physicalSize.height / ui.window.devicePixelRatio);
```

**Comment by stuartmorgan** [comment]
Per [the updated scope](https://github.com/google/flutter-desktop-embedding/blob/master/plugins/window_size/README.md#scope) of this plugin, this isn't something that will be added. I would encourage you to review the multi-window design doc linked from that README and leave feedback if the proposed APIs wouldn't address your use case.
