### ISSUE TITLE
Null safety not implemented

### ISSUE THREAD

**Issue by zeeshan-iqbal-cs** [google/flutter-desktop-embedding#845]
With the introduction of sound null safety, this library cannot be included in the project where sound null safety is enabled.
```
CUSTOMBUILD : error : Cannot run with sound null safety, because the following dependencies 
```

**Comment by stuartmorgan** [comment]
> this library cannot be included in the project where sound null safety is enabled.

Which library? This repository is a collection of separate packages.

> ```
> CUSTOMBUILD : error : Cannot run with sound null safety, because the following dependencies 
> ```

You've cut off the part of this that lists the problematic dependencies.

All the packages here should support null safety, so this needs details about which packages--and which versions of those packages--you are using and having issues with.

**Comment by stuartmorgan** [comment]
Closing due to lack of response.

**Comment by kakyoism** [comment]
This is what I get when running an app using `file_selector`.
```
Launching lib/main.dart on macOS in debug mode...
Building macOS application...
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:file_selector
 - package:file_selector_platform_interface
 - package:plugin_platform_interface
 - package:cross_file
```

**Comment by stuartmorgan** [comment]
None of those plugins are part of this repository.
