### ISSUE TITLE
[window_size] Full macOS "file integration"

### ISSUE THREAD

**Issue by tp** [google/flutter-desktop-embedding#851]
**Describe Request**

Using `setWindowTitleRepresentedUrl` just shows the file's icon in the title bar.

I wish there was a way to enable the "full" file integration that document-based apps usually use on macOS, including the ability for the user of the app to easily rename and move the file.

![image](https://user-images.githubusercontent.com/52437/115118337-ff334300-9fa2-11eb-8fec-dd8836c9b339.png)

**Comment by stuartmorgan** [comment]
Configuring the application as a document-based application on macOS is out of scope for this plugin.

Someone else is certainly welcome to try to make such a plugin; I suspect some amount of modification to the runner itself would be necessary. (And if the goal is to support multiple windows, which each window running an engine instance, it'll be even more complicated to try to do via a plugin.)
