### ISSUE TITLE
[Windows] How can I create or write on disk C? Do I need permission to do this? If yes, please tell me the way I can do it 

### ISSUE THREAD

**Issue by manle93** [google/flutter-desktop-embedding#861]
**Describe Request**
When I use the method File.create(). It have exception:

[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: FileSystemException: Creation failed, path = 'C:\Windows\System32\isana\log\app' (OS Error: Access is denied., errno = 5)

**Comment by stuartmorgan** [comment]
https://github.com/google/flutter-desktop-embedding/blob/master/README.md#feedback
