### ISSUE TITLE
[windows] flutter_location needs a .bat version

### ISSUE THREAD

**Issue by stuartmorgan** [google/flutter-desktop-embedding#88]
Currently tools/flutter_location is only a bash script, so Windows still requires that the Flutter tree be at a known location for the tooling to work. We need a .bat port, at which point update_flutter_engine.bat can use it the way update_flutter_engine uses flutter_location.

**Comment by gabrc52** [comment]
Or it could be made dependent on git bash

**Comment by stuartmorgan** [comment]
Requiring all clients to install an alternate execution environment just to avoid porting a 20-line script would be a very large hammer; I don't see any reason to go that route.

There's also the fact that the `flutter` tool has known issues in git bash and other similar environments, which would make requiring its use for `locate_flutter` confusing and potentially problematic.
