### ISSUE TITLE
can't set window size.

### ISSUE THREAD

**Issue by Sevencats** [google/flutter-desktop-embedding#889]
### Is this a bug in one of the plugins in this project?

- [X] I have read [the README section about feedback](https://github.com/google/flutter-desktop-embedding/blob/master/README.md#feedback).
- [X] My issue is about one of the plugins in this repository.

### Which plugin is this bug report about?

window_size

### Describe the bug

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method setWindowMinimumSize on channel flutter/windowsize)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>
#1      WindowSizeChannel.setWindowMinSize (package:window_size/src/window_size_channel.dart:167:5)
<asynchronous suspension>

### Flutter doctor

```bash
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 2.6.0-0.0.pre, on Microsoft Windows [Version 10.0.19042.572], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
[√] Android Studio (version 4.2)
[!] Android Studio
    X android-studio-dir = C:\Users\PC\AppData\Roaming\Google\AndroidStudio4.2
    X Unable to find bundled Java version.
[√] Connected device (3 available)
```

**Comment by Sevencats** [comment]
![image](https://user-images.githubusercontent.com/56510404/133017499-58db7a0b-de5c-4b68-b49c-3cd6dfc5aafa.png)

**Comment by stuartmorgan** [comment]
Please provide the pubspec.yaml section (the actual text, not a picture of it) you are using to include `window_size`.

**Comment by stuartmorgan** [comment]
Closing due to lack of response.

@ggdream Please file a new issue with details of your issue.
