### ISSUE TITLE
"Unable to parse platform message" when running on Linux

### ISSUE THREAD

**Issue by gabrc52** [google/flutter-desktop-embedding#89]
Terminal output displays this:

```
Unable to parse platform message
* Line 2, Column 1
  Syntax error: value, object or array expected.
```

Because of that, the example can't load or save files (Edit: the file chooser does appear but no files are saved or loaded, so working as intended)

Distribution details:
```
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=17.1.10
DISTRIB_CODENAME=Hakoila
DISTRIB_DESCRIPTION="Manjaro Linux"
Linux Lenovo 4.16.14-2-MANJARO #1 SMP PREEMPT Fri Jun 8 20:10:17 UTC 2018 x86_64 GNU/Linux
```

To anyone else using this distro, I had to remove the unnecessary parentheses in the gtk3 header files so it compiled

**Comment by stuartmorgan** [comment]
> Terminal output displays this

What exactly are you doing when you get this message? You mention the file chooser; is this when you close the native dialog after selecting a file?

> no files are saved or loaded

They aren't supposed to be, it just shows a snackbar with the results of the dialog. Are you not seeing that?

**Comment by gabrc52** [comment]
> What exactly are you doing when you get this message? You mention the file chooser; is this when you close the native dialog after selecting a file?

As soon as I launch the app.

> They aren't supposed to be, it just shows a snackbar with the results of the dialog. Are you not seeing that?

It's working as intended

**Comment by gabrc52** [comment]
I couldn't reproduce it again

**Comment by stuartmorgan** [comment]
I just hit this on macOS. I don't know for sure if your case was the same, but there are cases where Flutter will send things on the flutter/accessibility channel. That doesn't use the JSON codec, so will cause this message.

In the short term I'll drop that silently (and improve the error message to include the channel in case something else comes up in the future).
