### ISSUE TITLE
Could not find a file named "plugins/file_chooser/pubspec.yaml

### ISSUE THREAD

**Issue by juzimmer** [google/flutter-desktop-embedding#893]
### Is this request within the scope of this project?

- [X] I have read [the README section about feedback](https://github.com/google/flutter-desktop-embedding/blob/master/README.md#feedback).
- [X] My request is specifically related to this repository, not Flutter's desktop support.

### Which plugin is this request about?

Other feedback

### Describe the request

I'm trying to implement this plugin but I'm getting a debug build error.

`Could not find a file named "plugins/file_chooser/pubspec.yaml" in git://github.com/google/flutter-desktop-embedding.git 03d957e8b5c99fc83cd4a781031b154ab3de8753.
pub get failed (1; Could not find a file named "plugins/file_chooser/pubspec.yaml" in git://github.com/google/flutter-desktop-embedding.git 03d957e8b5c99fc83cd4a781031b154ab3de8753.)`

I'm using;

file_chooser:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/file_chooser
      ref: 03d957e8b5c99fc83cd4a781031b154ab3de8753

**Comment by stuartmorgan** [comment]
That plugin was removed a year ago; the README in that folder clearly states that the plugin no longer exists. The error message you are receiving is expected if you point your pubspec to a folder that isn't a plugin.

**Comment by juzimmer** [comment]
Sorry. Is there a new package in flutter now that will get windows api screen width?

**Comment by stuartmorgan** [comment]
I'm not sure what you are asking, but it doesn't sound at all related to what `file_chooser` was.

If you're looking for information on what the plugins in this repository do, the READMEs and documentation comments should cover it.

**Comment by ggdream** [comment]
@juzimmer If I understand what you think, I think you can try `window_size`
