### ISSUE TITLE
[menubar] Add "disabled" boolean on NativeMenuItem

### ISSUE THREAD

**Issue by vmichalak** [google/flutter-desktop-embedding#908]
### Is this request within the scope of this project?

- [X] I have read [the README section about feedback](https://github.com/google/flutter-desktop-embedding/blob/master/README.md#feedback).
- [X] My request is specifically related to this repository, not Flutter's desktop support.

### Which plugin is this request about?

menubar

### Describe the request

Currently the only way to grey out (disabled) a NativeMenuItem for the User is assigning the onSelected to null. Adding a "disabled" property can be more simple to use in a lot of cases.

Thanks a lot for your job here, it's helpful.

**Comment by stuartmorgan** [comment]
This was changed deliberately in https://github.com/google/flutter-desktop-embedding/pull/903 to align with the new Flutter framework API.
