### ISSUE TITLE
Git error. Command: `git clone --mirror git://github.com/google/flutter-desktop-embedding.git

### ISSUE THREAD

**Issue by kanakapalli** [google/flutter-desktop-embedding#914]
### Is this a bug in one of the plugins in this project?

- [X] I have read [the README section about feedback](https://github.com/google/flutter-desktop-embedding/blob/master/README.md#feedback).
- [X] My issue is about one of the plugins in this repository.

### Which plugin is this bug report about?

menubar

### Describe the bug

I'm trying to run an old flutter project, when I'm trying to run in macOS <latest> but I'm getting this error

```
Git error. Command: `git clone --mirror git://github.com/google/flutter-desktop-embedding.git /<path>r/flutter/.pub-cache/git/cache/flutter-desktop-embedding-87b62662532896a522efe2d4fc10c086d1a2768b`
stdout: 
stderr: Cloning into bare repository '/<path>/flutter/.pub-cache/git/cache/flutter-desktop-embedding-87b62662532896a522efe2d4fc10c086d1a2768b'...
fatal: unable to connect to github.com:
github.com[0: 20.207.73.82]: errno=Operation timed out
```

### Flutter doctor

```bash
octor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-arm, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.74.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by stuartmorgan** [comment]
> fatal: unable to connect to github.com:
> github.com[0: 20.207.73.82]: errno=Operation timed out

If your development environment can't connect to github.com, that's something you'll need to resolve on your side.
