### ISSUE TITLE
is there in Flutter itself already ?

### ISSUE THREAD

**Issue by fehernyul** [google/flutter-desktop-embedding#918]
### Is this request within the scope of this project?

- [X] I have read [the README section about feedback](https://github.com/google/flutter-desktop-embedding/blob/master/README.md#feedback).
- [X] My request is specifically related to this repository, not Flutter's desktop support.

### Which plugin is this request about?

window_size

### Describe the request

You wrote, I don't need to use this package because this will placed in the Flutter system itself.
How can I use this functionality from Flutter itself and not from this package?

Thanks,
Gabor

**Comment by stuartmorgan** [comment]
> You wrote, I don't need to use this package

That is not what the readme says.

> because this will placed in the Flutter system itself.

It doesn't say that it will, it says: "in the long term [it] is expected to be replaced by functionality within the Flutter framework." That's not a guarantee.

> How can I use this functionality from Flutter itself and not from this package?

If you want to use functionality that doesn't exist in the Flutter SDK yet, but want to use it from the Flutter SDK, you would need to wait until it is implemented.

Closing as there is not issue or request here.
