### ISSUE TITLE
Run Flutter app in windows 32 bit

### ISSUE THREAD

**Issue by AndroidDesigner** [google/flutter-desktop-embedding#920]
### Is this request within the scope of this project?

- [X] I have read [the README section about feedback](https://github.com/google/flutter-desktop-embedding/blob/master/README.md#feedback).
- [X] My request is specifically related to this repository, not Flutter's desktop support.

### Which plugin is this request about?

Other feedback

### Describe the request

Hello.
As you know, flutter is not running in windows 32 bit.
Can I use this package to run my own flutter desktop app on a windows 32 bit?

**Comment by stuartmorgan** [comment]
> [x] I have read [the README section about feedback](https://github.com/google/flutter-desktop-embedding/blob/master/README.md#feedback).

When issue templates include checkboxes like this, it's for a reason; please don't just blindly check them.
