### ISSUE TITLE
Publish in pub dev

### ISSUE THREAD

**Issue by ARASHz4** [google/flutter-desktop-embedding#921]
### Is this request within the scope of this project?

- [x] I have read [the README section about feedback](https://github.com/google/flutter-desktop-embedding/blob/master/README.md#feedback).
- [x] My request is specifically related to this repository, not Flutter's desktop support.

### Which plugin is this request about?

menubar

### Describe the request

Please publish this package to pub.dev

**Comment by stuartmorgan-g** [comment]
Please see https://github.com/google/flutter-desktop-embedding/tree/main/plugins#using-plugins and https://github.com/google/flutter-desktop-embedding/tree/main/plugins/menubar#menubar which address why this plugin is not published.
