### ISSUE TITLE
Support rich mouse events

### ISSUE THREAD

**Issue by stuartmorgan** [google/flutter-desktop-embedding#93]
The embedding API needs a way to provide rich mouse events (right click, scroll wheel, mouse move, etc.). This is to track proposing that on the Flutter side, and then implementing it in the platform embedders if it's accepted.

If that's accepted, then it will be possible to start adding support for these things in Flutter widgets (e.g., scrolling lists using the scroll wheel).

**Comment by jld3103** [comment]
+1

**Comment by stuartmorgan** [comment]
Scroll wheel and mouse move have been added, and non-primary-button handling is in development. Since the overall API structure is established, having a tracking but that's this high-level/vague is no longer useful.

If there are things other than the above that are missing, they should be filed as specific new bugs in the Flutter repository to be tracked individually.

**Comment by Joematpal** [comment]
I love the mouse and scroll wheel features. They have come in handy. Thanks, Flutter team! Is there a timeline or roadmap for the non-primary button features?

**Comment by stuartmorgan** [comment]
https://github.com/flutter/flutter/issues/33220 is the issue you're looking for at this point.
