### ISSUE TITLE
Support drag and drop

### ISSUE THREAD

**Issue by stuartmorgan** [google/flutter-desktop-embedding#97]
This will require #96, but also some notion of a widget being able to declare itself as a drag target and/or source.

It's not entirely clear how much of this will need to be on the native side vs. the Dart side. I suspect dropping into the app will be easier to support than dragging out, but both will require careful thought about how to straddle the native/Dart divide (e.g., how to track rectangles for drag targets).

**Comment by RazaGR** [comment]
lovely...
will it support dataType like in HTML? https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API/Recommended_drag_types
Text, Image, Files etc

**Comment by stuartmorgan** [comment]
I don't know what the specific API will look like, but if you are primarily asking whether this would support more than just text, yes.

**Comment by stuartmorgan** [comment]
Moved to https://github.com/flutter/flutter/issues/30719
